### ISSUE TITLE
Strings: wrong handling of % symbol

### ISSUE THREAD

**Issue by maltsevoff** [SwiftGen/SwiftGen#1012]
SwiftGen misinterprets the string below. I'm using pod version `6.6.2`

> Buy on 0% installments with

It creates function as below instead of a parameter 
```Swift
public static func installment(_ p1: Int) -> String {
         return "project.installment".localizeWithFormat(arguments: p1)
}
```

I also tried to use double percent (%%). It creates parameter for this string but just showing this percent symbol twice in returning string.

**Comment by djbe** [comment]
You're right that you need to use the double `%` to escape it. The rest of your issue I honestly don't know, because you seem to be using a custom template 🤷 

See older issues such as https://github.com/SwiftGen/SwiftGen/issues/577 for a much more in-depth discussion about this.
