### ISSUE TITLE
Stencil template type

### ISSUE THREAD

**Issue by parski** [SwiftGen/SwiftGen#1074]
I use SwiftGen for things like assets and strings in a project. Now I need to generate some arbitrary files not directly related to anything Swift or Xcode specific, but still in the project, and to do that I want to use a templating engine. [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit) looks good but it's not a command line utility. SwiftGen is a command line utility but it's making me use `colors`, `yaml`, `plist`, etc when I'm trying to just use a template.

I would like a subcommand that will parse some standard of object notation like YAML, JSON, etc, and populate a template.

Like this:

**input.json**
```json
{
   "name": "Mario"
}
```

**template.stencil**
```stencil
It's-a me, {{ name }}!
```

Command line:
```shell
$ swiftgen run json-generic --templatePath template.stencil input.json
It's-a me, Mario!
```

I get that maybe this isn't what SwiftGen tries to be but it would sure be handy. I want to avoid adding another dependency to the project and SwiftGen is so close to doing this so I thought I'd at least raise the issue.

**Comment by Liquidsoul** [comment]
I'm a little dusty on this but did you try using the [JSON/YAML commands](https://github.com/SwiftGen/SwiftGen/blob/1cf6d7eebd70c2157f69d5a991bc57c1ef182ed1/README.md#json-and-yaml) with custom templates?

I'll close this issue for triage purpose, feel free to reopen it if necessary.
