### ISSUE TITLE
How to remove SwiftGen from a project?

### ISSUE THREAD

**Issue by Gargo** [SwiftGen/SwiftGen#1076]
I got a project with SwiftGen and I need to delete it due to some reasons. Are there any recommendations how to do that correctly?

**Comment by Liquidsoul** [comment]
It depends on your project and what you want to achieve and you did not provide your usage of SwiftGen.

I cannot really help you with your context but note that if you remove the SwiftGen step, you'll have to either:
- update the previously generated code manually when you update your data
- remove the generated code entirely and replace all the call the generated code with name-based calls to access your data
