### ISSUE TITLE
Some problem on Xcode 15

### ISSUE THREAD

**Issue by Lobsterrinho** [SwiftGen/SwiftGen#1082]
Hi there, I faced with problem after updating to new Xcode 15 and MacOS Sonoma. When Im trying to build or run project I receive build error:

error: 1 duplicate report for Sandbox: swiftgen(67503) deny(1) file-read-data /Users/lobster/watchfaceseditor/Pods/SwiftGen/bin (in target 'WatchFacesEditor' from project 'WatchFacesEditor')
error: Sandbox: swiftgen(67503) deny(1) file-read-data /Users/lobster/watchfaceseditor/Pods/SwiftGen/bin (in target 'WatchFacesEditor' from project 'WatchFacesEditor')
error: Sandbox: swiftgen(67503) deny(1) file-read-data /Users/lobster/watchfaceseditor/Pods/SwiftGen/bin (in target 'WatchFacesEditor' from project 'WatchFacesEditor')
Error: The file “swiftgen.yml” couldn’t be opened because you don’t have permission to view it.

maybe someone already had same or near problem? (the code number in brackets may changes after Xcode reopen)

**Comment by matijakregarGH** [comment]
Try changing `ENABLE_USER_SCRIPT_SANDBOXING` to `NO` in target Build Settings.

**Comment by Lobsterrinho** [comment]
> Try changing `ENABLE_USER_SCRIPT_SANDBOXING` to `NO` in target Build Settings.

so, it helped... thanks u a lot, but could u please explain what that means? if I understood correctly this may restrict publishing into App Store, am I right?

**Comment by matijakregarGH** [comment]
I haven't done much research, however I don't see an issue with the App Store though. If I understand correctly this setting only affects the folder access of the scripts in the build phases. Don't take my word for it. I just came upon the same issue as you did today. Maybe you should open the issue again and the team could put a note on this in the documentation.

**Comment by Lobsterrinho** [comment]
> I haven't done much research, however I don't see an issue with the App Store though. If I understand correctly this setting only affects the folder access of the scripts in the build phases. Don't take my word for it. I just came upon the same issue as you did today. Maybe you should open the issue again and the team could put a note on this in the documentation.

TY so much mate, u really helped me, take ur best every time!!!
