### ISSUE TITLE
Color Generated with SwiftUI 

### ISSUE THREAD

**Issue by MoElkilany** [SwiftGen/SwiftGen#1091]
Hello everyone,

When I use SwiftGen colors with SwiftUI's Text or Button components, I encounter an error. Please help me resolve this issue.

Example:-
Text("Hello World")
                    .foregroundColor(ColorName.color53B44B.color)

Error:-
Cannot convert the value of type 'Color' (aka 'UIColor') to expected argument type 'Color?'

![Screenshot 2023-12-05 at 11 04 13 AM](https://github.com/SwiftGen/SwiftGen/assets/45436838/e3895fac-1609-479e-977b-196991c2fa5e)

how can solve it ?

**Comment by kingiol** [comment]
Just use this to try.
`
Text("Hello World").foregroundColor(Color(uiColor: ColorName.color538448.color))
`

**Comment by MoElkilany** [comment]
thank you @kingiol  
it's working
