### ISSUE TITLE
[Homebrew] Error: swiftgen has been disabled because it does not build!

### ISSUE THREAD

**Issue by batkov** [SwiftGen/SwiftGen#1104]
Homebrew is not installing `swiftgen`.

I've tried installing older formulas, like `brew install swiftgen@6.6.0`, but it is not helping.

```
$ brew update
Already up-to-date.
$ brew install swiftgen
Error: swiftgen has been disabled because it does not build!
```

**Comment by isgallagher** [comment]
Try this. https://github.com/SwiftGen/SwiftGen/issues/1030#issuecomment-1960719499

**Comment by batkov** [comment]
@isgallagher this workaround worked. 

Copying for other unfortunate devs:

```
curl -Lo /tmp/swiftgen.rb https://raw.githubusercontent.com/iMichka/homebrew-core/17ae00b4bf1640cc544eae5f6eec03775c09420b/Formula/swiftgen.rb && brew install /tmp/swiftgen.rb && rm /tmp/swiftgen.rb
```

**Comment by muradtries** [comment]
> @isgallagher this workaround worked.
> 
> Copying for other unfortunate devs:
> 
> ```
> curl -Lo /tmp/swiftgen.rb https://raw.githubusercontent.com/iMichka/homebrew-core/17ae00b4bf1640cc544eae5f6eec03775c09420b/Formula/swiftgen.rb && brew install /tmp/swiftgen.rb && rm /tmp/swiftgen.rb
> ```

I've tried to replace `brew install swiftgen` with this command. However receiving an error and warning on the console:

```
Error: Failed to load cask: /tmp/swiftgen.rb
Cask 'swiftgen' is unreadable: wrong constant name #<Class:0x000000010ff17768>
Warning: Treating /tmp/swiftgen.rb as a formula.
```

How can I resolve this issue?

**Comment by gongzhang** [comment]
> > @isgallagher this workaround worked.
> > Copying for other unfortunate devs:
> > ```
> > curl -Lo /tmp/swiftgen.rb https://raw.githubusercontent.com/iMichka/homebrew-core/17ae00b4bf1640cc544eae5f6eec03775c09420b/Formula/swiftgen.rb && brew install /tmp/swiftgen.rb && rm /tmp/swiftgen.rb
> > ```
> 
> I've tried to replace `brew install swiftgen` with this command. However receiving an error and warning on the console:
> 
> ```
> Error: Failed to load cask: /tmp/swiftgen.rb
> Cask 'swiftgen' is unreadable: wrong constant name #<Class:0x000000010ff17768>
> Warning: Treating /tmp/swiftgen.rb as a formula.
> ```
> 
> How can I resolve this issue?

Already installed? Try `... && brew reinstall /tmp/swiftgen.rb && ...` 😉

**Comment by lhoracek** [comment]
We've replaced it with mint install.
`brew install mint`
`mint install SwiftGen/SwiftGen`

**Comment by VicenteAlbert** [comment]
> We've replaced it with mint install. `brew install mint` `mint install SwiftGen/SwiftGen`

Although this worked for me also, my project setup couldn't find the "swiftgen" command, even if I could run it from terminal. If you need specific homebrew installation, this worked for me:
```
1. disable homebrew's check update 'export HOMEBREW_NO_INSTALL_FROM_API=1', otherwise the installation will overwrite the file edited below
2. Manually change the repository file 'brew edit swiftgen', which will automatically edit the repository file using vim
3. find 'disable! date: "xxxx", because: xxxx', add # before it, comment out this line
4. ':wq' Save and exit edit
5. 'brew install swiftgen' to install
```

**Comment by isgallagher** [comment]
> > @isgallagher this workaround worked.
> > Copying for other unfortunate devs:
> > ```
> > curl -Lo /tmp/swiftgen.rb https://raw.githubusercontent.com/iMichka/homebrew-core/17ae00b4bf1640cc544eae5f6eec03775c09420b/Formula/swiftgen.rb && brew install /tmp/swiftgen.rb && rm /tmp/swiftgen.rb
> > ```
> 
> I've tried to replace `brew install swiftgen` with this command. However receiving an error and warning on the console:
> 
> ```
> Error: Failed to load cask: /tmp/swiftgen.rb
> Cask 'swiftgen' is unreadable: wrong constant name #<Class:0x000000010ff17768>
> Warning: Treating /tmp/swiftgen.rb as a formula.
> ```
> 
> How can I resolve this issue?

Break it into multiple commands and run each one at a time. It looks to me like the file is not downloading to /tmp/swiftgen.rb. Maybe /tmp does not exist or is not writable by your user?

**Comment by teejayhh** [comment]
```
brew install swiftgen
```

is part of our ci pipeline and I dont really want to make the `curl solution` the permanent fix. Will this be resolved so we can use brew again ? I tried mint but I had issues using swiftgen afterwards.

**Comment by isgallagher** [comment]
> We've replaced it with mint install. `brew install mint` `mint install SwiftGen/SwiftGen`

I am not able to get mint's install to actually work.

`SwiftGenCLI/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/removed/.mint/bin/SwiftGen_SwiftGenCLI.bundle or /private/var/folders/_8/cr5ngqns1n38s7l4tg3crv2m0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/SwiftGen_SwiftGenCLI.bundle
zsh: trace trap  ~/.mint/bin/swiftgen`

But it works when I use the curl brew install method.

**Comment by Liquidsoul** [comment]
Problem should be fixed once the homebrew-core PR gets merged 🤞 

Sorry for the inconvenience.

**Comment by batkov** [comment]
`brew install swiftgen` works now. Thanks
