### ISSUE TITLE
Apple privacy manifest support

### ISSUE THREAD

**Issue by pavm035** [SwiftGen/SwiftGen#1109]
Hi,

Apple is enforcing every app and SDK provider to provide privacy manifest in their SDK, would you please let me know is there any plan for the support?

https://developer.apple.com/support/third-party-SDK-requirements/
NOTE: I noticed this SDK is not listed in required list from apple

**Comment by Liquidsoul** [comment]
Hi @pavm035,

SwiftGen is not an SDK you embed in your application. It is a build tool you use to generate code you integrate in your application.  
As such, I do not see the need of supporting this in SwiftGen. So to answer your question:  
No, there is no plan to support this.

If there is a case I do not see that would require this, I am open to discuss this and I will welcome any contribution on this.

**Comment by pavm035** [comment]
Hi @Liquidsoul Thanks for the confirmation, if any request comes from apple will revisit this, thanks again!
