### ISSUE TITLE
Compilation error with Xcode 16.1 beta

### ISSUE THREAD

**Issue by Frizlab** [SwiftGen/SwiftGen#1138]
I have a project which has SwiftGen as a dependency (version 6.6.3).
Compilation fails on Xcode 16.1 beta with the following error: `mutable capture of 'inout' parameter 'buffer' is not allowed in concurrently-executing code`, in `Array+Parallel.swift`.

**Comment by ojun9** [comment]
I also encountered the same issue on `Xcode 16.1 Beta 1`. However, I can confirm that the issue is fixed when using `Xcode 16.1 Beta 2 (16B5014f)`.

**Comment by Frizlab** [comment]
It looks fixed indeed.
