### ISSUE TITLE
Support for loose images (outside of XCAssets).

### ISSUE THREAD

**Issue by jcampbell05** [SwiftGen/SwiftGen#146]

**Comment by AliSoftware** [comment]
I think that if PR #108 gets finished one day, and especially converted to be more general and being able to handle any file listing and not just nibs, it will be able to cover that somehow, by using that future command to simply list all PNG files?

**Comment by djbe** [comment]
This feature was implemented as part of 6.5.0, which was released a while ago. Use the new `files` parser for these and other needs.
