### ISSUE TITLE
Xcode 8 extension for Storyboards

### ISSUE THREAD

**Issue by Jeehut** [SwiftGen/SwiftGen#151]
Now that Xcode 8 has in-editor support for both autocompleting and representing images right within the code it seems this replaces SwifGens support for images for most common usage cases (I've tested it and it works like a charm). Although I haven't tested the color feature yet there seems to be something similar for it, too.

Also Xcode now has the ability to install extensions that do similar work like the integration of images right within the editor. So my question is, what do you think of the idea of implementing SwiftGen as a Xcode 8 extension and adding all supported features right into the text editor?

As a first start I think it would be most useful to add the Storyboards or Strings feature (as these are things Xcode 8 doesn't support itself) and simply both provide autocompletion **and** replace the Storyboard initialization calls by something like a label stating the name of the Storyboard / key of the String and a Storyboard/Strings icon. Would anybody be interested in implementing this? :)

**Comment by AliSoftware** [comment]
Tbh I'd love that feature!… but I sadly know I won't have the time to play with Xcode extensions and make one for SwiftGen myself anytime soon, too much work already lately.

So if anyone is willing to start this and give it a try I'd love it!

**Comment by djbe** [comment]
With the evolution of SPM and the addition of package plugins (see #913), I'm going to consider this issue closed (deprecated) for now.
