### ISSUE TITLE
CoreData support

### ISSUE THREAD

**Issue by Igor-Palaguta** [SwiftGen/SwiftGen#185]
Hello,

Are you planning to add core data support for generation managed object subclasses code.

mogenerator is too old. Yes it works for swift, but has a lot of legacy code. SwiftGen is great place for substitution, it makes similar tasks.

Thanks!

**Comment by AliSoftware** [comment]
Xcode 8 already contains a feature similar to what mogenerator did so I don't feel the urge, and there's also pods like QueryKit and QueryKitCLI to manage CoreData specifically.

But if you contribute and do a Pull Request I'll definitely consider it.

**Comment by Igor-Palaguta** [comment]
mogenerator have something that is missed in XCode. XCode always generates optional strings even if field is marked as not optional. Also mogenerator has ability to customize code files with templates

Will check how other SwiftGen tools work

**Comment by Igor-Palaguta** [comment]
Created test project https://github.com/Igor-Palaguta/MotoSwift
Currently it contains just MoGen framework that parses CoreData model files and then with Stencil renders to string. Now it lives just in unit tests now.
Here is an example what it generates:
https://github.com/Igor-Palaguta/MotoSwift/blob/master/Example/Tests/Models/TypesModel_MotoSwift/GeneratedExample.swift
Next steps:
1) it is written in swift3. Are you planning to migrate SwiftGen in the nearest future?
2) do you prefer to add code to GenumKit? or we can add MoGen as dependence?
3) it uses SWXMLHash. I see you are using native XML parsers. Do you have any objection to reduce number of pods for SwiftGen?
4) I see following usage.

a) For those who prefers to separate into machine & human code
```
#generates machine code
swiftgen coredata --entityFileName "_{{entity_class}}.swift"
   --output "./Managed/Detail" --model "Model.xcdatamodeld"
   --templatePath "./Templates/machine_swift.stencil"

#generates human code
swiftgen coredata --entityFileName "{{entity_class}}.swift"
   --output "./Managed" --model "Model.xcdatamodeld"
   --templatePath "./Templates/human_swift.stencil"
```

b) For those who prefers to use extensions like XCode does
```
#generates class
swiftgen coredata --entityFileName "{{entity_class}}+CoreDataClass.swift"
   --output "./Managed" --model "Model.xcdatamodeld"
   --templatePath "./Templates/class_swift.stencil"

#generates extension with properties
swiftgen coredata --entityFileName "{{entity_class}}+CoreDataProperties.swift"
   --output "./Managed" --model "Model.xcdatamodeld"
   --templatePath  "./Templates/properties_swift.stencil"
```

c) for those who wants to collect all information about entities to one file:
```
swiftgen coredata --model ".Model.xcdatamodeld"
   --templatePath "./Templates/all_entities_in_one_file.stencil" >> ./Managed/Model.swift
```

What do you think?

**Comment by Igor-Palaguta** [comment]
@AliSoftware what do you think about adding it to swiftgen?

**Comment by Igor-Palaguta** [comment]
@AliSoftware please review https://github.com/AliSoftware/SwiftGen/pull/191

**Comment by AliSoftware** [comment]
#191 looks good! 👍

**Comment by Igor-Palaguta** [comment]
https://github.com/AliSoftware/SwiftGen/pull/195 merged with recent master, please review

**Comment by djbe** [comment]
Hi @Igor-Palaguta, with the latest SwiftGen release we've split the whole project into many sub-parts. If you'd like I can help you get started on reworking this to match the project changes.

The best place to start is with the parser, which'd go in the SwiftGenKit repository. It might be best to open an issue or PR there, so we can go over the code bit by bit and review any changes if needed.

**Comment by djbe** [comment]
In the mean time, I'm going to close your PR #195. We can create a new PR here once the features have been added to the other repositories.

**Comment by Igor-Palaguta** [comment]
Hello @grantjbutler I started do it, but unfortunately review process was too long, so I moved idea to separate tool. You can check ideas here https://github.com/Igor-Palaguta/MotoSwift

**Comment by AliSoftware** [comment]
Now that the unification of parsers and the migration to mono-repo has been done, it's indeed the right time to start implementing new parsers like one for CoreData, which should now hopefully be easier than with the previous architecture.

I'd love to see CoreData parser & support directly in SwiftGen indeed to make SwiftGen a single too to parse them all 👍

**Comment by djbe** [comment]
#455 has been merged, which implements this feature. I'd like to thank everyone who participated in this issue and the PRs leading up to this.

We'll probably do a release this weekend. In the meantime, people who'd like to try this feature can check out the develop branch,
