### ISSUE TITLE
Storyboards in App Extensions

### ISSUE THREAD

**Issue by beretis** [SwiftGen/SwiftGen#263]
If you create App Extension which has storyboards ( Notifications ), swiftgen automatically generate code for them, but those ViewControllers and Storyboards are not members of main Target. You have to add them to Target and that leads to your project being compiled twice every time. 
I would like to have tool to somehow prevent this. Is this possible?

Thank you

**Comment by djbe** [comment]
Sure, there's already a PR that fixes this:
https://github.com/SwiftGen/templates/pull/17

In the mean time, you can copy the new template and use it locally using the `--templatePath` parameter.

**Comment by AliSoftware** [comment]
SwiftGen/templates#17 has been merged and will be part of the next SwiftGen release that is due very soon!
