### ISSUE TITLE
Wrong Image.init for watchOS

### ISSUE THREAD

**Issue by BjornRuud** [SwiftGen/SwiftGen#275]
Generated file for images produced by SwiftGen do not compile with watchOS targets.

`UIImage(named:, in:, compatibleWith:)` is not supported on watchOS and should be `UIImage(named:)`

**Comment by djbe** [comment]
Is there a bundle variant for watchOS?

**Comment by BjornRuud** [comment]
There isn't a bundle variant according to the documentation. Looking at the headers that init method is exposed when the platform supports UITraitCollection, which is not supported on watchOS.
