### ISSUE TITLE
Colors: Respect lowercase in source file and Swift 3 conventions

### ISSUE THREAD

**Issue by tomaskraina** [SwiftGen/SwiftGen#277]
It seems like `swiftgen colors` does respect neither Swift 3 convention nor the case of the first letter in color name.

In my colors.txt file, I have defined all colors with names starting with a lowercase letter:
```
semiTransparentWhite    : #ffffffaa
```

However, the enum case gets generated with a uppercase letter:
```
enum ColorName {
    case SemiTransparentWhite
}
```

This not respect the Swift guidelines where switch cases should start with a lowercase letter.

**Comment by djbe** [comment]
Could you please ensure you're using the correct template?
`swiftgen colors -t swift3 ...rest of your command...`

**Comment by tomaskraina** [comment]
ah, yes. Sorry, I completely missed the section about templates in documentation. Thanks!

**Comment by AliSoftware** [comment]
Is it because that section is not at the right place should we move it up or down to make it more visible? 
Or maybe it's because it's not listed in the ToC at the top?

**Comment by djbe** [comment]
I honestly think people expect the default behaviour to be swift 3. Until we remove the the default template behaviour, it might be best to add a warning near the top that swift3 users need to specify a template.
