### ISSUE TITLE
Images command fails for asset catalogs with an empty folder

### ISSUE THREAD

**Issue by kamarshad** [SwiftGen/SwiftGen#278]
@AliSoftware 
I need your help as I am not able to generate the source code for image asset catalog for my iOS app based on swift3. When I run the command `swiftgen images App/Assets.xcassets -t swift3 --output App/Asset.swift`  always got the message `error: failed to render template invalidInputType`. I am not able to understand whats wrong with it.

I have installed the `swiftgen` through the `homebrew` and I hope it has installed the latest version. 
Moreover I have checked the app image asset but find no issue with them.
Any idea why it is happening

**Comment by AliSoftware** [comment]
Can you run `swiftgen --version` to check which version you're using?

**Comment by kamarshad** [comment]
Thanks for your reply 

`SwiftGen v0.0 (Stencil v0.8.0, StencilSwiftKit v1.0.0, SwiftGenKit v1.0.1)`

**Comment by kamarshad** [comment]
@AliSoftware  Nothing was wrong with `swiftgen`. there was a blank folder in `image asset catalog` folder which was not letting generate the source code. As I deleted it and run the command everything started working with grace.

Thanks for your effort +1

**Comment by AliSoftware** [comment]
Thanks for the feedback 
Ah I forgot that our last version had a bug in… retrieving is own version number, thus the "v0.0" 😜 (fixed since) 

Maybe we should be able to detect such a buggy use case of empty folder and provide a more explicit error message?

**Comment by djbe** [comment]
I think we're limited here with what `actool` provides. Given this issue and #228, we might want to consider eventually reverting to our own parser.

**Comment by djbe** [comment]
Although I have to ask: where was this empty folder? When I add an empty folder to an asset catalog, `actool` works just fine for me and ignores it.

**Comment by kamarshad** [comment]
@djbe it was in a root folder which was having several sub folders.

**Comment by andredsp** [comment]
I have the same issue (same command line and same error message), however there's no empty folder in my case.

After some analysis, I detected the error only occurs in the folder "App Icons", which has several icon set used for different environments.

The folder structure is:
```
App Icons/AppIcon.appiconset
App Icons/AppIcon.appiconset/app_icon@2x.png
App Icons/AppIcon.appiconset/app_icon@3x.png
App Icons/AppIcon.appiconset/Contents.json
App Icons/Contents.json
App Icons/DEVAppIcon.appiconset
App Icons/DEVAppIcon.appiconset/app_icon@2x.png
App Icons/DEVAppIcon.appiconset/app_icon@3x.png
App Icons/DEVAppIcon.appiconset/Contents.json
App Icons/PREPRODAppIcon.appiconset
App Icons/PREPRODAppIcon.appiconset/app_icon@2x.png
App Icons/PREPRODAppIcon.appiconset/app_icon@3x.png
App Icons/PREPRODAppIcon.appiconset/Contents.json
App Icons/SITAppIcon.appiconset
App Icons/SITAppIcon.appiconset/app_icon@2x.png
App Icons/SITAppIcon.appiconset/app_icon@3x.png
App Icons/SITAppIcon.appiconset/Contents.json
App Icons/UATAppIcon.appiconset
App Icons/UATAppIcon.appiconset/app_icon@2x.png
App Icons/UATAppIcon.appiconset/app_icon@3x.png
App Icons/UATAppIcon.appiconset/Contents.json
```

SwiftGen version is 4.2.0:
```
andrepinto $ swiftgen --version
SwiftGen v0.0 (Stencil v0.8.0, StencilSwiftKit v1.0.0, SwiftGenKit v1.0.1)
andrepinto $ brew list swiftgen
/usr/local/Cellar/swiftgen/4.2.0/bin/swiftgen
```

As a workaround, I created a new asset catalog only for the App Icon Sets.

**Comment by djbe** [comment]
@andredsp Could you run the following command on your asset catalog?
`xcrun actool --print-contents Assets.xcassets`

If possible, could you share a (minimal) version of the asset catalog where the error occurs? Please note, as mentioned here: https://github.com/SwiftGen/SwiftGen/issues/228#issuecomment-265718725, that some asset types break `actool` for some reason.

**Comment by vani2** [comment]
4.2.1 still don't work for me

**Comment by djbe** [comment]
Hi @vani2, could you provide the same information that I asked @andredsp in my previous comment?

**Comment by vani2** [comment]
[Here you go](https://gist.github.com/vani2/d73d8abad59598a10556df384a4e6f8c)

**Comment by djbe** [comment]
I noticed the following line at the start of your log:
```shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory```

I think there might be something wrong with your shell settings? Essentially SwiftGen executes that command and parses the output. If the output contains error messages, it won't be able to parse anything at all.

**Comment by vani2** [comment]
Looks strange, but 4.1.0 works.

**Comment by AliSoftware** [comment]
Any spaces in the full path to your assets catalog? Maybe forgot to escape them?

4.1 didn't use Apple's tool to parse the assets catalog and had other issues and uses cases we missed for other use cases — that's why we migrated to use the official Apple tool dedicated to assets catalog

**Comment by vani2** [comment]
No whitespaces 😒
`$PODS_ROOT/SwiftGen/bin/swiftgen images -t swift3 ${SRCROOT}/MyProj/Resources/Assets.xcassets --output ${SRCROOT}/MyProj/Classes/Generated/Assets/ImageAssets.swift`

**Comment by djbe** [comment]
He was asking about the expanded path. Are there any whitespaces there?

Could you please also check a previous solution mentioned above:
>  Nothing was wrong with swiftgen. there was a blank folder in image asset catalog folder which was not letting generate the source code. As I deleted it and run the command everything started working with grace.

**Comment by vani2** [comment]
The empty folder inside image asset was an issue. Thanks.

**Comment by AliSoftware** [comment]
@djbe  Even if that's a bug in the Apple tooling itself (`actool`) and not in SwiftGen, maybe we can try to catch this and provide a nice error message / suggestion when that happens, given that it's not the first time people have this issue with `actool`?

**Comment by djbe** [comment]
I'm thinking about just dropping the use of `actool` and instead write our own parser (that reads the json files in each folder). We have too many incoming issues and limitations due to the bugginess of it.

**Comment by AliSoftware** [comment]
Why not but we had that manual parsing before and had issues with it iirc (or more especially lots of use cases to handle)?

**Comment by djbe** [comment]
Nah, before `actool` this was the parser:
```swift
  public func parseDirectory(path: String) {
    if let dirEnum = NSFileManager.defaultManager().enumeratorAtPath(path) {
      while let path = dirEnum.nextObject() as? NSString {
        if path.pathExtension == "imageset" {
          let imageName = (path.lastPathComponent as NSString).stringByDeletingPathExtension
          self.addImageName(imageName)
        }
      }
    }
  }
```

Essentially we just check if we're parsing an asset catalog, then recurse through folders and load each `json` file. We still check if a folder is an `imageset` but now add the check for namespacing.

**Comment by AliSoftware** [comment]
Ah, right. So properly parsing the Contents.json files ourselves. Makes sense.

**Comment by andredsp** [comment]
I had this issue again, but now I have an "empty" folder (it actually has a Contents.json there). However, actool does not crash or return error. Take a look at this sequence:

```
$ swiftgen images -t swift3 Assets.xcassets --output ~/Images.swift
error: failed to render template invalidInputType
```
```
$ xcrun actool --print-contents Assets.xcassets
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.actool.catalog-contents</key>
	<array>
		<dict>
			<key>children</key>
			<array>
				<dict>
					<key>filename</key>
					<string>Splash</string>
				</dict>
				<dict>
					<key>children</key>
					<array>
						<dict>
							<key>children</key>
							<array>
								<dict>
									<key>filename</key>
									<string>splash_bg.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>568</real>
										<key>width</key>
										<real>320</real>
									</dict>
									<key>scale</key>
									<string>1x</string>
								</dict>
								<dict>
									<key>filename</key>
									<string>splash_bg@2x.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>1136</real>
										<key>width</key>
										<real>640</real>
									</dict>
									<key>scale</key>
									<string>2x</string>
								</dict>
								<dict>
									<key>filename</key>
									<string>splash_bg@3x.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>1704</real>
										<key>width</key>
										<real>960</real>
									</dict>
									<key>scale</key>
									<string>3x</string>
								</dict>
							</array>
							<key>filename</key>
							<string>splash_bg.imageset</string>
						</dict>
					</array>
					<key>filename</key>
					<string>Splash Screen</string>
				</dict>
			</array>
			<key>filename</key>
			<string>Assets.xcassets</string>
		</dict>
	</array>
</dict>
</plist>
```
```
$ rm -rf Assets.xcassets/Splash
```
```
$ swiftgen images -t swift3 Assets.xcassets --output ~/Images.swift
File written: /Users/andrepinto/Images.swift
```
```
$ xcrun actool --print-contents Assets.xcassets
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.actool.catalog-contents</key>
	<array>
		<dict>
			<key>children</key>
			<array>
				<dict>
					<key>children</key>
					<array>
						<dict>
							<key>children</key>
							<array>
								<dict>
									<key>filename</key>
									<string>splash_bg.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>568</real>
										<key>width</key>
										<real>320</real>
									</dict>
									<key>scale</key>
									<string>1x</string>
								</dict>
								<dict>
									<key>filename</key>
									<string>splash_bg@2x.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>1136</real>
										<key>width</key>
										<real>640</real>
									</dict>
									<key>scale</key>
									<string>2x</string>
								</dict>
								<dict>
									<key>filename</key>
									<string>splash_bg@3x.jpg</string>
									<key>idiom</key>
									<string>universal</string>
									<key>image</key>
									<dict>
										<key>height</key>
										<real>1704</real>
										<key>width</key>
										<real>960</real>
									</dict>
									<key>scale</key>
									<string>3x</string>
								</dict>
							</array>
							<key>filename</key>
							<string>splash_bg.imageset</string>
						</dict>
					</array>
					<key>filename</key>
					<string>Splash Screen</string>
				</dict>
			</array>
			<key>filename</key>
			<string>Assets.xcassets</string>
		</dict>
	</array>
</dict>
</plist>

```

**Comment by djbe** [comment]
Ah, I see what the problem is:
```
  {% if not image.items %}
  case {{image.value|swiftIdentifier|snakeToCamelCase|lowerFirstWord|escapeReservedKeywords}} = "{{image.value}}"
  {% else %}
  {% call recursiveBlock image.items %}
  {% endif %}
```

The problem is that, for your empty "Splash" folder, `image.items` is empty, and thus `false`. So Stencil tries to use `image.value`, which doesn't exist for folders (only for images). So that evaluates to `null`, and then we apply string filters to that, which receive something that isn't a `String` type, and throw the `invalidInputType` error.

For reference, here is the context generated for your asset catalog:
```swift
[
  "catalogs": [
    [
      "name": "1",
      "assets": [
        [
          "items": [],
          "name": "Splash"
        ],
        [
          "items": [
            [
              "name": "splash_bg",
              "value": "splash_bg"
            ]
          ],
          "name": "Splash Screen"
        ]
      ]
    ]
  ]
]
```

**Comment by djbe** [comment]
The check in the template should actually be:
```
  {% if image.value %}
  case {{image.value|swiftIdentifier|snakeToCamelCase|lowerFirstWord|escapeReservedKeywords}} = "{{image.value}}"
  {% else if image.items %}
  {% call recursiveBlock image.items %}
  {% endif %}
```
