### ISSUE TITLE
SwiftGen as a third party dependence for another Pod

### ISSUE THREAD

**Issue by dchohfi** [SwiftGen/SwiftGen#280]
Hey, awesome project. I've used it for some projects and it rocks, thank you.

Kick question, do you think it is possible to use SwitGen to generate stuff for a private Pod?
How to get the generated stuff on my main project?

**Comment by djbe** [comment]
Generally, most pods have an example project. In that example project you could add SwiftGen as a dependency, and the necessary generation commands as build steps for that project.

You should commit the generated files, and include these in your podspec.

**Comment by dchohfi** [comment]
Gotcha, thank you.

**Comment by djbe** [comment]
Let me know if you have any remaining issues. I'll close this for now.
