### ISSUE TITLE
Add file names generator (nibs, plists, etc)

### ISSUE THREAD

**Issue by valerianb** [SwiftGen/SwiftGen#284]
Hi,

@AliSoftware We've met at AppDevCon, I wanted to adapt #108 to the new structure and making it more generic. As discussed back then, I'm opening an issue to discuss this.
You told me you were working on writing some docs on how to contribute now the project has been split in subprojects.
The first step would be to work on the SwiftGenKit part, right ?

**Comment by djbe** [comment]
For generators, the steps are:
- First implement the generator in SwiftGenKit
- Then implement the tests in SwiftGenKit. The necessary assets (input) and contexts (output)  will be stored in the `templates` repository. Once you reach this point you'll open a related PR in the `templates` repo.
- Once your contexts are correctly generated and tested, write your new templates (stencil) in the `templates` repo.
- Once your templates are ready, write tests for them (in the templates repo). This will require the same contexts (input), but now you'll add the expected output (swift) files.
- Finally, if need be, we might add some stuff to ensure the compilation of the output files works.

**Comment by djbe** [comment]
Quick question: could you describe what features you'd like to implement?

What's the overlap with the reuseIdentifier issues/PRs? (https://github.com/SwiftGen/SwiftGenKit/pull/16, https://github.com/SwiftGen/SwiftGenKit/pull/15, https://github.com/SwiftGen/SwiftGen/pull/134) Or is it more an overlap with the codegen feature (https://github.com/SwiftGen/SwiftGen/pull/188), that could be expanded from JSON to include plist's?

**Comment by valerianb** [comment]
We use it solely to list nibs for the moment. There's no actual parsing of the nibs.
So the feature would simply be a listing of any type of files.

I will look into the issues/PRs you mentioned and get back to you !

**Comment by Robuske** [comment]
Any updates on the state of this?
I am in need of something similar but with JSON’s, I mean, the existing templates for JSON’s already give me a reference to the files, but then I would be parsing some pretty big files without the need for it

**Comment by AliSoftware** [comment]
@Robuske to my knowledge, I don't think any contributor took the time to start this yet.

Would be a good starter PR imho though, as the parser to implement for this would be pretty straightforward (nothing to parse actually, just return the file names) so the contexts to generate as output of the parser would just be something like an array of strings and the rest will follow.

We could improve further afterwards to not just return the file names but also the file type (UTI or

**Comment by Robuske** [comment]
Would be interesting to do it, but I honestly don’t know how to even start. Is the process still the same outlined by @djbe in the first comment?

**Comment by djbe** [comment]
This feature was implemented as part of 6.5.0, which was released a while ago. Use the new `files` parser for these and other needs.
