### ISSUE TITLE
Upgrade to Stencil 0.9.0

### ISSUE THREAD

**Issue by diogot** [SwiftGen/SwiftGen#290]
Would be great to have support to Stencil [0.9.0](https://github.com/kylef/Stencil/releases/tag/0.9.0). Be able to use `elif` templates would be helpful.

**Comment by djbe** [comment]
I checked the changelog and there aren't any breaking changes, so we can upgrade this without worrying.

**Comment by djbe** [comment]
Small issue though: @kylef hasn't pushed 0.9.0 to cocoapods yet.

**Comment by diogot** [comment]
Yeap, I open an [issue](https://github.com/kylef/Stencil/issues/109)

**Comment by diogot** [comment]
I can open a PR for this when Stencil 0.9.0 is available.

**Comment by djbe** [comment]
Sure, that'd be great! Best to make 2 PRs:
- one to just update the dependency to 0.9.0 (in both the podspec as the Package.swift)
- one to update the templates to use the new features.

You could get started on the 2nd one already in the templates repository, even though tests will fail for now. Either don't push your changes yet, or just ignore the failures 😆

**Comment by AliSoftware** [comment]
Stencil 0.9.0 has been pushed on CP!

**Comment by djbe** [comment]
Second item (update templates) is handled here: https://github.com/SwiftGen/templates/pull/42
