### ISSUE TITLE
Update documentation/Templates.md

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#305]
* Remove the documentation about the structure of each context, as it's now documented in SwiftGenKit. So instead, replace all those paragraphs with a link to https://github.com/SwiftGen/SwiftGenKit/tree/master/Documentation
* Update the documentation to focus on "how templates are searched" (by name, looking in App Support first, then bundle, etc) and "how to create your own custom template"
* Update the documentation with the new `swiftgen templates …` subcommands, especially to list templates it's now `swiftgen templates list` and we should mention the `swiftgen templates cat strings-swift3 >strings-custom.stencil` tip to make creating of custom templates easier

**Comment by djbe** [comment]
Actually, this document is also in the templates repo, we should remove the one located in this repo.
I've made a PR (https://github.com/SwiftGen/templates/pull/59) to update the documentation there.

Still need to make a PR to update the readme documentation here.
