### ISSUE TITLE
Rename some subcommands to better match current and future functionality

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#311]
I'd like to propose we rename 2 of the subcommands that we currently have:
- `storyboards` to `ib`: There are quite a few requests to add support for xib/nib parsing, but it'd be weird to have a separate command (once implemented) for these file types, as they essentially provide similar information. (the IB stands for interface builder)
- `images` to `assets` (or `assetcatalog`): this isn't really as important as the previous point, but the asset catalog supports many more file types than the simple `image assets` we currently support. There is a gotcha though: what if we want to support loose image files (outside of a catalog)? We have 2 options:
  - rename the subcommand for eventual support of other catalog file types, and if needed add a separate command for loose bundle files
  - keep the subcommand name as is and eventually add support for loose image files. If we ever add support for other catalog file types, we'll need to add new subcommands.

What certainly complicates things is the new `UIColor(named:)` added in iOS 11 (and other platforms).

**Comment by AliSoftware** [comment]
I'm still unclear as to if storyboards and XIB will provide the same extracted data (scenes and segues are only in storyboards, while for XIB the main request is to list XIB file names…) but would not stand against unifying it under `ib` if there's indeed common features.

I like the `assets` new name for images. I think it could still apply to loose images (images are assets even if not in an asset catalog) without being surprising 

As for colors, I think the `assets` subcommand would be in charge of parsing colors from asset catalogs while the colors subcommand could still exist for colors.xml and .clr files

**Comment by djbe** [comment]
IB:
I was thinking more about the reusable parts for example.

Colors:
We could still use the asset catalog parser part for the colors parser.

**Comment by AliSoftware** [comment]
For refs, btw: https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/Named_Color.html#//apple_ref/doc/uid/TP40015170-CH59-SW1

**Comment by djbe** [comment]
As #313 is getting close to a merge, we should think about what we're going to to with this.
- We can leave the `storyboard` command as is and always make it an alias later if needed.
- `assets` can't apply to both
  - a catalog parser for images, colors, etc...
  - a catalog parser for images + a parser for loose images
- maybe `assetcatalog` for all things in a catalog, and `files` for a future loose generic files parser (that generates code for handling certain specific types)
- or keep `images` for all things images-related (catalog, loose), and improve the `colors` parser to handle asset catalogs (it already handles multiple types).

**Comment by AliSoftware** [comment]
I was thinking:

* Keep `storyboards`
* use `assets` or `xcassets` to parse everything in asset catalogs (so images and soon colors declared there and later maybe other stuff)
* Introduce `files` (in a later release) to generate list of loose files, will be useful for listing XIB files, or list of JSON files the app might use for configuring stuff or for test stubs, …
* Use `images` for loose images (in a future release only as well to avoid postponing 5.0 too much). Those would require a dedicated command different from `files` because we'll need to handle `@2x`/`@3x` and even image series people can use in `imageView.animatedImages = …` and stuff like that 

For 5.0 we'd then have the `storyboard` command unchanged, and the `images` command renamed to `xcassets`. 
In a future version 5.x  and a future separate OR, we'll later add the new `files` and `images` subcommands

**Comment by AliSoftware** [comment]
@djbe do you agree with my proposal from the comment above?

I was thinking about doing that renaming soon (to include it once https://github.com/SwiftGen/SwiftGenKit/pull/48 + https://github.com/SwiftGen/StencilSwiftKit/pull/55 and then https://github.com/SwiftGen/SwiftGen/pull/313 are merged) but wanted to be sure we agreed on the renaming before starting it.

**Comment by djbe** [comment]
Yeah, sounds good. I'd vote for the `xcassets` name (if only because assets sounds too general)

**Comment by AliSoftware** [comment]
I think we already have issues open for all the pending features for future versions (`files` & `images` subcommands + make `xcassets` subcommand parse colors) so we should be OK to close this?

**Comment by djbe** [comment]
Sure
