### ISSUE TITLE
failed to remove localised.strings

### ISSUE THREAD

**Issue by romk1n** [SwiftGen/SwiftGen#316]
I am getting this error time to time, any advice on how to fix it?

```
failed to remove /Users/romk1n/Library/Developer/Xcode/DerivedData/r2derm-cwlxtyndrmfmhwhconnwnyfljvbe/Build/Products/Debug-iphoneos/helloapp.app/Localizable.strings: “Localizable.strings” couldn’t be removed
```

**Comment by AliSoftware** [comment]
During which build step of your build log does this error occur?

(Not sure how this relates to SwiftGen…?!)

**Comment by romk1n** [comment]
oops didn't copy and paste everything here the full log. that's basically after we generated the localizedStrings using swiftgen

```
CopyStringsFile /Users/romk1n/Library/Developer/Xcode/DerivedData/r2derm-cwlxtyndrmfmhwhconnwnyfljvbe/Build/Products/Debug-iphoneos/helloapp.app/Localizable.strings r2derm/Supporting\ Files/Localizable.strings
    cd /Users/romk1n/work/helloapp
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/roman/Library/Developer/Xcode/DerivedData/helloapp-cwlxtyndrmfmhwhconnwnyfljvbe/Build/Products/Debug-iphoneos/helloapp.app -- helloapp/Supporting\ Files/Localizable.strings
```

**Comment by Liquidsoul** [comment]
Could you check the file permissions of your Localizable.strings (in your app not in the DerivedData) using `ls -l`?
Sometimes a missing write permission on a file you copy prevents it from being overwritten the next time you build.

**Comment by romk1n** [comment]
hmm, it usually works after clean, but here the permissions 
```
-rw-r--r--+ 1 romk1n  staff  1025 30 Jun 17:12 Localizable.strings
```

**Comment by AliSoftware** [comment]
The `Localizable.strings` file isn't generated using Swiftgen. It's not altered or touched.
It's only read (and not modified) to generate the Swift code from it, but not generated or overwritten so I'm not sure how SwiftGen could have any effect on the `CopyStringsFile` phase.

Do you have the same error if you comment the SwiftGen build phase? What SwiftGen version are you using and which full command line? (Maybe you miswrote the command line and accidentally asked SwiftGen to write on the strings file instead of a swift file?)

**Comment by romk1n** [comment]
thanks for all your replies ! really appreciate it :) here the phase we have i guess we do rewrite it file, is that not how to use it?

```
echo "running SwiftGen"

"${PODS_ROOT}/SwiftGen/bin/swiftgen" images -t swift3 "$PROJECT_DIR/helloapp/Assets.xcassets" --output "$PROJECT_DIR/helloapp/Application/Generated/UIImage+Asset.swift"

"${PODS_ROOT}/SwiftGen/bin/swiftgen" strings -t swift3 "$PROJECT_DIR/helloapp/Localizable.strings" --output "$PROJECT_DIR/helloapp/Application/Generated/Localized.swift"

"${PODS_ROOT}/SwiftGen/bin/swiftgen" colors -t swift3 "$PROJECT_DIR/helloapp/colors.json" --output "$PROJECT_DIR/helloapp/Application/Generated/UIColor+helloappal.swift"

"${PODS_ROOT}/SwiftGen/bin/swiftgen" fonts -t swift3 "$PROJECT_DIR/helloapp/Fonts/" --output "$PROJECT_DIR/helloapp/Application/Generated/UIFont+helloappal.swift"

```

**Comment by AliSoftware** [comment]
The CLI you use LGTM

**Comment by romk1n** [comment]
hmm interesting, didn't see that issue before swiftgen integration.

**Comment by romk1n** [comment]
when do you recommend this phase should be executed ?

**Comment by AliSoftware** [comment]
I still don't see how SwiftGen could modify your `Localizable.strings` file from that build phase and affect the error you see in the `CopyStringsFile` build phase…

Especially since the `CopyBuildPhase` is talking about trying to _remove_ the `helloapp.app/Localizable.strings` file, so the file that is *already in the .app bundle* (probably built/copied for the previous build and it's trying to replace the old one by the new one)

**Comment by romk1n** [comment]
i see what you saying

**Comment by djbe** [comment]
Have you tried simply nuking your derivedData? (or a simple clean to begin with)

**Comment by AliSoftware** [comment]
The SwiftGen Script Build Phase should always be executed before the Compile Source phase, obviously (so that the code generated by SwiftGen is generated before the compilation starts). So that should be way before the CopyStringsFile phase happen I think?

**Comment by romk1n** [comment]
nuking folder as well as just running a clean works, but it's annoying cause you have to recompile everything :)

**Comment by djbe** [comment]
And after that clean, it keeps working, or it breaks again?

**Comment by romk1n** [comment]
@AliSoftware yup, i think there was a bad merge and hence the issue! glad we figured it out!

@djbe it's working always after clean.
