### ISSUE TITLE
Allow `swiftgen strings` to use a directory as input

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#32]
`assets strings` should be allowed to take a directory as parameter and scan for every _.strings files in it.
This would allow people using `Base.lproj` and one `_.strings`file for each`.xib`or`.storyboard` to work too

**Comment by iGranDav** [comment]
:+1: would be awesome!

**Comment by AliSoftware** [comment]
This could also use #33 to parse multiple `Localizable.strings` files passed as argument instead of a dir

**Comment by iGranDav** [comment]
Issue #39 could be related also

**Comment by AliSoftware** [comment]
Ping'd in https://github.com/SwiftGen/SwiftGen/issues/497#issuecomment-422438917 with thoughts on cases where folders have multiple `.lproj` files

**Comment by djbe** [comment]
This has been implemented by #570, released in SwiftGen 6.1.0 🎉
