### ISSUE TITLE
Make the font's path relative to how they'll be included in the final bundle

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#324]
We mainly include the `path` in the generated code so we can `register()` the font automatically if it's not registered when the user tries to use it. [See the generated code here](https://github.com/SwiftGen/templates/blob/master/Tests/Expected/Fonts/swift3-context-defaults.swift#L22-L31).

That path could also be used to create a template generating the necessary entries in the users `Info.plist` — as we generally need to declare custom fonts in there too for them to work (we should provide such a template at some point btw, that would be nice too)

But I'm wondering if it's a good thing that we currently base that registration on the relative path of the font **as found in the Xcode project / in the filesystem's hierarchy**.

Because once the app is compiled and bundled into an `.ipa`, the font is gonna generally end up at the root of the generated `.ipa` bundle. Except if the user added their Fonts folder as a "folder reference" in their Xcode project (in which case the folder hierarchy is gonna be kept identical once bundled in the `.ipa`), but if they just added their Fonts folder as a "group" (yellow folder icon in Xcode) and not a "folder reference" (blue folder icon in Xcode project) then the font will be copied at the root of the IPA bundle along with all other files in the ipa.
So the `register()` and the `Info.plist` should use _that_ final relative path in the bundle, not the one determined by how the fonts are in the repo's file system, right?

Also related to: #323

**Comment by djbe** [comment]
Hmmm, the default behaviour should probably be just the filename. 
But we should keep the relative path option for those that want it, and users wanting this will be responsible invoking swiftgen from the correct path to have the result they want.

Add a `param` option to switch between only the filename and a relative path? Something like `preservePath`? I'm wondering then, how do we then handle splitting the path up to only have the filename.

**Comment by AliSoftware** [comment]
Yeah I think only keeping the basename should indeed be the sensible default. 

We could either have `param.preservePath` or, probably easier, have `param.relativePath` be the path to prefix to the filename in the generated code, and let the user provide that path prefix  themselves.
That would let them have more control, avoids risk to leak any accidental local path as in #323  and avoid any assumption from our part.

**Comment by djbe** [comment]
Right. To be clear then, we're completely removing the "path" from the generated context, and replacing it with only the basename?

**Comment by djbe** [comment]
Just in case you still want the `info.plist` template, can't remember what goes in there (full path, filename, ...).

**Comment by AliSoftware** [comment]
Right… only problem I just thought about is if fonts are not all in the same folder but in different levels of folders… then a common prefix won't do. Damn

**Comment by djbe** [comment]
Right, but in that case they might as well write custom templates 😄

**Comment by djbe** [comment]
Or, add a filter (if it doesn't exist yet) to stencil for removing a prefix from a path, and let users provide a "path to remove" parameter.

**Comment by djbe** [comment]
Just checked, we now have a `replace` filter, so:
- default: just the basename (somehow we still need to extract that from the path, or add it to the context)
- if `preservePath` is true: use the relative path, and if `stripPath` is set, strip it from the font's path.

**Comment by AliSoftware** [comment]
That would mean that we give the full path to the template and let the template be responsible for removing the prefix, including the user's name in the full path… I'm not sure I like this, feels like a security issue of sorts…

**Comment by AliSoftware** [comment]
So maybe in the end the best is to pass the relative path to the template and have a param option in that template to either keep the relative path (for people using folder references) or reducing it to the basename (the default, for people using just groups). We might need to add a `basename` Stencil filter for that.

**Comment by djbe** [comment]
Or maybe just add the `basename` as a variable to the template, next to the current `path` variable.

**Comment by AliSoftware** [comment]
Yeah, I thought about that too. But I think a filter or Stencil function would be better in the long run, I feel like if we introduce a `basename` Stencil context variable we'll want to clean that up and remove it later to make things more consistent instead of duplicating data in the context… Would be a shame to introduce some duplication again after all that cleanup ^^

**Comment by djbe** [comment]
Right, a `basename` filter it is 😄
About the second case (preservePath), do we provide an option for stripping a certain prefix?

**Comment by AliSoftware** [comment]
Like, if not set we use the basename, if it has a truthy value we  strip the prefix equal to the folder being scanned (as we (try to) do currently), and if it has a string value that's the prefix to strip?

We could also use `env.PROJECT_DIR` as a default value somewhere…

Trivia question: if my project folder is `$PROJECT_DIR` and I have `$PROJECT_DIR/Resources/Fonts/LightTheme/MyFont.ttf` and `$PROJECT_DIR/Resources/Fonts/DarkTheme/MyOtherFont.ttf`, with `$PROJECT_DIR/Resources/Fonts` added as a folder reference to my Xcode project:

* The IPA bundle will contain `Fonts/LightTheme/MyFont.ttf` and `Fonts/DarkTheme/MyOtherFont.ttf` folder hierarchies, right?
* But if I invoke `swiftgen fonts Resources/Fonts` then relying on the folder being scanned should remove the whole `Resouces/Font` prefix from the path, but just `$PROJECT_DIR/Resources`, right?

**Comment by djbe** [comment]
I'm unsure if mixing value types in a variable is the best solution, especially when stencil has no concept of actual booleans (a non-empty string == truthy).

point 1: sounds right
poinrt 2: not sure, I should check that. What *should* it be?

**Comment by AliSoftware** [comment]
For what's worth, the `Info.plist`'s `UIAppFonts` key expects the relative path of the font in the bundle, including the font file extension, e.g. `MyFont.ttf` or `Fonts/LightTheme/MyFont.ttf` if that Fonts folder were added as a folder reference and the folder hierarchy was kept during bundling. So the same relative path as the one used for `register()`.
Which is actually probably related, as I'm guessing declaring those fonts in the `Info.plist` is a way for iOS to auto-register them at app launch.

**Comment by djbe** [comment]
Jup, thought it'd use the same paths, just wanted to be certain.

**Comment by djbe** [comment]
If we can let the path be relative to the folder being scanned, then it's up to the user to use the right path --> we remove everything before it --> they enable preserve paths if they need it.

**Comment by AliSoftware** [comment]
everything before it except the dir name, to remove `$PROJECT_DIR/Resources` not `$PROJECT_DR/Resources/Fonts`, right? (An nowhere do we need to use a `env.PROJECT_DIR` as fallback?)

**Comment by djbe** [comment]
I don't think we need that fallback, no. Removing everything but the folder name works for me, now to check if our behaviour matches that 😄

**Comment by AliSoftware** [comment]
So, just to be clear:

 - SwiftGenKit has the responsibility to take the full path of the fonts and make them relative to the parent of the folder being scanned, turning them to `Fonts/LightTheme/MyFont.ttf` and passing that relative path to the template
 - The template is responsible for choosing to use that relative path directly if `param.preservePath` is set, or otherwise (default) filter it using `|basename`

**Comment by djbe** [comment]
jup, that's it.

**Comment by bsarrazin** [comment]
@AliSoftware sorry to be chiming in a bit late on this.
I'd compare SwiftGen to Carthage/CocoaPods in some capacity. One takes the approach of just downloading the dependencies for you and not messing with you project structure. The other takes over everything.

I'd argue that SwiftGen is closer to Carthage than it is to CocoaPods. I believe that SwiftGen shouldn't be dealing with ensuring the project is properly set up and making modifications to other files, such as `Info.plist`. Unless the vocation of SwiftGen is to _manage_ fonts, it should not get involved with the registration of the fonts at all.

In regards to the path, I think the relative path should always be used. Unless you're a one man shop (and even then), you'd probably never want to commit the full path of _that_ computer into the repo.

Looks like you guys have already solved it though. Just chiming in with another opinion (or the same?).

**Comment by djbe** [comment]
@bsarrazin SwiftGen will never modify your project files, unless you tell it to.

We were discussing the option of a plist template for those users that might want to generate the necessary info.plist keys, see https://github.com/SwiftGen/templates/issues/70 for a more detailed discussion.

The full computer path in #323 is a bug and will be fixed.

We were now discussing what the swift template should generate, and what options a user should have. @AliSoftware's last comment sums up the intended behaviour.

**Comment by AliSoftware** [comment]
@bsarrazin Thanks for the feedback. Our final solution we agreed on will look like this:

* SwiftGenKit will always pass the **relative** path to the template, to be sure to never commit the full path of the current computer
* The templates will be able to either use the relative path as is, or just extract its `basename` (useful when all font files are copied flattened in the ipa bundle)

Also, SwiftGen will not be responsible for modifying the `Info.plist` (I agree with you that it shouldn't be responsible for modifying the file itself and we should not try to build a one man shop). But custom templates could be still used to:

* generate the portion of the Info.plist containing the `UIAppFonts` array, ready to just be copy/pasted by the developer in the Info.plist file manually when they want (instead of having them type the list manually and risking any typo doing so)
* or generate the commands to pass to `/usr/libexec/PlistBuddy` to replace the current `UIAppFonts` entry with the right list of fonts, effectively indeed asking `PlistBuddy` to modify the Info.plist, but then again that would be suggested to be used only on demand when the developer decides to do so, instead on every build.

Because _modifying_ an existing, non-generated file like the `Info.plist` should be done blindly, so the idea is just to let the developer auto-insert that pre-generated list of fonts on demand to avoid having to type it manually and be sure to avoid any typo.
So the developer would only do `swiftgen fonts -t UIAppFonts Resources/Fonts -o UIAppFonts.plist` once in a while manually, then open UIAppFonts.plist and copy/paste the `UIAppFonts` key from that plist into their `Info.plist`. They could of course decide to automate that import of the UIAppFonts key in their Info.plist on every build, by using tools like `PlistBuddy` in their build phase, but that would be their choice and wouldn't be SwiftGen responsibility anyway.

**Comment by bsarrazin** [comment]
That looks like a great solution!
👍

**Comment by WestFlow127** [comment]
I am having an issue with SwiftGen code getting the bundle for registering custom fonts.
When it tries to access the url, it returns nil:
`fileprivate var url: URL? {
    let bundle = BundleToken.bundle
    return bundle.url(forResource: path, withExtension: nil) // This returns nil`

Here is a bigger picture of where it's happening:
<img width="674" alt="Screen Shot 2020-07-08 at 3 57 04 PM" src="https://user-images.githubusercontent.com/13974119/86978619-287d9380-c134-11ea-9313-a4fe04d31c16.png">

And the fonts are located in the following folder:
<img width="295" alt="Screen Shot 2020-07-08 at 3 58 07 PM" src="https://user-images.githubusercontent.com/13974119/86978651-39c6a000-c134-11ea-9e40-a1ca152de68b.png">

Am I suppose to run the command in the above comment? -> `swiftgen fonts -t UIAppFonts Resources/Fonts -o UIAppFonts.plist`

**Comment by AliSoftware** [comment]
Hello

Are your fonts in that `Fonts` folder properly marked to be included in the same target as the one containing your generated code? Especially if the file generated by SwiftGen is in your `magma` target, the font files also needs to be in the same target.

You don't need to bother about the UIAppFonts / Info.plist keys: SwiftGen forces the loading of the fonts by code nowadays so that the Info.plist keys are not necessary anymore.

**Comment by djbe** [comment]
@WestFlow127 you're better off opening a new issue, where you also state which SwiftGen version you're using, what template, paths, etc... 

Like @AliSoftware said, your command doesn't seem to "exist", there is no `UIAppFonts` template, and we don't have template to generate plists (your UIAppFonts.plist output file).

**Comment by AliSoftware** [comment]
+1 on opening a separate issue; this one is a discussion from 3 years ago which might not reflect the latest behavior of SwiftGen (eg among other things, we ended not going the UIAppFonts plist file route mentioned above after all)

**Comment by WestFlow127** [comment]
Okay got it. Opening a new issue. Thanks for the responses!
