### ISSUE TITLE
Autogenerated Assets file building error: Xcode8 swiftgen 5.1

### ISSUE THREAD

**Issue by tungfam** [SwiftGen/SwiftGen#327]
Hello,

I'm using **Xcode 8.3.3** and **swiftgen 5.1**. iOS targets are 9+.

After updating swiftgen to 5.1 I'm not able to build my project due to this error in the autogenerated assets file:
<img width="933" alt="screen shot 2017-08-21 at 12 30 55 pm" src="https://user-images.githubusercontent.com/17186720/29513015-9cdac3ca-866c-11e7-9c17-398666b98b5e.png">

What is strange is that it has this `@available iOS 11.0` but I'm using Xcode 8 so I think it shouldn't know about iOS 11. Also the line of code with an error is strange:
`self.init(named: asset.name, in: bundle, compatibleWith: nil)`. Since self is UIColor but it's trying to init the Asset out of UIColor which is impossible.

I think the issue is connected to iOS 11 and usage of Xcode8.

Please let me know if you need more information.

Thank you!

**Comment by djbe** [comment]
That's annoying that xcode doesn't ignore sdks higher than it supports itself.

The line itself isn't strange, we're initialising a named colour, using the `name` of the asset. The image extension works the same way.

**Comment by AliSoftware** [comment]
Hello @tungfam 

Thanks for the bug report!

The line seems correct to me, ie. `self.init(named: asset.name, in: bundle, compatibleWith: nil)` is [this method of UIColor](https://developer.apple.com/documentation/uikit/uicolor/2877381-init) so it's not trying to init the Asset out of UIColor but trying to init the UIColor using the `asset.name`

But the error you got is not normal indeed, as this code should only be seen by `@available(iOS 11.0)` which means Xcode 8 should not know about it and ignore this code… Or maybe we're using availability annotations wrong?

**Comment by tungfam** [comment]
Oh, understood. That's a new method for iOS 11 that I didn't know :)

Availability annotations seem​ to be correct.

I created a test project and added this:
<img width="893" alt="screen shot 2017-08-21 at 2 21 18 pm" src="https://user-images.githubusercontent.com/17186720/29517101-0f99d252-867c-11e7-98f5-69b0b5522fe5.png">

That tells me that the issue is that Xcode8 just doesn't recognize the new stuff that was added with ios11. Therefore there is such an error. So even if Xcode8 doesn't support iOS11 it still tries to compile the code and fails.

I think the case of swiftgen assets file is the same.

What do you think? 

Do you think it's possible to check if user is running Xcode9 and only in that case add these 2 extensions with `@available(iOS 11.0, *)` ?

@AliSoftware @djbe

**Comment by AliSoftware** [comment]
@tungfam Yeah we did some similar tests too and arrived to the same conclusion. The only way to detect Xcode 9 and conditionally-compile is via `#if swift >3.2` it seems. See https://github.com/SwiftGen/templates/pull/76 for the fix

**Comment by tungfam** [comment]
@AliSoftware thanks a lot for the fix!
But sorry, I'm not sure if I understood. Should I wait till you release 5.2 or should I change my template somehow? Currently my template is:
`swiftgen xcassets "$PROJECT_DIR/ProjectName/Resources/Assets.xcassets" -t swift3 -o "$PROJECT_DIR/ProjectName/Library/Autogenerated/Assets.swift"`

Thanks!

**Comment by djbe** [comment]
Temporarily, until we release SwiftGen 5.1.1, you can use a custom template where you change the typealias. When we release the SwiftGen version, you can switch back to the official template.

This guide explains how to create your own templates:
https://github.com/SwiftGen/templates/blob/7c3032fc324b3e7a9b6174cec0b1bd4098f5d47e/Documentation/Creating-your-templates.md

**Comment by tungfam** [comment]
Thanks, @AliSoftware @djbe for explanations!

@AliSoftware when do you think 5.1.1 may be released?

**Comment by AliSoftware** [comment]
5.1.1 has been released on GitHub (zip in GitHub Release) and CocoaPods, and is [pending on homebrew to be release there too](https://github.com/Homebrew/homebrew-core/pull/17066)

**Comment by tungfam** [comment]
It's released to homebrew. thanks a lot for help @AliSoftware @djbe ! 💯
