### ISSUE TITLE
swiftlint error for generate uiimage asset

### ISSUE THREAD

**Issue by romk1n** [SwiftGen/SwiftGen#334]
Started to have this error:

```
UIImage+Asset.swift:46:84: error: Superfluous Disable Command Violation: SwiftLint rule 'type_name' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
```

and the line in question is 

```
// swiftlint:disable identifier_name line_length nesting type_body_length type_name
```

what should be the fix for this? swiftlint version 0.22.0

**Comment by djbe** [comment]
Ah, that's because we disable some rules because we can't predict what will be generated.

We'll need to add `superfluous_disable_command` to our disable comment.

**Comment by romk1n** [comment]
@djbe is that new error? seems like triggers a build failure ?

**Comment by AliSoftware** [comment]
Yeah it seems that it's a new rulewhich was introduced in SwiftLint 0.22. How meta of SwiftLint to long is own annotations 😁

**Comment by djbe** [comment]
@romk1n as a temporary solution (while we address this issue), you can either:
- add the generated files to your `swiftlint` excluded files.
- use a custom template to add the `superfluous_disable_command`.

**Comment by romk1n** [comment]
yes thats what I did indeed.

**Comment by AliSoftware** [comment]
Mmmmh I just tried to add the comment to disable `superfluous_disable_command` but it seems it's too meta for SwiftLint to be able to disable it inline… :-/

![SwiftLint](https://user-images.githubusercontent.com/216089/31386998-2057cc56-adc9-11e7-92bc-9c63de43f6e3.png)

**Comment by AliSoftware** [comment]
@romk1n Note that I created the PR https://github.com/SwiftGen/templates/pull/83 which we'll merge very soon so it's gonna be in the next release of SwiftGen (probably this week-end)… but you'll **also** need to update SwiftLint to 0.23.1 as they also fixed a bug related to this `superfluous_disable_command` rule recently.

Once you've update to SwiftLint 0.23.1 AND that we'll have released the next version of SwiftGen to include the fix on the bundled templates on our end, all should be good again :wink:
