### ISSUE TITLE
Output of Catalog.Entry in High Sierra

### ISSUE THREAD

**Issue by fdiaz** [SwiftGen/SwiftGen#336]
The `children()` function of Path uses under the hood
[contentsOfDirectory(atPath:)](https://developer.apple.com/documentation/foundation/filemanager/1414584-contentsofdirectory) that states:

> The order of the files in the returned array is undefined.

SwiftGen was assuming the order to be alphabetical, thus creating different outputs in Sierra and High Sierra.

**Comment by fdiaz** [comment]
Moving to SwiftGenKit.

**Comment by AliSoftware** [comment]
This is already addressed in https://github.com/SwiftGen/SwiftGenKit/pull/55 — which is waiting for someone to finish it
