### ISSUE TITLE
Not able to integrate it with Carthage 

### ISSUE THREAD

**Issue by rohitnewscorp** [SwiftGen/SwiftGen#340]
Hi, 

Earlier I was using this framework through the pod and It was working fine but As I want to do it through Carthage and It is showing me the error.

**Dependency "SwiftGen" has no shared framework schemes for any of the platforms: iOS**

Please look into this!

Thanks 
~

**Comment by djbe** [comment]
Can you add CLI tools (that aren't libraries) to your project using Carthage?

SwiftGen is a "fake" library, in the sense that nothing will be linked with your project, it's just an easy way to install the tool. Depending on if it's possible or not (question above), I'd suggest installing SwiftGen using Homebrew or downloading the ZIP file.

**Comment by ikesyo** [comment]
As a maintainer of Carthage, I'd say Carthage is not a tool for managing CLI tools but a package manager that builds `.framework`s. See also #113.
