### ISSUE TITLE
Generate backwards-compatible colors from xcassets (for iOS 10 and previous)

### ISSUE THREAD

**Issue by sgtsquiggs** [SwiftGen/SwiftGen#341]
I really like the new color asset feature in Xcode 9, but annoyed that I can't use them in previous versions of iOS. I don't want to maintain xcasset colors AND a static colors file.

I plan to implement this myself and I wanted to gauge the demand.

Ideally the colors would be available exactly as the existing xcasset colors are (via `Asset.Color.myColor.color`) - branched for iOS version < 11.

Not sure how I will handle multiple color spaces defined for a single color yet.

Thoughts?

**Comment by djbe** [comment]
We actually discussed this during the implementation of "named colors" support:
https://github.com/SwiftGen/templates/pull/68#discussion_r133326922

This would involve adding a parser for the actual contents in a (color) asset, and wouldn't work if your color is different depending on the device and/or colorspace. Also, it might tempt you to use those named colors in a XIB or Storyboard file, which wouldn't work either on older iOS versions.

**Comment by sgtsquiggs** [comment]
I agree with this line of reasoning. Closing this!
