### ISSUE TITLE
SwiftGen - "You need to choose EITHER a named template OR a template path. Found name 'swift4' and path ''

### ISSUE THREAD

**Issue by sheinix** [SwiftGen/SwiftGen#351]
I get the following error when running the SwiftGen build phase.

> You need to choose EITHER a named template OR a template path. Found name 'swift4' and path ''

My build phase script:

`$PODS_ROOT/SwiftGen/bin/swiftgen xcassets -t swift4 "$PROJECT_DIR/MyProject/Assets.xcassets" --output "$PROJECT_DIR/MyProject/Images.swift"

$PODS_ROOT/SwiftGen/bin/swiftgen strings -t structured-swift4 "$PROJECT_DIR/MyProject/en.lproj/Localizable.strings" --output "$PROJECT_DIR/MyProject/Localized.swift"

$PODS_ROOT/SwiftGen/bin/swiftgen fonts -t swift4 "$PROJECT_DIR/MyProject/Fonts" --output "$PROJECT_DIR/MyProject/MAFonts.swift"`

It isn't working for any template.

**Comment by AliSoftware** [comment]
This has JUST been fixed today, and released 4.5.1 a few minutes ago, 4.5.1 

See duplicate issue #346 : CocoaPods & GitHub release are already available, Homebrew release is pending validation by someone from Homebrew (https://github.com/SwiftGen/SwiftGen/issues/346#issuecomment-338982640)

**Comment by sheinix** [comment]
Thanks!. I've just updated the pod in my case and worked again.

Solved.

**Comment by AliSoftware** [comment]
Cool, thanks for the feedback 👍
