### ISSUE TITLE
When swiftgen is ran from pods folder it doesn't find the config file

### ISSUE THREAD

**Issue by kdawgwilk** [SwiftGen/SwiftGen#352]
I installed SwiftGen through CocoaPods and tried to run it  from the root of the project but I just get the help text.

SwiftGen version: 5.1.2

**Comment by kdawgwilk** [comment]
Even a symlink from the root of the project to the swiftgen binary in the Pods folder doesn't work

**Comment by djbe** [comment]
Just checking:
- You have a config file called `swiftgen.yml` in your project root, so `$PROJECT_DIR/swiftgen.yml`
- You have SwiftGen installed via CocoaPods, so it's in `$PODS_ROOT/SwiftGen/bin/swiftgen`
- You are invoking SwiftGen from your project root (`$PROJECT_DIR`), either from terminal or via Xcode using a build phase (`"$PODS_ROOT/SwiftGen/bin/swiftgen"`)

Is that correct?

**Comment by djbe** [comment]
Oh wait, hey, you're using an old version of SwiftGen!
Config support was added in 5.2.0.

**Comment by AliSoftware** [comment]
Be sure to run `pod repo update` from time to time so CocoaPods know about new versions, before trying `pod update SwiftGen` to get 5.2.1

**Comment by kdawgwilk** [comment]
I didn't realize that config file was such a new feature, a `pod update SwiftGen` solved it 👍

**Comment by AliSoftware** [comment]
Thanks for the feedback! (And good catch @djbe !)
