### ISSUE TITLE
'tr' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by ga-tungnguyen** [SwiftGen/SwiftGen#357]
When I add new `Run Script` into my project and build it. I get error `'tr' is inaccessible due to 'private' protection level`. I tried to search for this error but doesn't the solution. But when I tried to change from `private` to `public` is error nothing. 
```
extension L10n {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, tableName: table, bundle: Bundle(for: BundleToken.self), comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}
```
-----
- SwiftGen version: `5.2.1`
- Xcode version: `9.1`
- MacOs: `10.12.6`
- Run Script
```
if which swiftgen >/dev/null; then
    swiftgen strings "${PROJECT_DIR}/RenosyInsight/Base.lproj/Localizable.strings" --output "${PROJECT_DIR}/RenosyInsight/Constants/Strings.swift" -t structured-swift4
else
    echo "warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen"
fi
```
<img width="1061" alt="2017-11-10 10 22 29" src="https://user-images.githubusercontent.com/29847975/32639187-f71ea184-c605-11e7-843d-2d4babba321f.png">

**Comment by djbe** [comment]
Huh, I actually use the structured swift4 template in most of my projects, and it works for me without issues.

Are you trying to access the `tr` function yourself from somewhere in your code? Because you're not meant to call it yourself, you should use the generated constants, such as (for example): `myLabel.text = L10n.Asset.Case.number("A1234")`

**Comment by ga-tungnguyen** [comment]
@djbe  I did not try access the `tr` function from my code. You can see that this file auto-generated by `SwiftGen`. 

--- 

<img width="1440" alt="2017-11-10 11 06 25" src="https://user-images.githubusercontent.com/29847975/32639416-36a27064-c607-11e7-99b8-faaa1994c176.png">

**Comment by djbe** [comment]
That's weird though, that should work in swift 4, I mean, I'm using it in multiple swift 4 projects without issues.

Could you do a quick check to see what swift version you're using in your project? (3.2 or 4?)

**Comment by ga-tungnguyen** [comment]
Oh, My mistake this project is using `Swift3`. Thanks for the support. This is a great library.
