### ISSUE TITLE
performSegue sender should be Any type instead of AnyObject

### ISSUE THREAD

**Issue by yzhong52** [SwiftGen/SwiftGen#360]
Currently, the generated code for `performSegue` takes an `AnyObject` `sender`. 

```
extension UIViewController {
  func performSegue<S: StoryboardSegueType>(segue: S, sender: AnyObject? = nil) where S.RawValue == String {
    performSegue(withIdentifier: segue.rawValue, sender: sender)
  }
}
```

Looking at the interface provided by Apple: 

```
func performSegue(withIdentifier identifier: String, sender: Any?)
```

The sender type was `Any`. We should consider changing the implementation to `Any` for support for `struct`, `enum` and etc. 

```
extension UIViewController {
  func performSegue<S: StoryboardSegueType>(segue: S, sender: Any? = nil) where S.RawValue == String {
    performSegue(withIdentifier: segue.rawValue, sender: sender)
  }
}
```

**Comment by djbe** [comment]
Hi @yzhong52,

Either you're using an old version of SwiftGen, where the default template was for Swift 2, or you're using the wrong template. The current templates for Swift 3 and 4 have the correct parameter type (`Any?`).

**Comment by djbe** [comment]
Update to the latest SwiftGen version (5.2.1), and run something like:
`swiftgen storyboards -t swift3 /dir/to/search/for/storyboards`
or use a YAML configuration file and run:
`swiftgen`

**Comment by yzhong52** [comment]
@djbe thanks for the prompt response. 

I am indeed using an older version of SwiftGen. That's my bad. Sorry about that.
