### ISSUE TITLE
SwiftGenKit Carthage support

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#368]
Transfer issue https://github.com/SwiftGen/SwiftGenKit/issues/47.

This issue might easily be fixed since we added a `SwiftGenKit` framework target to the Xcode project. @ddddxxx Could you check if this is sufficient for you?

**Comment by ddddxxx** [comment]
It works, thank you!

**Comment by djbe** [comment]
Closing this for now, if anyone thinks there's a need for documentation for this, they can open a new issue.
