### ISSUE TITLE
launch screen enum generating 3 times on each build other storyboard enums working fine

### ISSUE THREAD

**Issue by SandeepSpider811** [SwiftGen/SwiftGen#372]

**Comment by AliSoftware** [comment]
Hi @SandeepSpider811 and thanks for the issue.

Could you share a small simplified project reproducing the issue? I don't see that behavior on mine so I wonder what could be different in yours.

Also could you tell which version of SwiftGen you are using, and which commands you run to reproduce it (or the content of your `swiftgen.yml` if you use one)?

Thx

**Comment by djbe** [comment]
Closed due to inactivity and missing information.
