### ISSUE TITLE
When an installation problem

### ISSUE THREAD

**Issue by SexyIoveing** [SwiftGen/SwiftGen#380]
When I use the latest brew installation, can be installed successfully, but using it will go wrong.

Error: the File swiftgen. Yml not found.

**Comment by Liquidsoul** [comment]
Hi @SexyIoveing,

Thanks for the report but we'll need some more information to help you out.

Could you give us:
- the command you ran
- the path of the folder where you ran it
- the path of your `swiftgen.yml` file

Thanks!

**Comment by SexyIoveing** [comment]
cd ~/Desktop/My xcode project/
runing: swiftgen images assets.xcassets
prompt error：File swiftgen.yml not found.

I did not find the "swiftgen.yml" file in my folder

**Comment by djbe** [comment]
Assuming you're using a recent version of SwiftGen, you'll need to use the `xcassets` subcommand and provide a template as mentioned in our documentation: https://github.com/SwiftGen/SwiftGen#asset-catalog

```bash
swiftgen xcassets -t swift3 /dir/to/search/for/imageset/assets
```

---------------------------------------

The fact that it doesn't error on an unknown subcommand (`images`) seems very weird to me. If I try it locally I get the following:
```bash
> swiftgen images Application/Resources/Assets.xcassets
Unknown command: `images`
```
Could you specify which version of SwiftGen you're using?

**Comment by SexyIoveing** [comment]
swiftgen/5.2.1

**Comment by SexyIoveing** [comment]
Thank you, my order is an older version of the order.
When I uninstall reinstalling can run the correct command.
