### ISSUE TITLE
README: document TXT color parser support for name references

### ISSUE THREAD

**Issue by andrewlord1990** [SwiftGen/SwiftGen#387]
It would be really great to be able to reference another colour within the colours file.

For example in colors.txt:

```
Red: #ff0000

Primary: Red
```

or potentially something like

```
Primary: @Red
```

Just wondering if anyone had any idea how difficult this might be to implement or if its even possible?

**Comment by djbe** [comment]
This is already possible. Let me point you to the correct docs for this:
https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/SwiftGenKit%20Contexts/Colors.md

Essentially, you can just provide the name (case sensitive I think) of another color, no `@` required.

**Comment by andrewlord1990** [comment]
@djbe Awesome, thanks very much. Sorry I read the main README and didn't find this page specific to colours within SwiftGenKit. I missed that you could reference another colour.

**Comment by djbe** [comment]
Right, that should be fixed in the Readme, thanks for the clarification.

**Comment by andrewlord1990** [comment]
Ahh okay, no problem.

Btw, thanks for such a quick reply, really helpful!
