### ISSUE TITLE
[Internal] Integrate SwiftLint via CocoaPods instead of bundle

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#393]
SwiftLint is now also distributed as a pod (similarly to SwiftGen, actually), so we could integrate it `pod 'SwiftLint', '~> 0.25'` in our `Podfile`.

This would let us stop relying on `bundler` to run it in the build phase (which doesn't really work on all people's configurations, depending on their GEM_HOME config and all) and instead just change the Build Phase to `"$PODS_ROOT/SwiftLint/swiftlint --path …"` to lint code & tests

**Comment by djbe** [comment]
Huh, never actually thought about it, but I've been using it as a pod ever since I started using it ('bout half a year ago?). Anyway, good idea yeah.
