### ISSUE TITLE
Fix small memory leak in Fonts template

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#394]
[here](https://github.com/SwiftGen/SwiftGen/blob/master/templates/fonts/swift4.stencil#L27-L28) in the templates, we create an `Unmanaged<CFError>` but never release it.

We should instead:

* Either if we really don't care about the error, don't even use an `Unmanaged<CFError>` but pass `nil` as the third parameter
* Or if we do care about the error, use `let e = errorRef.takeRetainedValue()` to gain back ownership of the `CFError` and avoid the leak, and `throw e` if not `nil` (that would mean that `register()` would now be `throws`, and we could always call `try?` to ignore the error at call site later in the template — note though that it would mean that the template would be breaking the API generated by the template if some people did call `register()` themselves

**Comment by AliSoftware** [comment]
Not sure if worth a separate issue since it's probably as fast to do both in the same PR, but we should also generate code to list all custom fonts, more importantly to register them all in one go.

I have a project currently where custom fonts are provided by a framework, so the main app consuming the framework can't really declare the custom font files in the Info.plist of the app (since the path would have to point… inside the framework's resources?) to let iOS auto-register them. So having a `FontFamily.registerAllCustomFonts()` or `FontFamily.allCustomFonts.forEach { $0.register() }` would be very useful. Might even render https://github.com/SwiftGen/templates/issues/70 obsolete.

**Comment by AliSoftware** [comment]
This is what I use in a custom template:
```
  {{accessModifier}} static let allCustomFonts: [FontConvertible] = [
    {% for family in families %}{% set fam %}{{family.name|swiftIdentifier:"pretty"|escapeReservedKeywords}}{% endset %}
      {% for font in family.fonts %}{{fam}}.{{font.style|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}}, 
      {% endfor %}
    {% endfor %}
  ]
  {{accessModifier}} static func registerAllCustomFonts() {
    allCustomFonts.forEach { $0.register() }
  }
```

**Comment by djbe** [comment]
Sounds good!
