### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by AliSoftware** [SwiftGen/SwiftGen#397]
CircleCI 1.0 is sunsetting in august. We'll have to migrate to CircleCI 2.0 before that, by updating our config file.

* Docs: [Migrating from 1.0 to 2.0](https://circleci.com/docs/2.0/migrating-from-1-2/), [Migrating iOS Projects from 1.0 to 2.0](https://circleci.com/docs/2.0/ios-migrating-from-1-2/)
* Starting point, by [using the config-translation endpoint](https://circleci.com/api/v1.1/project/github/SwiftGen/SwiftGen/config-translation)

**Comment by djbe** [comment]
If we use workflows, we might be able to parallelize jobs (they can depend on each other if needed, from a quick look at the docs).

**Comment by AliSoftware** [comment]
Lol that's already what you suggested in SwiftGen/Eve#1 👍

**Comment by djbe** [comment]
Wow, it's been a while 🤦‍♂️
