### ISSUE TITLE
Support AVPlayerViewController in Storyboard Gen

### ISSUE THREAD

**Issue by CBeloch** [SwiftGen/SwiftGen#404]
There currently is an issue with the Storyboard code generation.
When I use an AVPlayerViewController inside the storyboard of an iOS project, SwiftGen defines the type as `UIAvPlayerViewController` which is unknown.

My current workaround: 
```swift
import AVKit

typealias UIAvPlayerViewController = AVPlayerViewController
```

--- 

FYI: The default XML Code from the storyboard file looks like this:
```xml
<avPlayerViewController videoGravity="AVLayerVideoGravityResizeAspect" id="0eg-7u-MRY" sceneMemberID="viewController"/>
```
vs a default `UIViewController`
```xml
<viewController id="DsH-rV-T6N" sceneMemberID="viewController">
```

**Comment by djbe** [comment]
Huh, didn't even know that one existed. Are there any other such controllers that you know about?

**Comment by CBeloch** [comment]
From the Interface Builder on iOS only the "GLKit View Controller" `GLKViewController` which results in a `UIGlkViewController` in the generated code.

```xml
<glkViewController storyboardIdentifier="glkit" preferredFramesPerSecond="30" id="y1T-5D-969" sceneMemberID="viewController">
```

I think they are very uncommon to use inside of storyboards and the API is so easy you could initialize them with just a few lines of code. Just noticed this bug yesterday with the `AVPlayerViewController`

**Comment by djbe** [comment]
Good to know though, thanks for checking!

I'll see about making a PR for this, unless you feel up for it? 😄
