### ISSUE TITLE
Shell Script Invocation Error , XCode 9.2, Cocoapods

### ISSUE THREAD

**Issue by chetandobariya** [SwiftGen/SwiftGen#406]
I am using pod 'SwiftGen', '~> 4.0'  in my project. everything looks fine and working perfectly.

But during the archiving project, I am facing `Shell Script Invocation Error` during run "swiftgen" script.
the error message is 

> Command /bin/sh failed with exit code 1

my shell script for the swiftgen is 
`"$PODS_ROOT"/SwiftGen/bin/swiftgen`

Need help to figure out the issue. I am using Xcode 9.2

**Comment by djbe** [comment]
- Which SwiftGen version are you using?
- What does your configuration look like?
- Are you using custom templates?
- What happens if you run SwiftGen straight from Terminal?

**Comment by chetandobariya** [comment]
It is solved now. It was problem with swiftgen v4.0. As it is not supporting swift4 and swiftgen.yml file compilation

I update it with v5.3.0 and it fixed.
