### ISSUE TITLE
Asset catalog name collisions

### ISSUE THREAD

**Issue by rudedogg** [SwiftGen/SwiftGen#408]
I've organized my asset catalog using folders, which SwiftGen nicely uses as enums/namespaces. But, I've noticed it loads the incorrect asset if I use the same name for multiple assets.

For example, I have two `"add"` image assets. This works well because they are in different folders in the asset catalog:
`View1/Icons/add`
`View2/Icons/add`

Usage with SwiftGen is something like:
`Asset.View2.Icons.add`, but since the filenames conflict (`"add"`) this actually will return the Asset for `View1`.

I looked around the code a little and noticed this is because the `ImageAsset` is a wrapper around the `UIImage(named: )`/`NSImage(named: )` initializers, which only takes the name (and doesn't care about Folders in the asset catalog).

Working around it is pretty easy (just use longer/unique names), but then organizing assets into folders is kind of pointless. Is there a different workaround?

**Comment by djbe** [comment]
Weird that Xcode doesn't give you an error (or warning) for this.

Anyway, this is where the concept of "provides namespace" comes in. Each of those folders in your catalog have a small checkbox with this property, that'll ensure that the name of your images will actually be "Views1/Icons/add" and "Views2/Icons/add", avoiding any naming collisions.

**Comment by rudedogg** [comment]
@djbe Thanks! I didn't know about that setting! 🎉 

I've been using AppCode a bit so that's how I missed the warning, when I loaded the project in Xcode I saw it.
