### ISSUE TITLE
SwiftLint Violation: Conditional Returns on Newline

### ISSUE THREAD

**Issue by iotize** [SwiftGen/SwiftGen#436]
When using SwiftGen to generate fonts using the Swift 4 template in combination with SwiftLint with the rule `conditional_returns_on_newline` enabled, SwiftLint raises a warning:

```
warning: Conditional Returns on Newline Violation: Conditional statements should always return on the next line (conditional_returns_on_newline)
```

This is caused by [this line](https://github.com/SwiftGen/SwiftGen/blob/3d6788dfd8f7699676f1c4aa6f9a2894531a75dc/templates/fonts/swift4.stencil#L26) in the Fonts template.

This can be fixed either by adding a newline:

```swift
{{accessModifier}} func register() {
  guard let url = url else {
    return
  }
  CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
}
```

Or by adding this rule to the list of ignored rules at the top of the file:

```swift
// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length
// swiftlint:disable conditional_returns_on_newline
```

Or, as discussed elsewhere, by excluding generated files from SwiftLint, but assuming that's not the case...

I'm happy to submit a pull request to fix this but I'm not sure which approach is preferable?

**Comment by djbe** [comment]
Hmmm, I wonder why that didn't get flagged in #402.

I think a disable would be preferable here, as I'm pretty sure we use the same style in the codebase for SwiftGen itself as well. @AliSoftware what do you think?

If we go the "disable that rule in the template" route, please note how we handle this in the other templates. All such rules are disabled only for that bit of the template, and re-enabled again as soon as possible in the same file. And we should cover the warning from #427 while we're at it.

**Comment by AliSoftware** [comment]
Tbh for this one I wouldn't be shocked to add the extra missing newline and fix the violation instead of ignoring it

**Comment by djbe** [comment]
I think there're more violations in the codebase itself (not sure though)

**Comment by iotize** [comment]
If it would be consistent with the rest of the codebase, perhaps disabling the rule is the best way to avoid a regression later on?
