### ISSUE TITLE
Generate Segue per Scene (not per Storyboard)

### ISSUE THREAD

**Issue by oderkach** [SwiftGen/SwiftGen#449]
I checked the repository to find some information about how to generate segues per `ViewController`.
But I didn't find anything about this. I checked SwiftGen sources and looks like it's not possible to match `Scene` and `Segue` because all Segues defined in `Storyboard.swift` file.

Example:
I have ViewController with 2 segues (one, two).

```swift
internal enum TestStoryboard: String, SegueType {
    case one = "one"
    case two = "two"
    case three = "three"
  }

//ViewController
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let segueEnum = StoryboardSegue.TestStoryboard(rawValue: segue.identifier ?? "") {
        switch segueEnum {
        case .one:
            // handle 
        case .two:
            //handle
        default:
            // handle others...
        }
    }
}
```

In case if I will add new segue `NewSegue` from `ViewController`, it will be handled as `default`case. As for me it's not a good because I want to handle all possible segues for my `ViewController`.

So is it possible to generate segues per `ViewController`?
`StoryboardSegue.TestStoryboard.ViewController(rawValue: segue.identifier ?? "")` or somehow else?

**Comment by AliSoftware** [comment]
Hey @oderkach 

Maybe @djbe 's Pull Request https://github.com/SwiftGen/SwiftGen/pull/364 will answer your needs once it's merged?

**Comment by djbe** [comment]
Yes this feature is possible, and it's implemented in #364. If you have any comments/requests, please post them there.

Closing this as a duplicate.

**Comment by djbe** [comment]
Ah, sniped 😄

**Comment by oderkach** [comment]
Thanks for the answers.
When do you plan release SwiftGen 6.0?)
