### ISSUE TITLE
Want to make camelcase enum name but uppercase for just the first one

### ISSUE THREAD

**Issue by ChocOZerO** [SwiftGen/SwiftGen#465]
I generated a enum structure via SwiftGen. There are something different from example on https://github.com/SwiftGen/templates/blob/master/Tests/Expected/Strings/structured-swift4-context-localizable.swift
I want to get a camelcase enum name but I got a lowercase but upper for just first one. Is there a option for that?

**Comment by ChocOZerO** [comment]
I ask this problem to "@aligatr" on twitter. And I got answer.

Yes there is. Either check if there isn't an existing template fitting your needs, or if the templates doesn't provide parameters allowing you to customize that… and if none of the provided stuff fit your needs, you can just duplicate an existing template to fully customize it.

Also, please use GitHub issues for that. I'm not the sole contributor to SwiftGen, and many other people would be able both to answer your specific questions and others could also benefit from those questions' answer eventually.

**Comment by AliSoftware** [comment]
Please provide information about:

 - The version of SwiftGen you're using
 - The template you're using, and any parameter you passed to it
 - The command line invocation you're using

Also the link you provided points to an old and archived repo used for previous versions of SwiftGen. We've migrated the templates and their documentation in the main repos since then.

**Comment by ChocOZerO** [comment]
I decide to change keys on my strings file like "LandingPages" to "landing-pages".

finally, I got right name that I want.

It was..

The version of SwiftGen you're using : SwiftGen v5.3.0 (Stencil v0.10.1, StencilSwiftKit v2.4.0, SwiftGenKit v2.2.0)
The template you're using, and any parameter you passed to it : just for strings
The command line invocation you're using : swiftgen strings {custom}/Localizable.strings -t structured-swift4 --param enumName={custom}

**Comment by djbe** [comment]
Closing this in favour of #483.
