### ISSUE TITLE
Stencil 11.0

### ISSUE THREAD

**Issue by ethanjdiamond** [SwiftGen/SwiftGen#473]
Hi! I noticed that your podfile.lock seems to use Stencil 11.0, but SwiftGen's most recent release is still at Stencil 10.1. I'm working on a project using SwiftGen that i'd like to send in an array via a --param flag, but am unable to since it only takes strings. A solution that would work is to comma separate and then use the `split` filter Stencil introduced in 11.0. Do you have an idea when SwiftGen will be updated to allow Stencil 11.0?

**Comment by djbe** [comment]
Late but short answer: soon (we hope).

Longer answer: we're directly jumping to Stencil 0.12, which is needed to finish up some PRs pending for SwiftGen 6.0.
