### ISSUE TITLE
XCAssets: Make the generation of `allXXX` arrays only opt-in via a `param`

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#478]
When you have a *lot* of images, colors and data assets, those lists are super-long, and useless 90% of the time.

Sure we could say that we don't really care since it's auto-generated code anyway so it's not a big deal to have too much rather than too little… but I still open the generated files quite often to have a glance at the list of objects generated quickly (especially when autocomplete is in a bad mood, opening the generated file allows you to see the list of StoryboardScene, Assets, etc… available), and those `allXXX` lists quite pollute that super-long generated file in the end.

Proposal, invert the behaviour of the current `noAllValues` parameter: replace it by an `allValues` parameter, that by default is false.

**Comment by AliSoftware** [comment]
+1 for this, even if that would be breaking.

That said, I don't care having to wait after 6.0 and having to bump to 7.0 for that, if otherwise implement that would postpone the next major version pending
