### ISSUE TITLE
Organise the order of the generated output

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#479]
Make sure that the static content (declaration of our internal `struct` etc) and the content which really depends on the files being parsed (list of storyboard scenes, assets, etc…) are clearly isolated from one another, via a `// MARK -` or something, and always at the very end of the generated file, to make it easy to access without being polluted by the helper types and implementation details declared in the rest of the files.

So:
- Add `// MARK: - ` comments for the static and dynamic parts
- Move the dynamic part to the top of the file.

**Comment by AliSoftware** [comment]
I'd say move the dynamic content to the **bottom** of the file (as it's almost already the case already, for most of the content, just not all yet, hence this issue). But 🍅/🍅

**Comment by djbe** [comment]
Ah, I must've misunderstood the convo then. What do you check more often, the list of parsed items, or the available variables/methods?

**Comment by AliSoftware** [comment]
I indeed more often want to read the list of items, so moving them at the top would be nice.

I'm just saying since they're already mostly at the top for 95% of the templates except for some rare portions that would be less changes to do to keep them at the bottom and just regularize it. But if we go thru the whole reordering then yeah why not invert it indeed and put dynamic content at the top 👍

**Comment by djbe** [comment]
@AliSoftware any preference for the section names? Or simply `Static/Dynamic Code`?

**Comment by AliSoftware** [comment]
Haven't thought about the names but I don't like "static" vs "dynamic". Too confusing with other concepts like static funcs or like dynamic dispatch etc

Maybe `// MARK: - {{enumName}}` and `// MARK: - Implementation Details` ?
Or `Generated Constants` or _the name of the resources type_ (`// MARK: - XCAssets`, `Strings`, etc) for the first one? And `Implementation` for the 2nd?
