### ISSUE TITLE
Tests: Compile output with a specific deployment target

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#487]
The NSDataAsset asset type PR (#445) added code that depends on a type that's only available from certain iOS/tvOS versions. It did have an `@available` check, but it was in the wrong place (it needed to be on the extension of the new type instead of the method, fixed in #482).

The reason our tests didn't catch this is because, while we do provide an SDK (the latest public available, see [here](https://github.com/SwiftGen/SwiftGen/blob/master/Rakefile#L63)), we do not provide a deployment target.

The main question then is, what deployment target do we chose for our templates? (per platform)
And we should document these choices in our template docs.

Note: this should not affect the `swiftgen` podspec, as the user can always choose to use their own templates for older platform versions.

**Comment by AliSoftware** [comment]
Other question is, which deployment target do we test our targets with? Which is somewhat related to the deployment target we chose for our templates, but what I means is that we'll likely provide a *range* of SDKs + deployment targets supported (like "template tested for iOS 9+" or "template tested on macOS 10.10 thru 10.12"), but do we then run our CI to test only the minimum target supported (iOS9, macOS 10.10), or also to test with the latest target (iOS 12b as of now, and will evolve later), to be informed when it breaks in a future version ?

That would mean a lot of builds (each target being built on multiple SDKs and for each SDK on at least 2 deployment targets, the min and the max) though…

Or maybe just using the *latest* BaseSDK of the platform and just providing a DEPLOYMENT_TARGET setting for the *min version* supported ensures us that it covers everything, and we'd then be good with just 3 builds per template (one per platform iOS, macOS, watchOS)?

**Comment by djbe** [comment]
Implemented in #789.
