### ISSUE TITLE
Some constant are not working - can't be found even though they are generated

### ISSUE THREAD

**Issue by nyeu** [SwiftGen/SwiftGen#491]
Hi!
I have a very weird bug, I will try to explain as good as I can:

- [x] Using `SwiftGen (5.3.0)`
- [x]  Xcode version 9.4
- [x]  Swift 4

- I have a long list of strings and I run `swiftgen strings -t structured-swift4 {Project name}/Base.lproj/Localizable.strings`
- All strings are generated into constants and almost all of them work fine. There's 8 that can't be used anywhere in the app even though they are in the generated file.
- The generated file is in alphabetical order, but this 8 constants are at the end of the file.
- If I look at the `Base.lproj/Localizable.strings`, the keys and the strings are correctly formatted and look no different than any other.
- It doesn't matter if I run it through Xcode in `Build phases` or through `Terminal`.

This is how the end of the generated file looks like, where `userProfileTitleLastPicture` is the last working constant and all the next ones are the ones who don't.

```
 /// Your last picture sent
  internal static let userProfileTitleLastPicture = L10n.tr("Localizable", "user_profile_title_last_picture")
  /// Bump up your picture
  internal static let ﻿dashboardOnlineButton = L10n.tr("Localizable", "﻿dashboard_online_button")
  /// chat requests
  internal static let ﻿dashboardOnlineTextChatRequests = L10n.tr("Localizable", "﻿dashboard_online_text_chat_requests")
  /// men browsing in your region
  internal static let ﻿dashboardOnlineTextMenInRegion = L10n.tr("Localizable", "﻿dashboard_online_text_men_in_region")
  /// in your region
  internal static let ﻿dashboardOnlineTextRegion = L10n.tr("Localizable", "﻿dashboard_online_text_region")
  /// viewed your picture
  internal static let ﻿dashboardOnlineTextViewed = L10n.tr("Localizable", "﻿dashboard_online_text_viewed")
  /// women browsing in your region
  internal static let ﻿dashboardOnlineTextWomenInRegion = L10n.tr("Localizable", "﻿dashboard_online_text_women_in_region")
  /// Share your location
  internal static let ﻿﻿﻿signupLocationButton = L10n.tr("Localizable", "﻿﻿﻿signup_location_button")
  /// We need you to share your location
  internal static let ﻿﻿﻿signupLocationTitle = L10n.tr("Localizable", "﻿﻿﻿signup_location_title")
```

Any idea what can be wrong? 

Thanks

**Comment by djbe** [comment]
Wait, I can confirm the issue, just tried it in a playground. Weird...

**Comment by djbe** [comment]
There's an invisible character before the dashboardOnlineButton (after the space, before the `d`), same thing for the key (`dashboard_online_button`). The same applies for the other, non-working keys.

This often happens when whoever edited the strings files, copied in content from something like MS Word. Never ever ever ever let people edit strings (or xliffs) inside Word or something similar.

**Comment by djbe** [comment]
The issue is probably that this is valid swift code, but the xcode autocomplete doesn't also autocomplete the hidden character or something. 🤷‍♂️ 

I recommend actually fixing the issue in your strings files, because it'll lead to more problems down the road.

**Comment by nyeu** [comment]
Weird, we do all our strings with Lokalise. I also checked if there was an space before the key, as it happened before.

**Comment by djbe** [comment]
It's not a space, it's an invisible, non-space character. You can check by tapping the left/right arrows to move your cursor in a text editor. It'll "pause" at the start where those characters are.

**Comment by nyeu** [comment]
oh, I see it! wow, amazing! Nice catch :) thank you so much, it drove me crazy for a week

**Comment by djbe** [comment]
Glad I could help 😄
