### ISSUE TITLE
Json parser: `null` support

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#492]
I was trying a `master` build for some of the json files in one of our apps, and encountered an issue with `null` support.

Given this JSON file:
```json
{
  "name": "Ambassify",
  "community_id": null
}
```
That sometimes can become this JSON file:
```json
{
  "name": "Ambassify",
  "community_id": null
}
```

Just to explain the use case, `community_id` is an `Int` that can be `nil`, so it should be an `Int?`.

------

SwiftGen then produces (from the file with `null`):
```swift
// inline
internal enum JSONFiles {
  internal static let name: String = "Ambassify"
  internal static let communityId: Any = <null>
}

// runtime
internal enum JSONFiles {
  private static let _document = JSONDocument(path: "config.js")

  internal static let name: String = _document["name"]
  internal static let communityId: Any = _document["community_id"]
}
```

There's obviously an error in the inline version, that should be `nil` instead of `<null>`.

The runtime version is a bit more complex. Our current templates are only meant to parse the "current" file, pointing to a specific file in the bundle. I don't think we should change that, if the user wants more complex functionality, it's up to them to write a custom template. What we maybe should do, is add some notes to the templates documentation:
> - Loads the data from the JSON file at runtime

Should maybe become
>  - Loads the data from the JSON file in your app bundle at runtime.
>  - If you need other functionality, such as loading a file in your `Documents` folder, or handling `optional` properties, you should write your own template (... link to docs...)

**Comment by AliSoftware** [comment]
Is it really loading the JSON file from the app bundle? Shouldn't it be loading the file from the current bundle (ie the bundle/target/framework the generated file has been added to), like templates for other resources do (`private static let bundleToken…`)

Aside from that I agree that we should let users make their own templates if they want to load JSON files from bundles or folders from a different target than the generated file is in, like the Documents folder. We could still include a `param` in a future version of the templates in a later release of the demand is high for such special cases.
