### ISSUE TITLE
Is there a way to specify the targets to generate code for?

### ISSUE THREAD

**Issue by felixsolorzano** [SwiftGen/SwiftGen#500]
If I only want to generate the code for iOS, is there a way I could specify that my target is iOS?

**Comment by AliSoftware** [comment]
Hi @felixsolorzano 

SwiftGen operates at a filesystem level. So it scans the *folders* you asks it to scan (what you configure in your `swiftgen.yml` config file).

It has no knowledge of your Xcode project, so can't really know which files on disk are part of which Xcode target in your project.

The best option for you to generate only the code for your iOS target is to put all the files specific to that target in a dedicated subfolder (which is what Xcode generally does by default anyway), and tell swiftgen to parse only this subfolder.
