### ISSUE TITLE
When swiftgen.yml parsing fails, output error messages that Xcode parses

### ISSUE THREAD

**Issue by skagedal** [SwiftGen/SwiftGen#516]
1. Integrate SwiftGen with Xcode as a Script Build Phase.
2. Have an invalid swiftgen.yml, for example by making it just contain the word `failure`. 
3. Build your project. 

Expected behavior: the build fails.
Observed behavior: none – you have to open the build output to see the failure. 

In this case it prints:
```
Wrong type for key root: expected Dictionary, got Optional<Any>.
```

It would be nice if it instead printed:
```
/path/to/swiftgen.yml:1:error:Wrong type for key root: expected Dictionary, got Optional<Any>.
```

(In this case an even better error message like "Invalid YAML" would have been better of course, but that is not the point of this issue.)

It could be done so it only uses this format if run within Xcode, or if a certain flag is passed. (I could not find such an existing flag.)

**Comment by skagedal** [comment]
I see that such error messages are generated in such contexts, but not all.

**Comment by djbe** [comment]
Regarding the phase not erroring, please read our docs:
https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Articles/Xcode-Integration.md
We mention how it's better to use `/bin/sh -e` exactly for that reason.

**Comment by AliSoftware** [comment]
Yeah swiftgen Stiller exits with error code so of you use `-e` your build would error if SwiftGen errored.

Would still be good to unify our error logging style to print `error: ` though, to show the error as a red mark in the IDE with more context

**Comment by skagedal** [comment]
Ah sorry, totally my bad on that part; I was not forwarding the exit code correctly. But yeah, it would still be a nice improvement if the error logging got marked up with `error:`.

**Comment by djbe** [comment]
SwiftGen 6.0.1 is out 🎉
