### ISSUE TITLE
404 to colors.txt

### ISSUE THREAD

**Issue by skagedal** [SwiftGen/SwiftGen#522]
From README.md, section about Colors, there is a link to [colors.txt](https://github.com/SwiftGen/SwiftGen/blob/master/Tests/Fixtures/Resources/Colors/colors.txt) which doesn't exist at that URL. Could not figure out what this should be pointing to.

**Comment by skagedal** [comment]
I just submitted a PR for another 404, but i see I messed up the base branch

**Comment by AliSoftware** [comment]
no problem, Danger should now tell you about it :wink:
