### ISSUE TITLE
ib segues-swift4 template output produces error when targeting macOS 10.14

### ISSUE THREAD

**Issue by nhojb** [SwiftGen/SwiftGen#535]
Due to API churn in the macOS 10.14 SDK, NSStoryboardSegue.Identifier is no longer RawRepresentable and is now typealiased as a String.

This causes the code generated by the ib segues-swift4 template to fail to build with the following error:

```
StoryboardSegues.swift:47:44: error: value of type 'NSStoryboardSegue.Identifier' (aka 'String') has no member 'rawValue'; did you mean 'hashValue'?
    guard let identifier = segue.identifier?.rawValue else { return nil }
                           ~~~~~~~~~~~~~~~~^ ~~~~~~~~
                                             hashValue
Swift.String:3:16: note: 'hashValue' declared here
    public var hashValue: Int { get }
```

SwiftGen v6.0.0 (Stencil v0.13.1, StencilSwiftKit v2.7.0, SwiftGenKit v6.0.0)
Xcode 10.0
Target: macOS 10.14 SDK

**Comment by AliSoftware** [comment]
Hi @nhojb 

Thanks a lot for reporting this issue!

It happens that this has already been reported in #515 and fixed in #519 :wink:

We plan to do a 6.0.1 release probably tonight to include that fix 👍

**Comment by djbe** [comment]
@nhojb do note that your issue is actually unrelated to the macOS version, but has to do with the Swift version you're using (4.2 vs 4.0)

**Comment by nhojb** [comment]
Thanks.

The penny did finally drop after I submitted this issue. The tight coupling between the Swift _language_ version and the Cocoa API does cause some confusion - for me at least :-) For example the current AppKit API documentation describes the latest API without any reference to the Swift language version:

https://developer.apple.com/documentation/appkit/nsstoryboardsegue/identifier

**Comment by AliSoftware** [comment]
Yeah, that's indeed confusing. Also lead us wondering, when we implemented the fix, if the solution was to write the test on the SDK version or on the `#if swift(>=4.2)` condition… ended up doing the latter, but had a hard time finding the confirmation that it was indeed what introduced the change!
