### ISSUE TITLE
[Proposal] Sequential images support

### ISSUE THREAD

**Issue by noppefoxwolf** [SwiftGen/SwiftGen#539]
This is a proposal to the default template.
If the image below the namespace is a sequential image, It can be called with plural name method.

- xcassets
```
Common
  LoadingImage
    - 000.png
    - 001.png
    - 002.png
    - 003.png
....
```

- code (before)

```swift
let images = [Asset.Common.LoadingImage._001.image, Asset.Common.LoadingImage._002.image ...]
```

- code (after)

```swift
let images = Asset.Common.loadingImages
```

**Comment by noppefoxwolf** [comment]
Uhh. I feel better this way.

```
let images = Asset.Common.LocadingImage.images
```

Someone please give me your opinion.

**Comment by AliSoftware** [comment]
Hey!

This is definitely a good idea :+1: and as it happens we have an issue open for a while about that idea, as we wanted to add it for a while (just never had the time to tackle it)

See #137 for further ideas and discussion about the topic
