### ISSUE TITLE
Colors: `publicAccess` parameter does not make internal code public

### ISSUE THREAD

**Issue by hisaac** [SwiftGen/SwiftGen#548]
I'm working with SwiftGen's "color" generation. I noticed when using the `literals-swift4` template, and passing `publicAccess: true` in the parameters, it only made the main enum public, not the values inside it. Is this expected behavior? It was unexpected to me, but I understand there may be a good reason for it that I don't know about.

Here's what the generated code looks like:

```swift
public extension ColorName {
  enum HIGColors {
    /// 0x007affff (r: 0, g: 122, b: 255, a: 255)
    static let blue = #colorLiteral(red: 0.0, green: 0.47843137, blue: 1.0, alpha: 1.0)
    /// 0x4cd964ff (r: 76, g: 217, b: 100, a: 255)
    static let green = #colorLiteral(red: 0.29803923, green: 0.8509804, blue: 0.39215687, alpha: 1.0)
  }
  enum Q3Colors {
    /// 0x5b73aaff (r: 91, g: 115, b: 170, a: 255)
    static let blue = #colorLiteral(red: 0.35686275, green: 0.4509804, blue: 0.6666667, alpha: 1.0)
    /// 0xaa925bff (r: 170, g: 146, b: 91, a: 255)
    static let gold = #colorLiteral(red: 0.6666667, green: 0.57254905, blue: 0.35686275, alpha: 1.0)
  }
}
```

In my case, I'm generating this inside of a library, and then using the library within an app. My issue is, I'm not able to access the colors within the `HIGColors` and `Q3Colors` enums.

The code below gives me an error that says, `'blue' is inaccessible due to 'internal' protection level`

```swift
let blueColor = ColorName.HIGColors.blue
```

This can be fixed by adding `public` to the internal `enum` values, and their properties, like so:

```swift
public extension ColorName {
  public enum HIGColors {
    /// 0x007affff (r: 0, g: 122, b: 255, a: 255)
    public static let blue = #colorLiteral(red: 0.0, green: 0.47843137, blue: 1.0, alpha: 1.0)
    /// 0x4cd964ff (r: 76, g: 217, b: 100, a: 255)
    public static let green = #colorLiteral(red: 0.29803923, green: 0.8509804, blue: 0.39215687, alpha: 1.0)
// ...
```

## Environment
- SwiftGen Version: SwiftGen v6.0.2 (Stencil v0.13.1, StencilSwiftKit v2.7.1, SwiftGenKit v6.0.2)
- Xcode Version: 10.0

**Comment by hisaac** [comment]
I don't know the codebase well enough to know this for sure, but it seems like changing this would just require adding `{{accessModifier}}` to the beginning of [line 26](https://github.com/SwiftGen/SwiftGen/blob/master/templates/colors/literals-swift4.stencil#L26) and [line 31](https://github.com/SwiftGen/SwiftGen/blob/master/templates/colors/literals-swift4.stencil#L31) in the [literals-swift4.stencil](https://github.com/SwiftGen/SwiftGen/blob/master/templates/colors/literals-swift4.stencil) file.

If it really is that simple, and the maintainers agree that the change makes sense, I'd be happy to make the change and open up a pull request for you.

Also if the change makes sense, should a similar change be made to the other built-in templates?

**Comment by djbe** [comment]
Jep, it's a bug that boils down to some missing `{{accessModifier}}`. A PR would definitely be welcome 👍

**Comment by hisaac** [comment]
Alrighty, I'll get to work on it!

**Comment by djbe** [comment]
The non-literal templates seem to be OK. They even have too many things as `public`, these can be removed while we're at it:
https://github.com/SwiftGen/SwiftGen/blob/master/templates/colors/swift4.stencil#L49
https://github.com/SwiftGen/SwiftGen/blob/master/templates/colors/swift4.stencil#L61

**Comment by thedevme** [comment]
So I am not seeing how I can make the file public instead of internal - Is there a way I can set it - changing them all by hand would defeat the purpose?

**Comment by AliSoftware** [comment]
@thedevme This should be fixed in SwiftGen 6.1.0 — which is currently being released (available on CocoaPods already, pending approval in Homebrew), so once you update, you'll be able to use the `publicAccess: true` param in your config file to enable it as it was always intended (see the documentation for the template [here](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/colors/literals-swift4.md#customization) and [the config file here](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/ConfigFile.md) if you didn't read it yet).

**Comment by djbe** [comment]
6.1.0 is already available from CocoaPods & the zip here on GitHub. A brew release should be available soon.

**Comment by thedevme** [comment]
Thats why I didnt see it bc I am using brew.  When you say in your config file do you mean yaml? If so, where is there an example of this I couldnt find it anywhere.

**Comment by thedevme** [comment]
By the way, thank you for responding so quickly

**Comment by AliSoftware** [comment]
@thedevme I've put the links to the documentation & examples in my comment above :wink: (I edited it a few seconds after posting it to add them, so maybe you didn't see those links there)

**Comment by thedevme** [comment]
lol sorry @AliSoftware missed that - thank you
