### ISSUE TITLE
Xcode 10.1 beta 2 Error (Missing entry for key xcassets.paths.)

### ISSUE THREAD

**Issue by YiYiZheng** [SwiftGen/SwiftGen#552]
1 installed SwiftGen via cocoapods. 
2 add run script "${PODS_ROOT}/SwiftGen/bin/swiftgen"
3 add swiftgen.yml to project root dir. 
4 build project

compile error: 
Missing entry for key xcassets.paths.
Command PhaseScriptExecution failed with a nonzero exit code

What could I do? Thanks

**Comment by AliSoftware** [comment]
Hi

The message is telling you that you have an error in your `swiftgen.yml` configuration file.

_You can use `swiftgen config lint` in your terminal to try to have more information about the syntax error that you have in that config file of yours._

But according to the error SwiftGen already reports to you, you're missing the key `paths` under the `xcassets` key of your config file.
What's odd though is that this `paths` key is deprecated and was renamed in the latest versions of SwiftGen; so what probably happened is that you installed an old version of SwiftGen (5.x) but you followed the documentation of the new SwiftGen (6.0) — which correctly documents the config file structure to expect `inputs` for the key listing the path to scan (while this key was named `paths` in 5.x)

Could you just check that you installed the latest version of SwiftGen and not an old 5.x version? My best guess is that you probably forgot to run `pod repo update` to update CocoaPods' repo of podspecs before installing your pods (including SwiftGen) with `pod install`

**Comment by AliSoftware** [comment]
Sorry I meant `Pods/SwiftGen/bin/swiftgen config lint` not just `swiftgen config lint` (since you installed SwiftGen using CocoaPods so that's where it got installed in your project). Run that command in the terminal after having moved (using `cd`) to the directory where your project is, obviously 😉

Did you check the version of SwiftGen you did installed btw? You can check it either by running `Pods/SwiftGen/bin/swiftgen --version`, out by looking into your `Podfile.lock` generated by CocoaPods

**Comment by YiYiZheng** [comment]
Yeah! After run `pod repo update`, I can get the new version of SwiftGen. Xcode compiles successfully. 
I will continue to dive in.
My suggestion is specify this problem in the README.md. Also `Pods/SwiftGen/bin/swiftgen config lint`. I took a long time for these problems.   
Thx.

**Comment by AliSoftware** [comment]
Thanks for the suggestion and the follow up!

We might consider adding those notes to the README indeed (although those — especially doing `pod repo update` — are more related to CocoaPods own documentation though and had nothing to do with SwiftGen itself as it's applicable whatever pods you install with Cocoapods)
