### ISSUE TITLE
Support to Danger plugin

### ISSUE THREAD

**Issue by yutae** [SwiftGen/SwiftGen#558]
## Support to Danger plugin

I suggest to add a support for [Danger](https://github.com/danger/danger) plugin. Inspired by [Danger-swiftlint](https://github.com/ashfurrow/danger-swiftlint)

### Why ?

When using swiftgen, swiftgen must be run if there are any corresponding input changes.
After swiftgen, It will be a useful tool if developers can detect output changes using danger in PR.

### Expectation

- swiftgen config
- If there is any output change, post `Danger warn (default) or error(option)`

I would like to start this project or participate in it. 😄

**Comment by AliSoftware** [comment]
Just to be sure I understand your suggestion, you'd propose to make a Danger plugin dedicated to warn about SwiftGen changes, so that other people using SwiftGen can easily use that plugin in their own `Dangerfile`, right? (and not integrate Danger in this SwiftGen repo, which is already done)

I like the idea 👍  but I wonder if it's worth it writing a dedicated plugin for this, as opposed to just adding a single line to the user's `Dangerfile` like this:

```ruby
warn("SwiftGen config changed!") if git.modified_files.include?('swiftgen.yml')
```

So maybe if that's as simple as that, just suggesting this in the README or one of the `Documentation/` docs would suffice?

**Comment by AliSoftware** [comment]
I think this plugin could go in pair with #441, as in: for both issues we'll need a command to generate the list of inputs and output/generated files

So imagine if we add a new command that would look something like this: `swiftgen xcfilelist --inputs inputs.xcfilelist --outputs outputs.xcfilelist`, which would generate the list of input and output files according to the content of the `swiftgen.yml` config file. If we had such a command (= #441 would be implemented), then the rule in `Danger` could just be something like:

```ruby
outputs = `swiftgen xcfilelist --outputs /dev/stdout`.split("\n")
outputs.each do { |f| warn("File #{f} was modified by SwiftGen") if git.modified_files.include?(f) }
```

Thoughts?

**Comment by djbe** [comment]
Given access to the config file, it could just as well directly parse the config file instead of relying on the existence (and output format) of an `xcfilelist` command.

**Comment by AliSoftware** [comment]
@djbe I first thought the same at first. But if one would do that in ruby, there might be a couple of things to handle manually during parsing though then:

1. As of the current config file format/features, they would at least have to be sure to not forget to prepend the `output_dir` option at the top of the YAML file if present to all outputs.
2. But also later on once we implement #355 (env vars in config file, as well as glob / `fnmatch` patterns), that would have to be replicated in the ruby code as well (and potentially leading to inconsistent lists of files if the Swift implementation in SwiftGenKit and the ruby implementation in the Danger plugin slightly differ in interpretation for example)

So even if, as of today's supported features of the config file, parsing the YAML file manually in ruby (and just prepending the `output_dir` option manually) might seem sufficient, if we want to be resilient to future additions / evolutions of the config file (esp. #355) then I feel relying on SwiftGen itself to generate that output list (and be sure it's interpreted the same way as when SwiftGen do generate the outputs) feels more stable to me

**Comment by AliSoftware** [comment]
Also, parsing the YAML file in ruby might be tricky because you'd also have to take into account that `outputs:` can accept either an array of dictionaries (template, output), or directly one dictionary, etc… so reproducing all that logic (already implemented in SwiftGenKit) in ruby feels like duplicating all the logic and risking inconsistencies :wink:

**Comment by yutae** [comment]
Sorry. I guess I did not have enough explanation.

For example,
Input file `.strings` file has been modified but developer have not run swiftgen.
This will be a problem. therefore, this is to confirm. 
Run swiftgen and warn if output changes exists.

If I do this project, I will create a new repo.
ex) `danger-swiftgen`

```ruby
outputs = `swiftgen xcfilelist --outputs /dev/stdout`.split("\n")
outputs.each do { |f| warn("File #{f} was modified by SwiftGen") if git.modified_files.include?(f) }
```

Your suggestion is also good.
If I develop this project, I will add the above functions as well.

There is a difference in the point of view. but If modularized, it will be easy to apply.
just a line. 😄 
ex)
```ruby
swiftgen.modified_files

swiftgen.check modified_on_error: true // (option) 
# inline_mode
# excluded
...
```
