### ISSUE TITLE
Colors: Support for Android's color.xml format

### ISSUE THREAD

**Issue by takeTrace** [SwiftGen/SwiftGen#562]
I notice that #15 declare support for Android colors.xml, but when i use Android's xml from our team, i catch a error: "error: Invalid hex color "@color/theme_cyan" found for key "colorPrimary" (colors.xml)", because the xml use this format "<color name="colorPrimary">@color/theme_cyan</color>", maybe it's new for Android Studio support, can SwiftGen deal with this situation? i just see parse xml's value all use `Colors.parse(hex: value, key: name, path: path)`, or it's plan for support?

**Comment by AliSoftware** [comment]
I don't think we ever implemented a color referencing another color in the XML yet, should definitely be a feature worth adding support for indeed.

Could you post your colors.xml file so we have a good concrete example of what to support? We could even use it as a fixture for our unit tests on this one.

A fix should even be fairly easy to implement by yourself in a PR I think if you feel like it (we can guide you of needed) as it would mainly consist of recognizing `@color/` strings and reference that color during parsing instead of parsing it as hex.

**Comment by PoissonBallon** [comment]
Hi @AliSoftware && @takeTrace 

I am ready to make this PR for Android's XML support (it will be a great addition), but we have another issue, Android's XML is an ARGB format, today Swiftgen assumes we are in RGBA (if I'm not mistaken)
What is the best way to pass information if xml is RGBA or ARGB?

Thanks 👍

**Comment by PoissonBallon** [comment]
Hello,

After what you said, I think it would be annoying to wait for a major release.
We can implement the android behavior by analyzing the file name example: `colors@android.xml`
And indicating precisely in the README the procedure to follow and why.

In addition, IMHO change how work xml file even in a major release will be painful for existing users.

**Comment by AliSoftware** [comment]
We could also do it like @djbe suggested but without having to wait for a major version as long as we don't modify the defaults.

That means we'd still assume RGBA by default, but supporting the option to turn ARGB opt-in. Not changing the default = no need for a major version, and only drawback is that users using Android colors.xml will have to add `params: { argb: true }` in their `swiftgen.yml` explicitly to make it right.

_Then if we want, we could inverse the default in a next major version, deprecating the argb param and replacing it with an rgba param. Or not. But we can decide that later._

**Comment by djbe** [comment]
Yeah, that's why I mentioned "if we change the defaults". 

Note that we'll need to add a CLI option for accepting parser options here:
https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGen/Commander/ParserCLICommands.swift#L47
That could be implemented & tested in a separate PR.

**Comment by djbe** [comment]
Implemented in SwiftGen 6.5.0, which has been released 🎉
