### ISSUE TITLE
CaseIterable for *.xcassets template

### ISSUE THREAD

**Issue by soxjke** [SwiftGen/SwiftGen#571]
Swift 4.2 introduced neat feature https://developer.apple.com/documentation/swift/caseiterable for autogenerating `allCases` for enum values

Swift 4 template for xcassets (https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/xcassets/swift4.md) has a parameter `allValues` responsible for manual generation of `allImages`, `allColors` static var's for assets enum

1) Does it make sense to clone this template (say, create something like `swift42`) and make generated enum `CaseIterable` by default, removing `allValues` customization?
2) Does it make sense to do this for other enum templates?

The foreseen benefits are pretty obvious - more powerful enum's, advanced debug abilities for users, less code in templates.

If this makes sense for SwiftGen, I can create a PR with such templates.

Thanks!

**Comment by djbe** [comment]
Hi @soxjke,

The thing with `CaseIterable` is that there need to be actual cases in the `enum`s. In our (SwiftGen) case, the enums are empty and only used for namespacing purposes, note that we only have static constants.

**Comment by djbe** [comment]
BTW, the reason that we have static constants instead of cases, is that it makes no sense for a user to be able to `switch` over possible "cases" of an asset group.

I also don't know how it'd even be possible to have cases in combination with the type safety we currently have of image, color and data assets (using generics).

**Comment by soxjke** [comment]
Hi @djbe this makes sense.

The case I had with switch over possible cases was building a "gallery" with bundled images. I misread the template, so that I thought `CaseIterable` can be the case here.

Thanks for clarification!
