### ISSUE TITLE
Core Data: parameter to define additional imports

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#591]
Some of the properties of the generated models can be types defined in other modules. Unlike with the IB command, we have no way of knowing which modules these belong to, so we can't automatically generate the necessary import statements.

Mogenerator uses `additionalHeaderFileName`. I propose we use `additionalImports` (or something like that).

Bit of a throwback to #175 (PR for IB, where we added the `extraImports` parameter).

**Comment by AliSoftware** [comment]
Not sure if `extraImports` wouldn't fit here. Sure it's not completely the same, as for `ib`, `extraImports` is imports to add in addition to `import UIKit` and to all auto-imported modules, where here it will only be the ones in addition to `UIKit` and that's all… but still feels more consistent to use the same name for both?

**Comment by djbe** [comment]
I don't have any preference, `extraImports` works for me too. 🤷‍♂️

**Comment by djbe** [comment]
Implemented in #592.
