### ISSUE TITLE
Swift 5 templates

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#595]
Xcode 10.2 beta with Swift 5 is out. We should prepare new templates for Swift 5 with the needed changes (should be minimal).

We won't be able to test it yet until CircleCI adds Xcode 10.2 support (probably soon?).

Related to that change, we should consider deprecating the Swift 3 templates (like we did with 2, keep them around for a while, but unable to test them and removing them with the next major version)

**Comment by djbe** [comment]
Note that Xcode 10.2 doesn't support Swift 3 anymore:
> Swift 3 mode has been removed. Supported values for the -swift-version flag are 4, 4.2, and 5. (43101816)

**Comment by OlexandrStepanov** [comment]
Hello @djbe,

I believe Swift 5 template was not part of v.6.1.0 release, am I right?
Is there any ETA for the next release with these templates included?
If I want to use them, I should get SwiftGen tool from develop branch instead of version tag in cocoapods, that's correct?

Thanks in advance.

**Comment by djbe** [comment]
Hi @OlexandrStepanov,

That's right, you can test the swift 5 templates using the develop branch. Right now, there are no differences between the `swift4/5` templates, although both have small fixes that are not in the SwiftGen 6.1 `swift4` template. We hope to release these very soon!

**Comment by djbe** [comment]
Fixed in SwiftGen 6.2.0, should be available on CocoaPods (and other package managers) very soon!
