### ISSUE TITLE
String flat-swift4.stencil template does not match with documentation

### ISSUE THREAD

**Issue by caldofran** [SwiftGen/SwiftGen#604]
After reading the documentation about `flat-swift4.stencil` found here: https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/strings/flat-swift4.md

I've realised that the generated file is not matching what the documentation said.
In this section https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/strings/flat-swift4.md#generated-code the generated code is an enum with a case per localizable string key.

But after generating the strings file, the localizable strings are `static let` and `static func` like you could find here https://github.com/SwiftGen/SwiftGen/blob/master/Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable.swift

**Comment by djbe** [comment]
Good catch. We updated the "Usage Example" bit, but forgot to update the "Generated Code" section.

Would you like to create a PR to fix this? It's a perfect starter task 😄 (if not I can definitely do it one of the coming days).

**Comment by AliSoftware** [comment]
Fixed by #612 (not sure why GitHub didn't auto-close this issue once #612 was merged 🤷)

**Comment by djbe** [comment]
@AliSoftware GitHub does not auto-close if you're not merging into the main branch.
