### ISSUE TITLE
[Pre-Pitch] Localized strings conversion functionality

### ISSUE THREAD

**Issue by larryonoff** [SwiftGen/SwiftGen#608]
What community thinks about adding strings conversion functionality into the library, e.g. csv2strings, strings2csv. I tried to find some good solutions and the only good solution I've found is http://netbe.github.io/Babelish/. But I think this functionality can be a great extension of `SwiftGen`.

**Comment by djbe** [comment]
This is something that's beyond the scope of SwiftGen. SwiftGen is meant to parse resources and generate code for the user (at least with the built-in parsers & templates). It is technically possible to write a `csv` parser and have a template that generates `strings` files, but it's not something that would match with our vision for SwiftGen.

There are plenty of other tools that allow import/export of multiple formats, paid ones such as POEditor and CrowdIn, or free ones such as [Pootle](http://pootle.translatehouse.org) (online) & [Virtaal](https://virtaal.translatehouse.org) (offline).

**Comment by larryonoff** [comment]
@djbe thanks!

**Comment by AliSoftware** [comment]
Even though it doesn't support CSV per see I'd add https://github.com/scelis/twine to the list of tools to convert and manipulate localization files in different formats 😉

**Comment by larryonoff** [comment]
@AliSoftware Thanks! I saw Twine. But their file format isn't what I like.

PS. Pitched and got great recommendations from community. Thanks again :)
