### ISSUE TITLE
CoreData: expand RawRepresentable to non-enum types.

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGen#609]
While messing around with phantom types, I noticed that `RawRepresentable` doesn't have to be an enum. It can be an `OptionSet`, but also our own type such as a `struct`. So for example, we could have (yay phantom types):

```swift
struct Identifier<T: NSManagedObject>: RawRepresentable {
  let rawValue: Int64

  init?(rawValue: Int64) {
    self.rawValue = rawValue
  }
}
```

And use it in some types:
```swift
final class Test: NSManagedObject {
  internal var id: Identifier<Test> {
    get {
      let key = "id"
      willAccessValue(forKey: key)
      defer { didAccessValue(forKey: key) }

      guard let value = primitiveValue(forKey: key) as? Identifier<Test>.RawValue,
        let result = Identifier<Test>(rawValue: value) else {
        fatalError("Could not convert '\(value)' to type 'Identifier<Test>'")
      }
      return result
    }
    set {
      let key = "id"
      willChangeValue(forKey: key)
      defer { didChangeValue(forKey: key) }

      setPrimitiveValue(newValue.rawValue, forKey: key)
    }
  }
}
```

So, this code quite closely matches what we already have for `enum` attributes (see #593) with the `enumType` user info key. What I propose is that we rename that user info key to something like `rawRepresentableType` (which can be set to `Identifier<Test>` for the example above).

An extra thing that we should consider adding is some user info key to trigger code generation to unwrap the enum optional as above, so that the resulting attribute is a `Identifier<Test>` instead of a `Identifier<Test>?`. Suggestions for a name are welcome 😄 For example: `unwrapOptional` set to `"true"`?

**Comment by djbe** [comment]
@AliSoftware thoughts on this (especially the `unwrapOptional` parameter)? Did you have something similar in Gyro?

**Comment by AliSoftware** [comment]
We don't have such an ability in Gyro, which only support enums not arbitrary RawRepresentable. We also had long discussions about how to handle the nullability of those enums, especially if there's one optional level because the init is failable but another one because the CoreData attribute is marked as optional in the xcdatamodel… not sure how you want to handle that in SwiftGen's templates, but a userInfo let seems like a good idea to give options to the user.

I like the ability to use any type as RawRepresentable though and not limiting it to enums. I think the userInfo key name is a bit of a mouthful though and would suggest `RawValue` instead — which is shorter and also matches the associatedtype name in the RawRepresentable protocol.

**Comment by djbe** [comment]
With the code generated from this, and my own code such as:
```swift
extension User {
  typealias Identifier: Identifier<User>
}

extension Article {
  typealias Identifier: Identifier<Article>
}
```

It's really cool to have the swift compiler tell me that it "can't convert `User.Identifier` to `Article.Identifier`" 😄

**Comment by AliSoftware** [comment]
We should definitively add such an example usage (like yours with `User.Identifier` vs `Article.Identifier`) in the template documentation (couldn't we generate those too btw?)

**Comment by djbe** [comment]
Nah, that's up to the user to do fancy stuff like that. We can't assume such things for the user, they may have more complex identifier types, etc... For example, my codebase has 2 types of identifiers (string based or int based) for different entities.

Also, `#keyPath` doesn't work for non-objc properties 😢 So that'd suddenly break a whole lot of things for users.

**Comment by AliSoftware** [comment]
Right. Still worth suggesting in the docs as a cool use case I think 😉

**Comment by djbe** [comment]
Might be worth writing a separate article with ways to use enums and the identifier example I mentioned? Same way mogenerator has a separate page on how to do this: https://github.com/rentzsch/mogenerator/wiki/Using-enums-as-types.

**Comment by AliSoftware** [comment]
👍

**Comment by djbe** [comment]
#610 has been merged 🎉
