### ISSUE TITLE
Question about inline vs runtime

### ISSUE THREAD

**Issue by tedgonzalez** [SwiftGen/SwiftGen#615]
Hi, sorry for the dumb question

May I know the difference between the two?

[Inline JSON](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/json/inline-swift4.md) 

[Runtime JSON](https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/templates/json/runtime-swift4.md)

Thanks!

**Comment by djbe** [comment]
Read the “when to use it” part of the doc for each template.

**Comment by AliSoftware** [comment]
Hello

As the template documentations that you link state in their respective "when to use this" sections, the "inline" template embed the content of the JSON in the generated code, while the "runtime" template loads it at runtime.

What this means is that:

* the inline template copies the values found in the JSON, so once you've generated the constants from that JSON using SwiftGen you don't need the JSON anymore. If your JSON contains `{ "name": "Alice"}` then the generated code will be roughly equivalent to `static let name = "Alice"
* On the other hand, the "runtime" template doesn't _copy_ the values from the JSON into the generated constants, but only references the keys, and will load the values from the JSON at runtime. This means that the generated code will be conceptually equivalent to something like `static let name = loadJSON("your file")["name"]` (pseudo-code). You'll still need to have your file added in your target and as a resource in the bundle of your app, and at runtime it will load the content of the JSON and read the values of the keys. This means that if you change some values in the JSON the generated code won't change. This is great for example for referencing keys in your Info.plist among other use cases.

**Comment by tedgonzalez** [comment]
Thanks for the detailed explanation!
