### ISSUE TITLE
ImageAsset loading is slow

### ISSUE THREAD

**Issue by shuoli84** [SwiftGen/SwiftGen#623]
I did an instrument in debug mode, the Bundle(for: BundleToken.self) is way slow. Consider cache the bundle object as 

```swift

private final class BundleToken {
    static var bundle: Bundle = {
        return Bundle(for: BundleToken.self)
    }()
}

```

**Comment by djbe** [comment]
Good idea! You're welcome to create a PR for this, as it's an easy starter task.
Note that it not only affects the `xcassets` template, but also the other templates that support bundles  (`fonts`, `ib`, `json` realtime, `plist` realtime and `strings`).

**Comment by shuoli84** [comment]
@djbe sure.

**Comment by shuoli84** [comment]
Mistakenly created a pr to master. reopen a new one. Ignore 624, pls review 625

**Comment by djbe** [comment]
#625 has been merged 🎉
