### ISSUE TITLE
[Brew] install linkage failure

### ISSUE THREAD

**Issue by jhandguy** [SwiftGen/SwiftGen#626]
Hi! 👋 
It seems like Swiftgen installation on Homebrew is somewhat broken.
Here are the steps:

1) Ran:

➜ brew reinstall swiftgen

2) Got:

==> Reinstalling swiftgen
==> Downloading https://homebrew.bintray.com/bottles/swiftgen-6.1.0.mojave.bottle.tar.gz
Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/0f9e7aa2c3737d8a2ea46143b6163d270b39c960f246275c2a0f9d48fb80690b--swiftgen-6.1.0.mojave.bottle.tar.gz
==> Pouring swiftgen-6.1.0.mojave.bottle.tar.gz
Error: Failed changing install name in /usr/local/Cellar/swiftgen/6.1.0/lib/Commander.framework/Versions/A/Commander
  from @rpath/libswiftDispatch.dylib
    to /usr/local/Cellar/swiftgen/6.1.0/lib/libswiftDispatch.dylib
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
==> Summary
🍺  /usr/local/Cellar/swiftgen/6.1.0: 196 files, 20.9MB

**Comment by enhorn** [comment]
We have the same issue and have done some investigation.
One dev had the issue, and one dev hadn't, and it wasn't until after we had run `brew update` on the working computer that it broke.

**Comment by fwal** [comment]
This _seems_ to be a homebrew issue, reported it here: https://github.com/Homebrew/homebrew-core/issues/38044

**Comment by fwal** [comment]
Seems to work again in brew version `2.0.6` 👍
