### ISSUE TITLE
Assets not found

### ISSUE THREAD

**Issue by jsonfellin** [SwiftGen/SwiftGen#633]
SwiftGen 6.1.0
Xcode 10.2.1

After updating to 6.1.0 from 6.0.1 my Assets.swift file was cleared and with only `// No assets found` added. My yaml file wasn't changed and I'm not getting any errors when running from the command line. Looking at the template file, I see `{% if catalogs %}` must be false.

Thanks for any tips.

**Comment by djbe** [comment]
If the `catalogs` variable is empty, then SwiftGen couldn't find any catalogs it could parse.

- Try running `swiftgen config lint` to check if there are any issues with your config file.
- Have you tried going back to 6.0, to see if that still works? Perchance you moved some files and forgot about it.
- Are you maybe using env. variables in your configuration file? Support for them was added in 6.1.

**Comment by jsonfellin** [comment]
My input path looked this:

```
xcassets:
  inputs: Assets.xcassets/
```

That forward slash messed it up. Weird that I didn't get an error in the command like though like I would if the path was completely wrong. Thanks for the quick reply!
