### ISSUE TITLE
Configuration file in json

### ISSUE THREAD

**Issue by AndreiVidrasco** [SwiftGen/SwiftGen#636]
Hi,

Would it be possible to add an option to write configuration file in json in addition to yaml format? For me it's much easier to write, read, and maintain json file compared to yaml.

I find quite convenient approach taken in [XcodeGen](https://github.com/yonaskolb/XcodeGen) which allows both(default goes to yaml)
`--spec: An optional path to a .yml or .json project spec. Defaults to project.yml`

**Comment by djbe** [comment]
Hi @AndreiVidrasco,

There's actually nothing stopping you from writing the config in JSON format. JSON is after all a subset of YAML, so any valid JSON is also valid YAML.

I haven't tried it with SwiftGen yet, but I don't see why it shouldn't work.

**Comment by AndreiVidrasco** [comment]
You're right, it works. Thanks
