### ISSUE TITLE
SF Symbols support

### ISSUE THREAD

**Issue by danielsaidi** [SwiftGen/SwiftGen#640]
It would be great if SwiftGen could generate static enum cases for the new SF Symbols that arrive in iOS 13.

**Comment by djbe** [comment]
Based on what though? Pretty sure it's going to be a fixed list, with system version specific symbols (so later iOS versions may have different names or more symbols).

I think this is more something for a micro library, that can potentially use SwiftGen to generate the code, based on (for example) an input JSON file.

**Comment by danielsaidi** [comment]
Well, SwiftGen could use the development target and use that target's available symbol set. But sure, if you prefer SwiftGen to be more agnostic, then perhaps this could be something for a micro library. Or perhaps Apple will add this enum themselves.

**Comment by djbe** [comment]
> SwiftGen could use the development target and use that target's available symbol set

Again, I'm not sure how that'd work? Where is the actual list of symbols? Or is there a mechanism to iterate over all of them?

Note: even if there is a list or mechanism, it still wouldn't really work as there may be platform differences, or new symbols in later versions.

**Comment by djbe** [comment]
There's already a mini-library that does this:
https://github.com/piknotech/SFSafeSymbols/

**Comment by danielsaidi** [comment]
Case cloooosed, thanks! 🙃

**Comment by acosmicflamingo** [comment]
Interesting...am I the first person in history that's created my own SF Symbol that I want SwiftGen to generate an enum for? LOL Would it be possible to reopen the ticket not for supporting system SF Symbols but custom ones that I import into my own .xcassets folder?

**Comment by acosmicflamingo** [comment]
Oh wait a minute, this might be supported already. Which means...Tuist doesn't support it 😂
