### ISSUE TITLE
Core Data generate managed objects to separate files 

### ISSUE THREAD

**Issue by andriyslyusar** [SwiftGen/SwiftGen#643]
Hi, thanks for great work. Is it possible to configure SwiftGen to generate ManagedObjects from `xcdatamodeld` to separate files instead of single file?

**Comment by MilesHopkins** [comment]
Hey, was this question/issue ever resolved/answered? Trying to do the same thing atm

Thanks

**Comment by djbe** [comment]
Hi @andriyslyusar & @MilesHopkins,

This is currently not possible with how SwiftGen is setup, and we have no direct plans to add this in the near future. If there's enough interest, we will of course revisit this topic.

**Comment by djbe** [comment]
Closing this for now due to inactivity.
