### ISSUE TITLE
GUI tool to configure SwiftGen

### ISSUE THREAD

**Issue by MarcSteven** [SwiftGen/SwiftGen#646]
I think it is not good to use .
Do as the documentation ,but I always failed.
So why not make it like a GUI Tool ,let it simple . Two step to import  and then run. All will be done

**Comment by djbe** [comment]
Hi @MarcSteven,

Thank you for your feedback. SwiftGen's current focus is a CLI interface, with the configuration mainly done via a configuration YAML file. We believe this is currently the best way to handle these sorts of things, similarly to other tools such as SwiftLint, SwiftFormat, XcodeGen, etc...

If there's enough interest we could at some point create some sort of tool or UI for easier configuration, but that is not our main focus right now.

**Comment by MarcSteven** [comment]
Yeah it makes sense, I  hope you can publish GUI Tool very soon.
@djbe  Thank you so much.

**Comment by LeaderBoy** [comment]
@MarcSteven  GUI tool for SwiftGen - [https://supercoder.lessimore.cn/features/code](https://supercoder.lessimore.cn/features/code)
