### ISSUE TITLE
Fonts: `Font` typealias is incompatible with SwiftUI 

### ISSUE THREAD

**Issue by danielsaidi** [SwiftGen/SwiftGen#647]
I you use `SwiftGen` for fonts in an app that uses SwiftUI, the `Font` typealias will conflict with SwiftUI's new `Font` type.

**Comment by danielsaidi** [comment]
This is still very much an issue. Any progress on this, or is there a param I can use to change the name of the generated typealias?

**Comment by djbe** [comment]
We should add a template parameter to configure this. We can't really change the typealias by default, as it may break things for existing users.

**Comment by danielsaidi** [comment]
Yeah, a param would be great. Still, modifying the preset in a major update would also work, right?

**Comment by djbe** [comment]
We try to avoid breaking changes if at all possible, but I think this one is perfectly fine for a 7.0 release. The impact is quite minimal after all, the `Font` typealias is just a helper in the generated code, and not something people are meant to be using.

**Comment by djbe** [comment]
@danielsaidi I've created a PR to address this issue.

Until this is merged and released, you can use a custom template based on the template in #728, and modify your configuration to set `fontTypeName`. That way, you'll be ready for when we release SwiftGen 6.3.0.

**Comment by danielsaidi** [comment]
@djbe Perfect, thank you! I will give it a try after WWDC.

**Comment by djbe** [comment]
SwiftGen 6.3.0 has been released, which includes this change 🎉 

We've also deprecated the `Font` typealias, and will be removing it in the next major release.
