### ISSUE TITLE
Support for Dark mode colors

### ISSUE THREAD

**Issue by AndreiVidrasco** [SwiftGen/SwiftGen#651]
Apple added new method for initializing dynamic colors
```
Color(dynamicProvider: { trait in
    if trait.userInterfaceStyle == .dark {
        return darkColor
    }
    return lightColor
}
```
Would it be possible to extend `colors`, so we can add both in txt, json or xml?

**Comment by djbe** [comment]
I'd very strongly recommend using asset catalogs in this case, they do this fully automatically for you.

**Comment by ValeriyJefimov** [comment]
> I'd very strongly recommend using asset catalogs in this case, they do this fully automatically for you.

That will not work correctly on ios < 11

**Comment by premedios** [comment]
Developing apps for ios < 11 is extremely rare and you can't even submit them to the AppStore

**Comment by stefanovecchiatipfc** [comment]
hello, I don't know if is the correct place for ask this question, but if I have the dark mode active is possible load an asset catalog color in the light mode? Basically force to load an any appearance mode instead the dark one? Thanks
