### ISSUE TITLE
Add caching/hashing functionality, to avoid regenerating the code every time

### ISSUE THREAD

**Issue by acecilia** [SwiftGen/SwiftGen#652]
I am running SwiftGen as a build phase on Xcode in a big project. 

I am experiencing that running SwiftGen takes around 0.5 seconds every time. The problem is that Xcode is detecting that the generated files are touched (I think this is the reason), and is recompiling them on every build, taking an extra 6 seconds.

I think it should be possible to add some kind of cache/hashing functionality to prevent regenerating the code if the source files did not change.

One way I can think about is by hashing the source files and adding the hash as a comment inside the generated files. Then, when SwiftGen runs, if the hash matches the files should not be regenerated neither touched.

**Comment by djbe** [comment]
Uhm, the process you're describing is exactly what SwiftGen already does. It will generate the output in memory, compare it with the file, and only write the output to disk if there's a difference. 

Here the output is generated:
https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGen/Commander/ConfigCommands.swift#L48-L50
And here the output is written to disk only if there are changes:
https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGen/Commander/OutputDestination.swift#L35

Could you check the output of running SwiftGen? Are you seeing "Not writing the file as content is unchanged" or "File written: ..."?

**Comment by acecilia** [comment]
Okey, I think I found the issue.

I am using SwiftGen to generate a framework with my assets and localization keys. After generating the files, I am substituting `(for: BundleToken.self)` with `.main`, as my asset catalog and localization file are in the main bundle, and not in the framework bundle. This of course is bypassing the check you mentioned.

I think SwiftGen will benefit for checking if the origin files changed, better than if the output files are the same, because it will save some processing time. But I understand this may be a too specific use case, and may not easy to implement.

Will be closing this for now, thanks for the response @djbe!

For the record: what I am doing to avoid this is manually checking if the input files (asset catalog and localization file) have a modification date more recent than the output files (generated source code):
```
# This script takes some time to run. In order to run it only when neccessary, we have to check if the input files
# changed. In theory Xcode can do this. in reality the functionality is buggy, so here we do it ourselves
# See: https://wincent.com/blog/xcode-input-output-files-bug
if [[ $input_localizable -nt $output_localizable ]] || [[ $input_assets -nt $output_assets ]]; then
    # The input files changed, and source code needs to be regenerated
    swiftgen
fi
```

**Comment by djbe** [comment]
Right, what you want then is to actually use Xcode's built-in system for this. But then **you** have to set the build phase's input and output files, and these have to point to actual files, not directories (it won't recurse).

**Comment by djbe** [comment]
And TBH, for your use case, I would just use a custom template. Follow the instructions here on how to do it:
https://github.com/SwiftGen/SwiftGen/blob/master/Documentation/Creating-your-templates.md

That way, you don't need any shenanigans with changing the output from `swiftgen`.

**Comment by acecilia** [comment]
The Xcode built-in system is buggy, thats why I am doing it manually in bash (see: https://wincent.com/blog/xcode-input-output-files-bug).

Thanks for the tip of the custom template, ill have a look.
