### ISSUE TITLE
Dependency graph is unresolvable

### ISSUE THREAD

**Issue by ziadtamim** [SwiftGen/SwiftGen#657]
## What did I do?

```swift
dependencies: [
        .package(url: "https://github.com/Realm/SwiftLint", from: "0.34.0"),
        .package(url: "https://github.com/yonaskolb/XcodeGen.git", from: "2.6.0"),
        .package(url: "https://github.com/SwiftGen/SwiftGen.git", .upToNextMajor(from: "6.1.0"))
    ]
```
to a brand-new Package.swift created by swift package init, and attempted to download the dependency and build the project using swift build.

## What did I expect to happen?

I expected `swift build` to succeed.

## What happened instead?

I received the following output:

```
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/SwiftGen/SwiftGen.git @ 6.1.0..<7.0.0
```

## Charts Environment

**Xcode version:**
10.3 (10G8)
**Swift version:**
5.0

**Comment by stjernegard** [comment]
This happens because Swiftlint 0.32.0 and newer require `jpsim/Yams` 2.0 while SwiftGen is still using 1.0.

**Comment by djbe** [comment]
FYI SwiftGen does not work with SPM yet, because SPM doesn't support resource bundles (which we need for the templates). Instead you can use [Mint](https://github.com/yonaskolb/Mint).
