### ISSUE TITLE
Generate tests

### ISSUE THREAD

**Issue by 343max** [SwiftGen/SwiftGen#658]
Hi! I wonder if it would be good to generate tests as well when generating code. This way it would be a no brainer to find out if everything is setup correctly and still in order. Are there any ideas to do this or has it been dismissed?

**Comment by jrtibbetts** [comment]
You shouldn't need dedicated tests for the generated code if the code that _uses_ the generated code is tested.

**Comment by 343max** [comment]
I don't agree. When you delete some assets and forget to re-run swiftgen the tests could save you. Also If you a resource doesn't gets copied to the app bundle (because you forgot the tick the checkbox) a test could safe you. Generating code is one thing making sure it's actually working as expected and doesn't break is another.

**Comment by jbehrens94** [comment]
Forget to run SwiftGen? You could always add SwiftGen as a build phase to an Xcode project, and you'll almost always be up to date. Besides, if the project doesn't compile, that would (if you look at it loosely) mean a failing test anyway. So, I don't see the need to test the generated code.

**Comment by 343max** [comment]
Adding swiftgen as a build phase would make builds slower so it isn't really an option.

Also my other case when a file is part of the project but isn't being copied into the project isn't covered by your approach.

**Comment by djbe** [comment]
It doesn't really make build slowers, in all the large production projects we use it in, the impact is at most half a second. And note that SwiftGen does **not** modify the generated files if the output would be the same, so that Xcode doesn't recompile everything.

In essence, the impact is negligible.

**Comment by 343max** [comment]
Even if it's fast it's still an overhead.

But this answer still doesn't cover the case where a file might be part of the directory structure but won't get copied in the bundle or is corrupted or whatever.

**Comment by djbe** [comment]
Like I said, an overhead that is negligible. If you want, you can remove it from your normal build steps and only run it on CI (and throw an error if the user forgot to run SwiftGen). The point is, it needs to run somewhere. Oh and please note that running SwiftGen is probably 10x faster than building & running Swift tests.

IMO SwiftGen shouldn't check if your build process is working or not. Some people only use Xcode, some use Bazel/..., some use something else. SwiftGen's task is to parse the resources you point it to, and generate code you want.

Can you generate code for tests? Sure. We even recommend people write custom templates for their specific needs. Our standard templates are meant for 90% of the use cases, and as a demonstration on what is possible and what we recommend.

Can you make such a template generic enough, as to test resources in bundles/frameworks, storyboard scenes/segues (where the module is important), etc...? I don't think so (but would love to be proven wrong). And the question would still be, how many people would use this, and how much overhead would it be for us to maintain it.

Again, the idea is definitely good, especially for us (SwiftGen) internally to test our templates. I'm just not sure how feasible it is, and how much the general user base wants it.

**Comment by djbe** [comment]
Also note that there are actual tools to check your Xcode project, and/or to even generate it, so that should solve your 2nd issue.
