### ISSUE TITLE
Strings: stencil template creates duplicate enums

### ISSUE THREAD

**Issue by mrtsamma** [SwiftGen/SwiftGen#660]
Getting error "Invalid redeclaration of 'MySub'"

Using SwiftGen v6.1.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.1.0)
Generating String with template  [structured-swift4.stencil](https://github.com/SwiftGen/SwiftGen/blob/master/templates/strings/structured-swift4.stencil)

String keys will look like:
```
"main.mySub.value" = "value";
"main.my-sub.key" = "key";
"main.my_sub.key" = "key";
"main.mySub.key" = "key";
```
Output:
```Swift
internal enum L10n {
    internal enum MySub {
      /// key
      internal static let key = L10n.tr("Localizable", "main.my-sub.key")
    }
    internal enum MySub {
      /// key
      internal static let key = L10n.tr("Localizable", "main.mySub.key")
      /// value
      internal static let value = L10n.tr("Localizable", "main.mySub.value")
    }
    internal enum MySub {
      /// key
      internal static let key = L10n.tr("Localizable", "main.my_sub.key")
    }
  }
```

Is there possible to convert them all to one enum?
I guess that these will create each separate child under tables.first.levels.children. 
Any solution suggestions? I can't just rename keys, because they come from API if an error occurs.

**Comment by djbe** [comment]
Hi @mrtsamma,

Ideally your keys have a consistent structure, but like you said, we don't always have control over this.

There is an existing issue that discusses this topic, and it is something we're planning on tackling probably after the 6.2 release.

**Comment by acecilia** [comment]
Hey @djbe, any change to post here a link to the parent issue? 🙏  Cant find it at the moment. Thanks!
