### ISSUE TITLE
Is SwiftGen still under active development?

### ISSUE THREAD

**Issue by jrtibbetts** [SwiftGen/SwiftGen#661]
The most recent commit to `master` is from January 2019.

**Comment by djbe** [comment]
All development for new versions happens on the `develop` branch, which is why the last change to `master` dates to the last release.

TBH a release has been almost ready for quite some time (see #621), but finding time has been difficult. I'll try to at least get 6.2.0 out in the next few days.

**Comment by markusfassbender** [comment]
Would be great to have a new release, thank you for your work @djbe :)

**Comment by mycroftcanner** [comment]
How do you use the develop version? I tried setting up the git param in Podfile... no binary is installed

**Comment by aspcartman** [comment]
For people ending up here searching for swift5 support etc I do such a build step:
```bash
if which swiftgen >/dev/null; then
  swiftgen config run --config swiftgen.yml
else
  echo "warning: SwiftGen not installed"
  echo "please do"
  echo "brew install libxml2 mint"
  echo "mint install SwiftGen/SwiftGen@develop"
fi
```

**Comment by danielsaidi** [comment]
What's the current state of SwiftGen 6.2.0?

**Comment by mortenholmgaard** [comment]
@djbe Any news here? 
I would hate to see such a great lib be useless because of no active development..

**Comment by danielsaidi** [comment]
Given that he said he'd try to get 6.2.0 out in a couple of days in October and has been silent ever since, I am actually kind of worried.

**Comment by djbe** [comment]
No worries, still alive 😉 Same story as always, just been really busy.

**Comment by djbe** [comment]
Actually, if anyone on the team could take a look at #619 so we can merge that. Then I can open a PR for a branch I have based on that (https://github.com/SwiftGen/SwiftGen/tree/feature/update-pods), we can at least get CI working again and make a (alpha?) release.

**Comment by jrtibbetts** [comment]
> No worries, still alive 😉 Same story as always, just been really busy.

But we all have oodles of free time because of quarantine now, right?

j/k

**Comment by djbe** [comment]
SwiftGen 6.2.0 has been released! 🎉 It should be available on your favourite package manager very soon!
