### ISSUE TITLE
[Feature] General file resources from bundle

### ISSUE THREAD

**Issue by mgray88** [SwiftGen/SwiftGen#665]
I'd like to work towards adding support for parsing other file resources that need to be accessed from the bundle, usually with `Bundle.main.url(forResource:withExtension:)` and the like.

Looking through the issues it seems this is a desired functionality, but not much work has been towards achieving it
#109, #146, #284, #496, #637 

My thoughts on the implementation:
- A good name for the subcommand might be `resources`
- Correct me if I'm wrong, but it looks like `inputs` and `filter` are the best way to specify files or file types to include
- It seems I can probably implement the generator pretty quickly duplicating functionality from the yaml and plist generators
- Possible params:
  - enumName (default `Resource`)
  - publicAccess (default `false`)

Thoughts on template:
- Containing enum: `Resource`
- Each resource as a struct `ResourceFile`
- Each resource should have a name including the extension for uniqueness and clarity
- `ResourceFile` can expose two computed properties
  - `url` for `url(forResource:withPath:)
  - `path` for `path(forResource:ofType:)

Need input on:
- Arrays of resources
- Handling subdirectories implicitly/explicitly/disregarding

Thoughts? Ideas? Did I miss anything?

**Comment by djbe** [comment]
Hi @mgray88!

I think you've got topics things covered.

- For each resource(file), I'd also add a few properties such as name (without extension), extension, ... (in the context, so that in the template we can handle things appropriately)
- Subdirectories: I think we may want to handle this like the asset catalog parser, so include directory structure information in the context, and let the template choose to use that information or not.
- Maybe add mime type information to resource files? Not sure if it's worth it, and if there's any performance impact in trying to parse this.

**Comment by mgray88** [comment]
Awesome. Real life got in the way since I last worked on this, but I would like to see it through. I've got a start at https://github.com/mgray88/SwiftGen/tree/feature/file-resources

If you're able, let me know what you think. I remember I was working on getting the tests set up before I went any further and ran into an issue where Swiftlint was linting my test files and complaining about the comment header. Which was just copied from the existing test files

**Comment by djbe** [comment]
You can always open a draft PR and we can discuss some technicalities in there

**Comment by pfandrade** [comment]
Hey @mgray88, are you still working on this? I actually had the same need and this looks like exactly what I was looking for.

**Comment by mgray88** [comment]
@pfandrade I haven't been able to in a while. Thankfully my company is hiring an Android dev which will halve my workload. I was hoping to start back on it in a few weeks.

I'll start a PR with what I have if you'd like to help out. It's pretty far behind `stable` so I don't know how much of it is out of date

**Comment by mgray88** [comment]
https://github.com/SwiftGen/SwiftGen/pull/734

**Comment by pfandrade** [comment]
Hey, awesome! If I'm able to free up some time, I'll try to help out.

**Comment by darknoon** [comment]
Is this done, or are there more pieces beyond the current files parser support?

**Comment by mgray88** [comment]
@darknoon The feature as envisioned is complete in the PR that was merged into `develop`

@djbe Any news on an upcoming release?

**Comment by djbe** [comment]
Implemented in SwiftGen 6.5.0, which has been released 🎉
