### ISSUE TITLE
Strings: Objective-C template does not compile for entries with parameters

### ISSUE THREAD

**Issue by otusweb** [SwiftGen/SwiftGen#673]
steps to repro:
- create a localisation with substitution (ie: "version label"="Version: %@(%@);"
- run swiftgen with the Objc template

=> .h file does not compile because semi column is missing after every string with a substitution

generated code:
`+ (NSString*)versionLabelWithValues:(id)p1 :(id)p2`

expected code:
`+ (NSString*)versionLabelWithValues:(id)p1 :(id)p2;`

Fix:
In template: add ';' at the end of line 44 and 46

**Comment by djbe** [comment]
This has been fixed by #672, which will be in the 6.2.0 release.

**Comment by djbe** [comment]
Fixed in SwiftGen 6.2.0, should be available on CocoaPods (and other package managers) very soon!
