### ISSUE TITLE
Question: Is it possible to publish a new version of SwiftGen like 6.2.0?

### ISSUE THREAD

**Issue by AF-cgi** [SwiftGen/SwiftGen#680]
There are so many fixes and merged issues on the develop branch. Is it possible to publish a new version? It's not really a option to use the develop branch instead.

**Comment by bitsmakerde** [comment]
Good idea, I see a lot of Swift 5 improvements in 6.2.0

**Comment by moto0000** [comment]
+1

**Comment by djbe** [comment]
SwiftGen 6.2.0 has been released! 🎉 It should be available on your favourite package manager very soon!
