### ISSUE TITLE
Asset Catalog: SwiftGen throws an error for some color assets

### ISSUE THREAD

**Issue by szweee** [SwiftGen/SwiftGen#683]
I want to generate colors.swift file through Colors.xcassets After compiling, I am prompted about this：

```
Not writing the file as content is unchanged
[31merror: Unable to parse file at /Users/szweee/Documents/ApplePai/ApplePai/Resources/Colors.xcassets/mainTheme.colorset/Contents.json. Invalid structure, must be an object with string values.[0m
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by tychop** [comment]
Can you post the contents of the /Users/szweee/Documents/ApplePai/ApplePai/Resources/Colors.xcassets/mainTheme.colorset/Contents.json file? It can give an idea as to what the problem is...

**Comment by szweee** [comment]
> Can you post the contents of the /Users/szweee/Documents/ApplePai/ApplePai/Resources/Colors.xcassets/mainTheme.colorset/Contents.json file? It can give an idea as to what the problem is...


[Contents.txt](https://github.com/SwiftGen/SwiftGen/files/4379668/Contents.txt)

**Comment by szweee** [comment]
> Can you post the contents of the /Users/szweee/Documents/ApplePai/ApplePai/Resources/Colors.xcassets/mainTheme.colorset/Contents.json file? It can give an idea as to what the problem is...

This is a color file
<img width="1126" alt=" 2020-03-25 pm4 05 24" src="https://user-images.githubusercontent.com/20777870/77514946-afbf3800-6eb2-11ea-8e69-4099ed2bcaf0.png">

**Comment by twittemb** [comment]
Hi there.

Same issue here with a Color.xcassets file with one colour (Any, Dark).

here is the Contents.json:

```
{
  "colors" : [
    {
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "alpha" : "1.000",
          "blue" : "1.000",
          "green" : "0.759",
          "red" : "0.196"
        }
      },
      "idiom" : "universal"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "alpha" : "1.000",
          "blue" : "0.517",
          "green" : "0.814",
          "red" : "0.669"
        }
      },
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

**Comment by twittemb** [comment]
If you use the ```xcassets``` and not the ```colors``` section, it works fine though.

**Comment by djbe** [comment]
I'm curious as to why it's even trying to parse that catalog entry...

The extension is clearly `.colorset`, and with color sets, we normally don't even bother parsing the contents: https://github.com/SwiftGen/SwiftGen/blob/master/Sources/SwiftGenKit/Parsers/AssetsCatalog/CatalogEntry.swift#L67

For some reason it's skipping to the `nil` case (unknown type or a group), thinks it is a group because `type` (the extension) is empty, and tries to check if the group is namespaced. @szweee or @twittemb, could you upload a sample catalog (zipped) that breaks SwiftGen as above? I'd like to debug this locally.

**Comment by tychop** [comment]
It's happening to me with attached color asset:
[Background.xcassets.zip](https://github.com/SwiftGen/SwiftGen/files/4890592/Background.xcassets.zip)

error: Unable to parse file at /Users/tychop/Documents/xcodeprojects/pandy/VisualStyleGuide/VisualStyleGuide/Resources/Colors/Background.xcassets/klmWarmGreyMedium.colorset/Contents.json. Invalid structure, must be an object with string values.

(Using swiftgen 6.2.1 via homebrew)

**Comment by djbe** [comment]
@tychop I just ran it directly here:

**Comment by djbe** [comment]
@tychop I just ran it directly here with no issues:
```bash
$ swiftgen run xcassets --templateName swift5 Background.xcassets
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ColorAsset.Color", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetColorTypeAlias = ColorAsset.Color
...
```

Note: that's invoking via Homebrew. I've also tried it directly using a development build with no issues.

**Comment by djbe** [comment]
Note to everyone: to parse assset catalogs you **must** use the `xcassets` parser, not the `colors` parser!

The `colors` parser is for parsing things like an Android colors.xml, or a `.clr` file:
https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/Parsers/colors.md

The `xcassets` parser is meant for asset catalogs, and supports multiple asset types such as image sets, color sets, data sets, etc...:
https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/Parsers/xcassets.md

**Comment by tychop** [comment]
Yes, I can confirm: It works when using xcassets instead of colors.

**Comment by djbe** [comment]
Allright, so this was never an issue with SwiftGen, just an use of the wrong parser. Good to hear!
