### ISSUE TITLE
SwiftGen causes compiler crash running Swift 5.2 from command line

### ISSUE THREAD

**Issue by samrayner** [SwiftGen/SwiftGen#686]
Steps to reproduce:
1. brew uninstall swiftgen
2. Install Xcode 11.4, ensure selected with xcode-select
3. In command line: `echo "import Foundation; print(Date())" | swift -` (prints date)
4. brew install swiftgen
5. In command line: `echo "import Foundation; print(Date())" | swift -` (CRASHES)

Note: This crash did not occur with Swift 5.1 or earlier. It does not occur with the Swift REPL, only piping from stdin or executing a file with the `swift` command.

I initially assumed this was a Swift bug and filed a radar but Apple traced it to SwiftGen when they noticed that the Swift process was loading /usr/local/Cellar/swiftgen/6.1.0/lib/libswiftFoundation.dylib

Thanks!

Resolved: rdar://problem/59976668
Resolved: https://bugs.swift.org/browse/SR-12306

**Comment by djbe** [comment]
Ehm, did they specify anything besides "it's SwiftGen's fault"? I'm unsure how we're modifying any of the system libraries...

**Comment by samrayner** [comment]
I believe it's simply the existence of the dylib that causes it to be loaded. If you delete that dylib after brew installing it fixes the issue.

**Comment by djbe** [comment]
So simply the fact that we're embedding swift libraries breaks the whole system? That's insane.
Note: can confirm this on my own system, got SwiftGen installed via HomeBrew and the example command above crashes.

How are other tools handling this? I noticed that `swiftlint` doesn't include swift libraries (or links them statically, no idea).

**Comment by djbe** [comment]
Should be fixed in 6.2.1, which should be available via Homebrew very soon: https://github.com/Homebrew/homebrew-core/pull/57508
