### ISSUE TITLE
CoreData: Ambiguous use of fetchRequest()

### ISSUE THREAD

**Issue by davidrothera** [SwiftGen/SwiftGen#725]
There is an autogenerated method on all `NSManagedObject` objects called `fetchRequest` which has the below implementation:

```swift
/* A new fetch request initialized with the Entity represented by this subclass. 
   This property's getter is only legal to call on subclasses of 
   NSManagedObject that represent a single entity in the model.
 */
@available(iOS 10.0, *)
open class func fetchRequest() -> NSFetchRequest<NSFetchRequestResult>
```

Because we generate a method with the same name (but a more concrete type) it leads to ambiguous use errors unless you explicitly define the type like below which feels a little "un-swifty"

```swift
let fetchRequest: NSFetchRequest<Foo> = Foo.fetchRequest()
```

Although it would be a breaking change I would suggest naming the SwiftGen generated methods to something different like `createFetchRequest`

**Comment by djbe** [comment]
You're right, this would be a breaking change, so whatever PR that changes the method will have to wait until 7.0.

I sometimes have the same issue in my code, and have to solve it as mentioned above. In other cases, Swift can infer the type itself and do the right thing:
```swift
func fetchRequest(name: String) -> NSFetchRequest<Foo> {
  Foo.fetchRequest().then {
    $0.predicate = NSPredicate(format: "%K = %@", #keyPath(Foo.name), name)
  }
}
```

**Comment by djbe** [comment]
SwiftGen 6.3.0 has been released, which includes the change that fixes this 🎉
