### ISSUE TITLE
CoreData: Using RawType and unwrapOptional with OptionSet doesn't work

### ISSUE THREAD

**Issue by davidrothera** [SwiftGen/SwiftGen#727]
It is recommended for the `rawValue` type for `OptionSet` types be a fixed-width integer type which then allows you to use "set math" on them.

When using the new `RawType` and `unwrapOptional` generator options it generates code which is incompatible as creating an `OptionSet` from a `rawValue` doesn't return an optional (as it does with Enums).

**Comment by djbe** [comment]
Hmmm, can we detect this in the template? In the template engine, we are not "aware" of any of the types passed along in the `RawType` parameter.

Does it work if you add an additional `init` to your type that returns an optional?

**Comment by davidrothera** [comment]
I'll give the optional `init` a go now and let you know, I don't think there would be an easy way around this other than adding another option for `NoneOptionalInit` (or something)

**Comment by davidrothera** [comment]
Nope looks like that doesn't work unfortunately:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/2766321/85413083-40fd8380-b562-11ea-9124-1b5cc1b7e73b.png">

**Comment by djbe** [comment]
Does it work if you have both `init`s? Or is that not possible/available?

**Comment by davidrothera** [comment]
@djbe - Nope, unfortunately I don't think Swift (at the moment) supports having initializers with matching arguments/types apart from differing optionality ☹️

**Comment by djbe** [comment]
Boooooo 👎 Although I realise it would be a nightmare for the type checker, so yeah... 😅 

Allright, only option then is to add another `userInfo` setting like you mentioned before. You mentioned `NoneOptionalInit`, which sounds ok. Anyone got better candidates? Once we decide on a name, we can get started on a PR to fix this.

Would adding a `userInfo` setting for non-optional `init` be enough though? Are there other potential issues or edge cases?

**Comment by davidrothera** [comment]
I think the none optional init should suffice, the new option would simply move the creation of the return type to outside of the guard statement.

Once we're agreed on an option name I'll get a PR up for it to avoid churn if we change later on.

👍

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
