### ISSUE TITLE
I've added a swiftUIColor property in the swift5.stencil template of Assets.

### ISSUE THREAD

**Issue by tychop** [SwiftGen/SwiftGen#747]
I've added a property to the ColorAsset class so I can get SwiftUI colors from the generated code.

So now I can get a swiftUI color by calling `Asset.FormColors.coldGreyMedium.swiftUIColor`

Is this something you guys want to incorporate in SwiftGen? If so, do I open up a pull request (I haven't done that before) for or is posting this stencil here enough?
[swift5.stencil.zip](https://github.com/SwiftGen/SwiftGen/files/4895530/swift5.stencil.zip)

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
