### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by amine2233** [SwiftGen/SwiftGen#753]
SwiftGen not work on macos Big Sur and Apple Silicon,

when I try to install SwiftGen with `mint` or with `brew` on DTK machine with Apple Silicon on MacOs Big Sur, I have an issue

**Comment by djbe** [comment]
That doesn't really surprise me that there would be at least an issue or 2. Especially via Homebrew or CocoaPods, which use a pre-compiled version for a different architecture.

That it doesn't work using Mint is a surprise though. What error(s) are you getting when using SwiftGen via Mint?

**Comment by amine2233** [comment]
```Bash
🌱 Cloning SwiftGen 6.2.1
🌱 Resolving package
🌱 Building package
[1/10] Compiling writer.c

... SNIP ...

[14/15] Compiling SwiftGen Array+Parallel.swift
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/emitter.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/api.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/parser.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/reader.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/scanner.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /private/var/folders/49/m_t7qv0521dfjz91rwr6l3m40000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/CYaml.build/src/writer.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Undefined symbols for architecture x86_64:
  "_yaml_document_end_event_initialize", referenced from:
      _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in Emitter.swift.o
  "_yaml_document_start_event_initialize", referenced from:
      _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in Emitter.swift.o
  "_yaml_emitter_delete", referenced from:
      _$s4Yams7EmitterCfd in Emitter.swift.o
      _$s4Yams7EmitterCfD in Emitter.swift.o

... SNIP ...
```

**Comment by djbe** [comment]
Allright that looks like a Mint issue. It's forcing compilation with x86_64 instead of whatever arm architecture the DTK uses. You'll need to open an issue there: https://github.com/yonaskolb/Mint/issues

Same actually goes for Homebrew, it needs to add support for ARM architectures (so that they deliver a binary for the right version).

Once those tools support ARM, we can see if we need to change anything in our projects to support it as well. For that, we'll need Xcode 12 which is still in Beta, so that won't be an option until it's released.

**Comment by amine2233** [comment]
ok thanks @djbe, I will open an issue on Mint

**Comment by amine2233** [comment]
I saw SwiftFormat work with `mint` and `Apple Silicon` so it's very strange no ?

**Comment by djbe** [comment]
Curious. I'm not sure what's forcing x86_64 here. Maybe Yams/libYAML?
- Have you tried SwiftLint? They also use Yams.
- Have you tried Sourcery? They also use Yams and Stencil(SwiftKit).

**Comment by amine2233** [comment]
> Curious. I'm not sure what's forcing x86_64 here. Maybe Yams/libYAML?
> 
> * Have you tried SwiftLint? They also use Yams.

SwiftLint works 

> * Have you tried Sourcery? They also use Yams and Stencil(SwiftKit).

I didn't try Sourcery because i don't use this tool,

I create a PR on `Mint`, otherwise when i removed the `x86_64` cmd i solved the issue

**Comment by esteluk** [comment]
This builds fine with mint 0.15 👍

**Comment by djbe** [comment]
Good to hear! For reference's sake, this is the changelog entry from Mint that applies here:
> Support building for architectures other than x86_64 on macOS (Apple Silicon) [#185](https://github.com/yonaskolb/Mint/pull/185)

So update to Mint 0.15.0 or higher.
