### ISSUE TITLE
Strings: support Localization Debugging (handle `NSShowNonLocalizedStrings`)

### ISSUE THREAD

**Issue by lechuckcaptain** [SwiftGen/SwiftGen#754]
It would be nice if that the Strings parser supported the "-NSShowNonLocalizedStrings" "YES" arguments passed for Localization Debugging, showing non-localized strings. Attached you can see where is possible to configure this option for a scheme inside Xcode.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/341895/88642638-076beb00-d0c1-11ea-91fc-50288252ea4b.png">

I also attach a rough proposal about how this should work:

```swift

private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {

    let defaultLocaleIdentifier: String = "en"
    var defaultValue: String = ""

    if let index = ProcessInfo.processInfo.arguments.firstIndex(of: "-NSShowNonLocalizedStrings"),
       ProcessInfo.processInfo.arguments[index + 1] == "YES" {

        if let defaultLanguagePath = Bundle.main.path(forResource: defaultLocaleIdentifier, ofType: "lproj"),
           let defaultLanguageBundle = Bundle(path: defaultLanguagePath) {
            defaultValue = defaultLanguageBundle.localizedString(forKey: key, value: nil, table: table).uppercased()
        }
    }

    let format = BundleToken.bundle.localizedString(forKey: key, value: nil, table: table)
    if format.isEmpty, !defaultValue.isEmpty {
        return String(format: defaultValue, locale: Locale(identifier: defaultLocaleIdentifier), arguments: args)
    } else {
        return String(format: format, locale: Locale.current, arguments: args)
    }
  }
```

- check if the arguments are supplied
- try to load the default language (could be a parameter passed to the parser, default "en")
- uppercase the default value as Xcode does for non localized strings
- use it in case the value cannot be found from the current locale

**Comment by djbe** [comment]
I'm not sure why this code is needed in the first place? Normally Apple's frameworks will handle that parameter automagically and uppercase untranslated content as needed.

Did you try using that flag without the bundle/locale shenanigans posted above? It should just work™.

**Comment by lechuckcaptain** [comment]
You are definitely right, my bad! I misunderstood a strange configuration of a localization where I had all the keys with empty values  https://github.com/Flinesoft/BartyCrouch/issues/196.
