### ISSUE TITLE
Illegal hardware instruction when generating punctuation strings

### ISSUE THREAD

**Issue by zeus-medina-okcupid** [SwiftGen/SwiftGen#755]
Hi all, Swiftgen appears to crash when trying to generate strings that contain only punctuation marks.
This was very tough to track down - basically removing strings in our string file until the codegen completed successfully.
`Fatal error: [1]    46500 illegal hardware instruction`

Steps to reproduce:

1. Have a string in strings file such as `"," = ",";`
2. Run Swiftgen (either via pods or brew installation)
3. Fatal error

Removing the string fixes the issue.
The string shouldn't have been there to begin with - but my script that searches the project for strings picked it up

SwiftGen v6.2.1
XCode 11.5
Targeting iOS 11

**Comment by djbe** [comment]
Quite certain this is an issue in StencilSwiftKit, where we try to format an empty string and go outside bounds. Will have to test it to be 100% sure.

**Comment by djbe** [comment]
Seems to be fixed on latest `develop`.

**Comment by djbe** [comment]
Implemented in SwiftGen 6.5.0, which has been released 🎉
