### ISSUE TITLE
Support System Images

### ISSUE THREAD

**Issue by BastiaanAndriessen** [SwiftGen/SwiftGen#756]
I find myself using more and more SF symbols in my apps. It's nice that these images by default are selectable from IB, but to use them in code I need to pass a string. It would be nice if SwiftGen could provide these through the Asset API.

**Comment by tychop** [comment]
Interesting....

**Comment by tychop** [comment]
Check this: https://diamantidis.github.io/2020/06/28/applescript-to-generate-enum-for-sf-symbols
And this: https://gist.github.com/diamantidis/7dfa8de52aa2f36a3c64ff30a16dd22a#file-3_sfsymbolsv2-swift

Unfortunately, the list is not dynamic, but usable anyway.

**Comment by djbe** [comment]
SwiftGen is meant to parse a resource and generate code based on that. What you needs sounds much more like a dedicated library, especially now that SF Symbols 2 will be arriving soon, with new and renamed symbols.

For this case, I'd recommend something like https://github.com/piknotech/SFSafeSymbols (or other libraries) that can take these details into account.

Note: there is a PR to extract [code points from a font](https://github.com/SwiftGen/SwiftGen/pull/638) (for symbol fonts). But that wouldn't really help in this case, as the mechanism to access these symbols is very different.

**Comment by BastiaanAndriessen** [comment]
Yes, I was also doubting if this kind of functionality would be relevant to SwiftGen but I thought it couldn't hurt just mentioning it. Thanks for the great suggestions!
