### ISSUE TITLE
Generating code plist

### ISSUE THREAD

**Issue by smadbe** [SwiftGen/SwiftGen#76]
Is there any plan (or branch, or PR, or fork) to have a generator for plist files ? In particular, having swiftgen generating a class from the Info.plist so that the keys and their type not "guessed" would be of great help.

**Comment by AliSoftware** [comment]
Hi

I don't think there is any PR on that yet (and not sure how useful it could be given that the Info.plist official keys generally already have matching constants in Foundation, so would only be really useful for custom keys I guess) but feel free to make a PR if you feel it can be useful!

**Comment by AliSoftware** [comment]
I think however having a generic PLIST parser could be more interesting for generating constants for NSUserDefaults from the Settings.bundle/root.plist file 😉

**Comment by smadbe** [comment]
It may be used at different places. But typically, app parameters (enabling or not some features) is the kind of things where it can be useful.

**Comment by AliSoftware** [comment]
Ping @smadbe any idea what it would look like (a sample input Info.plist and what code you expect to be generated for example)? Or even a PR?

**Comment by smadbe** [comment]
`Info.plist` is the file containing all app settings such as the app icon, the device, orientation, etc ... but in addition to this, we have added settings such as the app name, color, ... to be able build two apps (two targets) from the same code but just changing this `Info.plist`. Another example in a file storing the default configuration (NSUserDefaults) values. In both case, it would be nice to be able to get keys from an enum/struct together with their type (bool, int, string, array or dict are supported in plist I think).

Sorry, we haven't implemented it. We would need a parser of these plist files, but it should not be too complicated.

**Comment by AliSoftware** [comment]
Yeah I think I get the idea, but how would SwiftGen then generate the cases/constants only for your *custom* keys in the Info.plist (color, etc…) and not all the other system keys?

**Comment by smadbe** [comment]
The system key can be generated well, we would be still free not to use them. Even, it would prefer use the generated key for the system instead of using the framework key which are not ensured to be present.

**Comment by yonaskolb** [comment]
I would love to have this too. But not specifically just the info.plist file but other plist files.

We use a seperate config.plist file that contains all the custom parameters we use in the app. Versions of these with different values can be loaded and switched out at runtime. Having a generated Config Struct with all typed values would be very useful. Because this is loaded at runtime the struct wouldn't actually hardcode the values but be initialised with a path that sets it's values which can then be accessed

**Comment by ealeksandrov** [comment]
@yonaskolb found this issue while searching for similar idea. I'm using this for now: https://github.com/theappbusiness/ConfigGenerator.


I see https://github.com/SwiftGen/SwiftGen/pull/288 is right about plist parsing, so adding comment to link between issue and PR.

**Comment by djbe** [comment]
The plist command has been added with #379, which will be released in 6.0. There are even some default templates that generate files to access the contents (inline or at runtime), but you can always write your own custom template if you want to deviate from this.
