### ISSUE TITLE
.stringsdict only supports single integer argument

### ISSUE THREAD

**Issue by garyhooper** [SwiftGen/SwiftGen#780]
I am struggling to have the new stringsdict functionality work for anything other than a single integer. Examples that are failing:

1. `%@: %#@value@` generates a func with a single `Int` argument. There should be two arguments, `String` and `Int`, even with a single `NSStringPluralRuleType` defined.
2. Defining `NSStringFormatValueTypeKey` to be `f` generates a func with a single `Int` argument. It should be a `Double`.
3. Only `%d` in the format of `one` or `other` works. `%g` fails, since only a single argument of `Int` exists.

(The simple example of an `Int` defined using `%d` in `one` or `other` works.)

**Comment by garyhooper** [comment]
Well, these was most definitely my issue, as I neglected to add the .stringsdict file to the Build Phase Input Files dependency.

**Comment by djbe** [comment]
Glad to hear you were able to solve your issue @garyhooper.

You may be interested in the `config generate-xcfilelist` command we're adding in the next version (6.4.0), which you can use to generate the input (and output) dependency file lists. #441
