### ISSUE TITLE
SPM minor fix

### ISSUE THREAD

**Issue by chilimovpasha** [SwiftGen/SwiftGen#784]
Could you please fix the problem below?

<img width="1254" alt="Screenshot 2020-10-03 at 22 14 09" src="https://user-images.githubusercontent.com/9354461/94999981-d11d8100-05c5-11eb-9fba-c41630113c86.png">

**Comment by djbe** [comment]
We do not support SPM yet, see our [installation instructions](https://github.com/SwiftGen/SwiftGen#installation). We support installation via CocoaPods, Homebrew, Mint and some manual options (ZIP & compile from source).

**Comment by djbe** [comment]
To clarify a bit: it seems you want to add SwiftGen to your project using SPM, which currently does not support "tooling" dependencies such as SwiftLint, SwiftGen, Sourcery, SwiftFormat, etc... With that I mean anything that you use during development, but isn't actually part of your codebase.

SwiftGen is meant to, using a configuration, parse a set of resources and generate a bunch of Swift code. That generated Swift code should then be added to your project.

**Comment by chilimovpasha** [comment]
I understand, ok then. Thanks for clarifying)
