### ISSUE TITLE
Exclude Storyboards and Strings based on preprocessor flags

### ISSUE THREAD

**Issue by kacper1703** [SwiftGen/SwiftGen#795]
Hello, I would like to be able to filter out Storyboards and Strings that match a regex that preferrably could be included in the .yml file as a parameter. I am familiar enough with the stencils to be able to modify them myself, I just don't know how to apply this filter.

My use case is that I have features that cannot be on release (production) app versions, and if I exclude a file from the release configuration I get a compiler error in the Storyboards.swift file:

```swift
#if DEBUG || BETA
class SecretViewController: UIViewController {
...
}
#endif
```
When building in production configuration:
```swift
  internal enum SecretStoryboard: StoryboardType {
    internal static let storyboardName = "SecretStoryboard"

    internal static let initialScene = InitialSceneType<SecretViewController>(storyboard: SecretStoryboard.self) //cannot find SecretViewController in scope
  }
```

I would like to be able to pass a regex to exclude files beginning or ending with `Secret` to not be included in the code generation. Also, I guess I would have to have two different stencils for production and non-production.

**Comment by djbe** [comment]
You might be better off modifying your configuration file to generate 2 outputs:
- One pointing at normal storyboards, and generating `normal-ib-scenes.swift`
- Another pointing at both normal and secret storyboard files, and generating a `normal+secret-ib-scenes.swift`

Then include the correct swift file in the correct target.

That or a custom template, if all your secret scenes contain the word "secret", you can just filter them out (or add a `#if` wrapper around it) using `contains("secret")` in Stencil: https://github.com/SwiftGen/StencilSwiftKit/blob/stable/Documentation/filters-strings.md#filter-contains

To clarify: this is not a feature we will add in the built-in templates, as the use case is waaaay too specific to your situation.

**Comment by kacper1703** [comment]
Thank you for the quick answer! I will try that tomorrow and let you know of the results.

**Comment by kacper1703** [comment]
hi @djbe, the `contains` (as well as `hasPrefix`) keyword does not seem to work for me. I did the following modification of the stencil:
```
{{accessModifier}} enum {{param.enumName|default:"StoryboardScene"}} {
  {% for storyboard in storyboards %}
  {% set storyboardName %}{{storyboard.name|swiftIdentifier:"pretty"|escapeReservedKeywords}}{% endset %}
  {% set isSecretStoryboard %}{% if storyboardName.contains("Start") %}true{% endif %}{% endset %}
  {% if isSecretStoryboard %}
  #if DEBUG || BETA
  {% endif %}
  {{accessModifier}} enum {{storyboardName}}: StoryboardType {
    {{accessModifier}} static let storyboardName = "{{storyboard.name}}"
    {% if storyboard.initialScene %}

    {% set sceneClass %}{% call className storyboard.initialScene %}{% endset %}
    {{accessModifier}} static let initialScene = InitialSceneType<{{sceneClass}}>(storyboard: {{storyboardName}}.self)
    {% endif %}
    {% for scene in storyboard.scenes %}

    {% set sceneID %}{{scene.identifier|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}}{% endset %}
    {% set sceneClass %}{% call className scene %}{% endset %}
    {{accessModifier}} static let {{sceneID}} = SceneType<{{sceneClass}}>(storyboard: {{storyboardName}}.self, identifier: "{{scene.identifier}}")
    {% endfor %}
  }
  {% if isSecretStoryboard %}
  #endif
  {% endif %}
  {% endfor %}
}
```

Which still outputs 
```swift
  internal enum Start: StoryboardType {
    internal static let storyboardName = "Start"
    
    internal static let initialScene = InitialSceneType<WelcomeScreenViewController>(storyboard: Start.self) //error: Cannot find type 'WelcomeScreenViewController' in scope
  }
```

Swapping `storyboardName.contains("Start")` to `storyboardName == "Start"` results in proper output:
```swift
  #if DEBUG || BETA
  internal enum Start: StoryboardType {
    internal static let storyboardName = "Start"
    ...
  }
  #endif
```

I'm using SwiftGen version 6.4.0, CocoaPods 1.10.0.beta.2.

**Comment by djbe** [comment]
Could you try this tweak?
```
{% set isSecretStoryboard %}{% if storyboardName.contains("Start") %}true{% else %}{% endif %}{% endset %}
  {% if isSecretStoryboard == "true" %}
```

**Comment by kacper1703** [comment]
No, still doesn't work :( 
Using `{% if isSecretStoryboard == true %}` as well.

If that helps, in my config file I have:
```yaml
ib:
  inputs: Screens/
  outputs:
    templatePath: Project/Resources/SwiftGen Templates/swiftGenStoryboards.stencil
    output: Storyboards.swift
    params:
        ignoreTargetModule: true
```

**Comment by kacper1703** [comment]
seems like `contains` and `hasPrefix` and `hasSuffix` do not return any value (a `null`?).
Stencil code:
```
// Value of check1: {{ "SecretDemo".hasSuffix("Demo") }} (should be true)
// Value of check2: {{ "SecretDemo".hasPrefix("Secret") }} (should be true)
// Value of check3: {{ "SecretDemo".contains("cret") }} (should be true)
// Value of check4: {{ "SecretDemo".hasSuffix("abc") }} (should be false)
```
results in swift file:
```
// Value of check1:  (should be true)
// Value of check2:  (should be true)
// Value of check3:  (should be true)
// Value of check4:  (should be false)
```

**Comment by kacper1703** [comment]
Hi @djbe, could you help me out here please? The deadline for having this in the project is close. 

Is this a syntax mistake or some internal bug?

**Comment by djbe** [comment]
Hey sorry forgot about this between other stuff 😅 

So, I tested this locally, and the filters work. The thing is that I didn't pay attention to the syntax that you and I were using! In Stencil, in order to invoke a filter you need to use `stuff|myFilter:"foo"`. The filter returns a boolean, so make sure you use it in an `if`. Stencil doesn't automatically convert it to the text "true", and variables set using `set` (used like above) are always strings.

So in your use case, that would be:
```
{% set isSecretStoryboard %}{% if storyboard.name|contains:"Start" %}true{% endif %}{% endset %}
{% if isSecretStoryboard %}
#if DEBUG || BETA
{% endif %}
```

**Comment by kacper1703** [comment]
Ahhh this is why! 😄 Thank you, now it all works as needed.
