### ISSUE TITLE
How does one effectively use the new xcfilelist generator in 6.4?

### ISSUE THREAD

**Issue by garyhooper** [SwiftGen/SwiftGen#796]
Starting in 6.4, I have two SwiftGen pre-compile build-phase commands. The first only generates the input and output xcfilelist files; the second runs SwiftGen using inputs.xcfilelist and outputs.xcfilelist as filelist dependencies.

However, a build in a clean environment always fails, as inputs.xcfilelist and outputs.xcfilelist do not exist when the build dependency tree is created. That is:

```
Unable to load contents of file list: '/Users/gary/.../swiftgen-input-files.xcfilelist'
Unable to load contents of file list: '/Users/gary/.../swiftgen-output-files.xcfilelist'
```
What is the best way to effectively incorporate this new feature into one's build environment?

**Comment by djbe** [comment]
Unfortunately the file lists **must not** be generated as part of the build process of your target. You can read through the discussion on this topic in the [original issue (#441)](https://github.com/SwiftGen/SwiftGen/issues/441).

One of the options mentioned there is using a "Pre-Action" of the "Build" action in your scheme. Another option **might** be to have a separate target you depend on, whose only purpose is generating those filelists. 

Note that these options are untested (so far).

**Comment by djbe** [comment]
@garyhooper I assume you were able to solve your issue? Might be good to post whatever you went with for future reference.
