### ISSUE TITLE
Fonts: iOS system fonts support

### ISSUE THREAD

**Issue by winstondu** [SwiftGen/SwiftGen#803]
Since iOS 13, phones have a significant number of pre-installed fonts (see: https://developer.apple.com/fonts/system-fonts/)

Is there a correct method of going about getting the swift-gen classes of these fonts?

Currently, I just have these fonts downloaded just for swift-gen to call them.

**Comment by djbe** [comment]
This question is a bit similar to the SF Symbols support issue (#640). Similar to #640, there are no "resources" for SwiftGen to parse in this case.

For these kind of cases, we highly recommend using some sort of micro-framework that does better handling of platform (iOS, macOS, ...) and version (iOS 13, iOS 14, ...) differences.
