### ISSUE TITLE
.gitignore Support

### ISSUE THREAD

**Issue by fishcharlie** [SwiftGen/SwiftGen#807]
Most of the time generated files (like those that SwiftGen generate) should be included within your `.gitignore` file. This is to help with merge conflicts and other issues that can arise from source control with generated files.

However when I added the `Generated` folder to the `.gitignore`, we ran into a few problems:

1. The SwiftGen script fails when that `Generated` directory is missing.
2. The SwiftGen script does not run every time we build (for incremental builds for example).
3. Unclear at this point if SwiftGen will add the generated files to the project automatically for building in this case (since before we had them in the project and didn't have to worry about doing that on the fly).

**Comment by djbe** [comment]
I personally disagree with `gitignore`-ing generated files, I like to commit them so I can keep track of changes, but to each their own 🤷 

1. Add a `.gitkeep` file in the directory, that way it'll stay in your repo.
2. Make sure you correctly configure your build step (use the input/output file list command to help you with this). Also, this is more of an Xcode issue or a your project issue. Do note that the build "log" of Xcode doesn't always represent what it **actually** does, it oftentimes caches the output of build steps.
3. Not sure if I understand this. Do you want SwiftGen to commit files to your repo? That outside the scope of this project.

**Comment by fishcharlie** [comment]
@djbe Got it. I agree with that being a huge benefit. For this project specifically, I think that benefit isn't strong enough to warrant the drawbacks.

That is super helpful!

Getting an error about `Build input files cannot be found` on first build. But the files are generated, and on the next builds it works fine. Kinda seems like my build phase is messed up or something. Not sure if you have any ideas off the top of your head as to why that'd be occurring.

**Comment by djbe** [comment]
Note: you should put the generated files as **output files** of the SwiftGen phase. As input, you should provide the list of assets.

About that error: no idea, seems more like an Xcode quirk?

**Comment by fishcharlie** [comment]
@djbe Thanks for your help! Really appreciate it. I'll look more into this when I get a chance.
