### ISSUE TITLE
PathKit version dependency

### ISSUE THREAD

**Issue by deepumukundan** [SwiftGen/SwiftGen#819]
We have a project which has both SwiftGen and Apollo. Both are on older versions and managed via Cocoapods (SwiftGen) and Carthage (Apollo) for legacy reasons. I am trying to move everything under Swift Package Manager and update versions while doing so. But was getting the error below in SPM dependency resolution

`because Stencil 0.14.0 depends on PathKit 1.0.0..<2.0.0 and no versions of Stencil match the requirement 0.14.1..<0.15.0, Stencil >=0.14.0 requires PathKit 1.0.0..<2.0.0.
And because SwiftGen >=6.0.0 depends on PathKit 0.9.0..<1.0.0, SwiftGen is incompatible with Stencil.
And because apollo-ios 0.40.0 depends on Stencil 0.14.0..<0.15.0 and no versions of apollo-ios match the requirement 0.40.1..<0.41.0, SwiftGen is incompatible with apollo-ios.
And because root depends on apollo-ios 0.40.0..<0.41.0 and root depends on SwiftGen 6.3.0, version solving failed.`

I noticed that SwiftGen's dependency on PathKit is from on older version
https://github.com/SwiftGen/SwiftGen/blob/0c67b63f43814a8d7eb71f685f0bf504b03223f3/Package.swift#L12

PathKit 1.0 drops support for Swift < 4.2, so updating SwiftGen to use a higher version of PathKit (i.e. 1.0) will mean SwiftGen will also drop support for Swift 4.2. Is this ok? If so I can create a PR to update this dependency and resolve the above issue with Apollo.

#### Environment
Xcode 12.4
Swift 5.3.2
Using SPM to fetch Swiftgen 6.3.0 and Apollo 0.4.0

**Comment by deepumukundan** [comment]
Was able to fork and change some versions for SwiftGen to be integrated into a project. But then stumbled on another issue - Looks like SwiftGen is only supported for macOS targets right now. The swiftgen binary was unable to be added in as a dependency. 
![Screen Shot 2021-01-28 at 4 57 07 PM](https://user-images.githubusercontent.com/1459484/106217654-8cc47b00-618a-11eb-8391-fc21abaa89de.png)

Further, when I compiled the trial project (with only SwiftGenKit added), was getting 
`AppKit is not available when building for iOS Simulator. Consider using `#if !os(iOS)` to conditionally import this framework.`.

Is SPM integration for iOS projects in the works? If so I can wait for the release that makes this available.

**Comment by deepumukundan** [comment]
Alright. Found that [some ground work](https://github.com/SwiftGen/SwiftGen/pull/793) was done. But seems to be in limbo since Oct 2020. Any way we can push that through? @djbe

**Comment by kompw** [comment]
Hi! Created new project, added SwiftGen from spm. I see blocked error: "AppKit is not available when building for iOS Simulator. Consider using `#if !os(iOS)` to conditionally import this framework."
Xcode Version 12.4

It would be fine if we fixed this issue Asap!

**Comment by djbe** [comment]
@deepumukundan @kompw you shouldn't add SwiftGen using SPM like that. You don't want/need to compile it into your codebase. You need to install it so that it **generates** code, which you then add to your codebase. Please read the (pretty extensive) [ReadMe](https://github.com/SwiftGen/SwiftGen) for more information.

SPM (for now) **does not** support "tooling" dependencies. For more information on what you can achieve right now, please check #689. @deepumukundan the issue you linked (#793) is (essentially) unrelated, it's an internal issue to change how we compile SwiftGen itself.
