### ISSUE TITLE
objc-h template should use documentation comments

### ISSUE THREAD

**Issue by szotp** [SwiftGen/SwiftGen#821]
I wanted to create PR with this change but contribution guide told me not to.

I think [this](https://github.com/SwiftGen/SwiftGen/blob/stable/templates/strings/objc-h.stencil#L40) line needs to be changed to generate documentation comment instead of regular comments. This way you can easily see key and base value for each property.

**Comment by djbe** [comment]
What are doc-comments in obj-c? Triple slash like in Swift?

Go ahead and make a PR for it once you've tested it. Make sure to also update the generated output (use the helper scheme for that), and add a changelog entry.

**Comment by szotp** [comment]
Yeah it's ///, thanks for response, I will make PR then...

**Comment by djbe** [comment]
Implemented in SwiftGen 6.5.0, which has been released 🎉
