### ISSUE TITLE
Support silent mode

### ISSUE THREAD

**Issue by thii** [SwiftGen/SwiftGen#823]
It looks like there's currently no way to suppress the `File written: /path/to/file.swift` output. It would be nice to have this supported, and only print out log like this in the verbose mode.

**Comment by tinder-maxwellelliott** [comment]
This would be really nice to have, no need to see `File Written:....` hundreds of times in a log.

**Comment by Andre113** [comment]
I created a PR for it. Accepting suggestions to improve it.
https://github.com/SwiftGen/SwiftGen/pull/846

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
