### ISSUE TITLE
Add instructions on installing via SPM

### ISSUE THREAD

**Issue by ptrkstr** [SwiftGen/SwiftGen#824]
I've noticed that there is now a package.swift added to the project indicating that it's installable via SPM.
However I didn't see any instructions.
SwiftFormat contains instructions that could be duplicated.
https://github.com/nicklockwood/SwiftFormat#using-swift-package-manager

**Comment by djbe** [comment]
The thing is that SPM doesn't really support "build tools", as can clearly be seen from the link in your post.

There is a proposal on Swift Evolution about build tools: [SE-0303](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md). Once that is merged, we WILL add support for it, and add the necessary instructions.

**Comment by ptrkstr** [comment]
It may not be the ideal way to integrate it but it does work without any issues. My concern is that until that proposal makes it to release, users may either not use swiftgen or use another dependency manager to integrate it when it isn't necessary.

**Comment by djbe** [comment]
Thing is, we **have** installation instructions for Mint, which is why we added the Package.swift a while ago. And that will remain the installation instructions using "SPM" (kinda) until SPM itself actually supports build tools.

**Comment by ptrkstr** [comment]
Understood @djbe, shall close the issue.
