### ISSUE TITLE
Make output file scoped to Public?

### ISSUE THREAD

**Issue by zakkhoyt** [SwiftGen/SwiftGen#837]
I am using SwiftGen to manage Colors in an Asset catalog in a Framework. I'd like to expose those colors in the public scope. 

In other words, I'd like the swiftgen output file to say 
```
public enum Asset {
  public enum Color {
    public enum Font {
      public static let body = ColorAsset(name: "Color/Font/body")
        ...
    }
  }
}
```
instead of 
```
internal enum Asset {
  internal enum Color {
    internal enum Font {
      internal static let body = ColorAsset(name: "Color/Font/body")
        ...
    }
  }
}
```

I didn't notice a way to do this in the config file documentation. It's possible that I have overlooked it.

**Comment by djbe** [comment]
Check this discussion about exactly the same thing:
https://github.com/SwiftGen/SwiftGen/discussions/833

Essentially: update your configuration to set a template variable for public access.

**Comment by zakkhoyt** [comment]
Great. I appreciate the reply.
