### ISSUE TITLE
Please include colorset color `components` info in xcasset parser

### ISSUE THREAD

**Issue by gchiacchio** [SwiftGen/SwiftGen#847]
Would be useful to have colorset data parsed, in particular for creating comments. 
Color components in comments are very useful to quickly recognize which constant name matches a design value (rgba or hex), otherwise I'd need to go to the catalog and keep looking at each color definition to find the name.
If the parser includes the info, we could create some custom template in order to include as much info as needed (dark value, light value, etc)

**Comment by djbe** [comment]
Asset catalog colors can be completely different colors depending on multiple traits, such as:
- appearance (light/dark mode + high contrast mode)
- device category (ipad/iphone/tv/...)
- gamut (srgb / p3)
- ...

So colors do not have 1 color of which we can parse the components. We'd have to parse the color for each variant, and you'd have to handle all of those. Same thing for images, data assets, etc...

**Comment by gchiacchio** [comment]
Would it be possible to just include some "metadata" dictionary, which we could handle in the template as needed? In any case, the parser is returning the basic info for creating the constants, but having metadata available would be useful ,and is up to the dev if wanted to make the custom template more or less complex.

**Comment by djbe** [comment]
Like I said, this would imply we'd have to load **all** data, such as **all** colors for colors. There's no in-between solution. Then you'd also have to somehow handle multiple colorspaces, because it could be hex, it could be RGBA, it could be HSBA, ...

TBH there's not many people who've asked for this, and it would make the parser slower for everyone.

**Comment by gchiacchio** [comment]
If I'm not wrong, the parser is already loading all metadata in order to see if `"provides-namespace"` is set. The thing is it's not passing those values to the template.  https://github.com/SwiftGen/SwiftGen/blob/stable/Sources/SwiftGenKit/Parsers/AssetsCatalog/CatalogEntry.swift#L114

Note I'm not asking to parse and map everything into static types, but just passing the complete dictionary if possible (not sure how the mapping between swift dict/stencil works).
Maybe a parameter would make more sense, so the dev can decide if wants it all or not.

**Comment by djbe** [comment]
It's only loaded for groups (folders). A color asset looks like this:

```json
{
  "info" : {
    "version" : 1,
    "author" : "xcode"
  },
  "colors" : [
    {
      "idiom" : "universal",
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "red" : "0xFF",
          "alpha" : "1.000",
          "blue" : "0xFF",
          "green" : "0xFF"
        }
      }
    },
    {
      "idiom" : "universal",
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "red" : "0.039",
          "alpha" : "1.000",
          "blue" : "0.040",
          "green" : "0.039"
        }
      }
    }
  ]
}
```

As you can see, some of those are floats, other are hex values, etc... Not sure if you know this, but Stencil templates can't deal with this (converting values and such), it's very very limited. So you'll only be able to use those values as is. Sure, we "could" define a whole bunch of filters in Stencil, but that'll get very complex very quickly...

So again, I'm pretty sure it'll end up being quite useless unless processed, which comes back to performance degradation for most users.

**Comment by gchiacchio** [comment]
> Not sure if you know this, but Stencil templates can't deal with this (converting values and such), it's very very limited.

Nothing else to add here... please disregard my request. Asked just in case it was easy to pass the metadata (some kind of automatic conversion between swift/stencil basic types), which is not the case.

Thanks for taking the time to explain!

**Comment by djbe** [comment]
At some point I want to add support for other template languages, such as Swift, but that's definitely something that's not in the near future 😅 

We can revisit this and many other features once we get there.

**Comment by mYoda** [comment]
> As you can see, some of those are floats, other are hex values, etc..

Actually, if you will set Hexademical in the "Input Methods" for all Colors in the Catalog, you will get the HEX data in the Contents.json file... anyway pass that object with all parameters to the template - is a very good idea. Our templates will be more flexible.

![2021-08-05_23-53-15](https://user-images.githubusercontent.com/5484180/128420276-c1d35c38-a3e3-436b-8f61-ad3234ffa5ff.png)

**Comment by djbe** [comment]
But this isn't always the case... For SwiftGen we need to handle ALL cases, no matter what the user has as data.

**Comment by mYoda** [comment]
Sure, but you already decided to cut data... why? I am a user and I need this. SwiftGen is an amazing tool! We all in our company love it!
But I think some adjustments will be very useful for us. I think if there is some data - lets users will decide how to use it. I think the parser should just pass that data... like `asset.color.components.alpha` or by some other way.

in my case, I need a marked comment that will appear in the suggestions list while typing a name of that color in the Code Editor. you are already doing this with Strings as example... So I love that!
