### ISSUE TITLE
SF Symbols / symbolset release date

### ISSUE THREAD

**Issue by ton252** [SwiftGen/SwiftGen#855]
I saw that the symbolset pull request is already in dev. When will it go public?

**Comment by djbe** [comment]
Please do not open issues like these, they don't add anything. If you have questions about the symbolset feature / implementation, you can ask it in the original issue: #767

If you want to try testing the latest development version of SwiftGen, you can do so using Homebrew or Mint. An actual release will be made at some point, but I won't promise when 🤷
