### ISSUE TITLE
Enhancement, specify configuration file

### ISSUE THREAD

**Issue by marcbaldwin** [SwiftGen/SwiftGen#869]
Thanks for building such a great tool!

I'd love to be able to specify the config file to use so that I can use this on a multi-project workspace.
In my case I have assets in different projects but currently I can only generate an `Assets.swift` for one of those projects. I'd be willing to help build this feature if you could point me in the right direction.

Many thanks!

**Comment by kuopenx** [comment]
Hi, Currently I've generated multiple Asset.swift files for multiple folders using swiftgen through cocoapods, but you need to set different parameters for different output in case their enumNames conflict. The [documentation](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md#swiftgen-configuration-file) demonstrates how to specify the path of configuration-file and how to specify multiple inputs-outputs for one parser, for instance, xcassets.

**Comment by kuopenx** [comment]
> Thanks for building such a great tool!
> 
> I'd love to be able to specify the config file to use so that I can use this on a multi-project workspace.
> In my case I have assets in different projects but currently I can only generate an `Assets.swift` for one of those projects. I'd be willing to help build this feature if you could point me in the right direction.
> 
> Many thanks!

Hi, Currently I've generated multiple Asset.swift files for multiple folders using swiftgen through cocoapods, but you need to set different parameters for different output in case their enumNames conflict. The [documentation](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/ConfigFile.md#swiftgen-configuration-file) demonstrates how to specify the path of configuration-file and how to specify multiple inputs-outputs for one parser, for instance, xcassets.

**Comment by djbe** [comment]
You have a few choices here, mainly:
- Have 2 separate config files, and point SwiftGen at each with `swiftgen config run --config=path/to/config.yml` (once for each target)
- Create a single config that generates multiple outputs, one for each target (per parser). This is @kuopenx's suggestion.

The advantage of the latter is that if you have an overlap of resources, then SwiftGen will only need to parse them once. The former is useful if you want to ensure the targets are completely separate.

**Comment by djbe** [comment]
Unless there are any issues, I'm going to close this.

Small tip: for questions & general discussion, it might be best to use the "Discussions" feature of GitHub, that way you can mark answers as your solution, and should remain visible to others once closed.

**Comment by marcbaldwin** [comment]
Thanks for the solutions, they worked great!
