### ISSUE TITLE
Make SwiftGenCLI useable from other tools

### ISSUE THREAD

**Issue by doozMen** [SwiftGen/SwiftGen#871]
It would be nice if I code use the `Config(path: ...)` and then just do `confing.run(...` inside my other swift code. This is not possible at the moment. For this to be possible config should move to `SwiftGenKit`. Is this something you would consider doing?

**Comment by doozMen** [comment]
[swiftformat](https://github.com/nicklockwood/SwiftFormat) does this so I can run it as a library from within my code

**Comment by djbe** [comment]
The config related code now lives in the SwiftGenCLI target, is that something that would help your use-case?

Note: SwiftGenKit itself is just for the parsers and contexts, it has nothing to do with handling configurations or user commands.

**Comment by doozMen** [comment]
I would like to configure a command in another cli tool. Not too complicated. This is now not possible. The `SwiftGenCLI` target is an `executable` if I am not mistaken. So this I cannot import in other swift code. It would have to be a lib. So everything that is not `main.swift` should be in a lib and and I would do the things you do from `main.swift` in my swift code. I Could make a PR if that helps?

**Comment by djbe** [comment]
Have you looked at the Package.swift? The only executable is `swiftgen`, which depends on `SwiftGenCLI` which is a framework (+ resource bundle).

It doesn't do much though, and we provide 0 support about changes in that library. It is meant for internal use, there's no public documentation about it, etc... Honestly, if I were you, I'd invoke SGK's `Parser`s and Stencil directly instead of using our `Config`s and `Command`s, but up to you 🤷

**Comment by doozMen** [comment]
It is meant to run on a cli. The CLI runs clean so if I have to build my swift tool, from cache if needed, and swiftgen. If I include it in my code I can write type safe swift code and it is only 1 executable that needs to be build. I will have a look at SwiftGenCLI if it is what I need.

**Comment by djbe** [comment]
@doozMen have you tried the new framework?

**Comment by doozMen** [comment]
No sorry not yet but I see you moved a lot thanks. Sorry was off for 2 weeks due to new born baby 🧑🏼‍🍼.

**Comment by djbe** [comment]
I'm going to close this issue for now, as I think it should be solved with the 6.5.1 release. As I mentioned before, the framework should be available to use using SPM (but 0 support as it's meant for internal use). If the issue remains, please reopen this ticket.

Side note: congrats on the new baby, hope all's going well.
