### ISSUE TITLE
Strings: `tr` mangles multi byte space

### ISSUE THREAD

**Issue by champo** [SwiftGen/SwiftGen#872]
I'm having an issue with the Portuguese thounsands separator character, which seems to be a multi byte space. When I use it as an argument for a string with formating, the separator comes out mangled on the other side. 

This small tests mimicking the tr structure reproduces the issue:
```
    func testEncoding() {
        func tr(_ args: CVarArg...) -> String {
            return String(format: "%s", locale: Locale.current, arguments: args)
        }
        func myTr(_ s1: UnsafePointer<CChar>) -> String {
            return tr(s1)
        }
        let str = "24 735,24"
        // myTr produces 24¬†735,24
        XCTAssertEqual(myTr(str), str)
    }
```

`String(format: "%s", locale: Locale.current, arguments: "24 735,24")` does the right thing and so does `String(cString: s1)`. Not sure what's being lost in `String(format: locale: arguments:)`

## Env

* SwiftGen v6.4.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.4.0)
* XCode Version 12.5 (12E262)
* iOS 14.5

**Comment by djbe** [comment]
Why are you using `%s` instead of `%@`? I think the conversion to `CChar` is somehow breaking a bunch of stuff.

**Comment by champo** [comment]
TBH I'm not sure why! I thought the `%@` was an Obj-C thing I guesss. Using `%@` fixes the issue.
