### ISSUE TITLE
 unable to run 6.4 version or any other due to permission issue

### ISSUE THREAD

**Issue by sreexamus** [SwiftGen/SwiftGen#876]
Unable to run the library as it is being blocked with permissions. Even after allowing the permissions from security settings its again and again asking the permissions from different libraries in the SDK.

**Comment by djbe** [comment]
How did you install SwiftGen? Did you follow the [recommended installation instructions](https://github.com/SwiftGen/SwiftGen#installation) in our readme file?

**Comment by djbe** [comment]
If you downloaded SwiftGen from Github (as a zip), and did not install it via CocoaPods, Mint, Homebrew, or any other method, then the executable will be marked by macOS as in quarantine.

If that is the case, you can right-click on the binary and click on open. MacOS will ask you if you're sure, but after doing this once the quarantine flag will be cleared. You can also do this in your Terminal, using:
```bash
xattr -r -d com.apple.quarantine path/to/swiftgen
```

**Comment by djbe** [comment]
I'm going to assume this was your issue and that my suggestions should fix it. If the issue remains, feel free to reopen this issue.
