### ISSUE TITLE
Do template stencil files exist anymore in the source of the project?

### ISSUE THREAD

**Issue by razor313** [SwiftGen/SwiftGen#888]
After I've updated the SwiftGen to the latest version, the template `.stencil` files are no longer in the source of the project. I've changed it to the following code but after the output file (Fonts.generated.swift) has been generated I got a bunch of errors on the output file!

> fonts:
  inputs: Fonts
  outputs:
    templatePath: .build/checkouts/SwiftGen/Documentation/templates/fonts/swift5.stencil
    output: Fonts.generated.swift
    
The previous path was:
>  templatePath: .build/checkouts/SwiftGen/templates/fonts/swift5.stencil

Now, I'd like to learn how can I use them as the previous path?

**Comment by djbe** [comment]
How are you using SwiftGen (as in, how did you install it)? Did you manually compile it?

Note: if you want to use the built-in templates, you should NOT use `templatePath`, but instead use `templateName`! In your case that'd be `swift5` as a value for it.

**Comment by razor313** [comment]
@djbe I've installed it via SPM that I've sent PR #841 for it in order to add this manner of installing.
Therefore I must use `templatePath` rather than `templateName`. Also, It was working before I've updated to the latest version! It seems all template `.stencil` files have been removed from the source of the project!

**Comment by djbe** [comment]
First & foremost: installation via SPM is not supported yet, so we don't test it and it could break between releases. Always keep that in mind 😉 If you want something like SPM, Mint works quite well.

Since #824 was created, we've released SwiftGen 6.5.0, which now fully builds with SPM. It now uses resource bundles (using SPM), so your workaround with `templatePath` shouldn't be needed anymore.

**Comment by razor313** [comment]
@djbe As you mentioned I've used `templateName` rather than `tamplatePath` and it works like a charm.
Thank you very much.
