### ISSUE TITLE
Not able to install SwiftGen using Homebrew

### ISSUE THREAD

**Issue by anilkb007** [SwiftGen/SwiftGen#889]
Not able to install swiftgen using Homebrew always getting this message

 % brew install swiftgen
Warning: No available formula or cask with the name "swiftgen".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
  % 

Please let me know how to install it on Mac OS Big Sur 11.4

**Comment by djbe** [comment]
Sounds more like an Homebrew issue?
```bash
❯ brew search swiftgen
==> Formulae
swiftgen ✔ 
```

**Comment by anilkb007** [comment]
Hi @djbe When I tried the same from my end I am getting the below, any tips would be helpful. 

brew search swiftgen
Error: No formulae or casks found for "swiftgen". 

I am using the latest Homebrew version
brew -v
Homebrew 3.2.16-37-gfecacdc
Homebrew/homebrew-core (git revision fecacdce49; last commit 2021-10-16)
Homebrew/homebrew-cask (git revision 8e7e7af9c0; last commit 2021-10-17)

**Comment by anilkb007** [comment]
hi @djbe yes you are right its problem with my Homebrew. I found My Homebrew core was not tapped properly when I run 

brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core was not tapped properly! Run:
 rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
 brew tap homebrew/core

Running the above command and 
then trying to install swiftgen worked fine.

Thanks for the tip

**Comment by djbe** [comment]
Glad to see the issue was solved 🎉
