### ISSUE TITLE
Multi plist error

### ISSUE THREAD

**Issue by JalalNajafi** [SwiftGen/SwiftGen#906]
in our project, we going to make project base on swiftgen and when it make i face with error of multi plist and i have to select the plist and deselect from target and after that, it work.
how can isolve this issue 
every time that make the project it should be deselected info.plist from target membership

**Comment by djbe** [comment]
The error sounds like it's from Xcode itself? That has nothing to do with SwiftGen

**Comment by djbe** [comment]
What's the output of running SwiftGen from terminal, for example (assuming it's installed using cocoapods):
`./Pods/SwiftGen/bin/swiftgen config run`

**Comment by JalalNajafi** [comment]
no, the output make the project and framework 
we use this
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
 when the project run and prepared in build face with multi info plist
for that we have to manually exclude the plist from target membership
is there any way to xclude the plist file from target membership

**Comment by djbe** [comment]
That's an XcodeGen question then.

Again, what's the output of running SwiftGen itself? Does that give errors? We definitely need more information than "there's a plist error".

**Comment by JalalNajafi** [comment]
for example i have three framework in app and each of that has plist when the project make and after that build it saye multi plist

https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce

and the plist added to the copy bundle resources
when i remove from target member ship it build but every time we make the xcodeGen and project and after that build it happen

can we have call

**Comment by djbe** [comment]
Again, that's an XCODEgen issue, not a SWIFTgen issue, a completely different project. For issues with XcodeGen, go here: https://github.com/yonaskolb/XcodeGen

**Comment by JalalNajafi** [comment]
thank you sorry yes thank you can you close and delte tghis thread
