### ISSUE TITLE
Playground won't live-view; error "no --inputencoding specified and could not detect encoding from input file"

### ISSUE THREAD

**Issue by SaganRitual** [SwiftGen/SwiftGen#909]
My apologies if this is not the best of bug reports. There's so much going on here that is totally unfamiliar to me, I'm not sure what to leave in or out.

The basic problem, I guess, is that when I run the playground, nothing happens. I can't even get a live preview. I'm guessing it's related to the error message.
<img width="1079" alt="Screen Shot 2021-12-19 at 14 03 50" src="https://user-images.githubusercontent.com/2438449/146692471-f051e37c-3342-46b7-8eb1-b37a56b62970.png">
- Swiftgen version: SwiftGen v6.5.1 (Stencil v0.14.1, StencilSwiftKit v2.8.0, SwiftGenKit v6.5.1)
- Version of Xcode: Version 13.2.1 (13C100)
- Target OS: tricky, I'm trying to use your playground project, and can't for the life of me figure out how to change the target to see if the error happens with different targets. This is despite doing a lot of googling and finding nothing, and some wild guesses like "Product->Scheme->Choose scheme" and getting ZERO response from Xcode (I've used Xcode for years, so I'm not surprised by this behavior, even a little). So you're stuck with the target that the playground has chosen: "iPad Pro (9.7-inch)"
- <img width="632" alt="Screen Shot 2021-12-19 at 13 39 36" src="https://user-images.githubusercontent.com/2438449/146691745-d2b449c6-0cc8-40b8-8552-d2c780d03a4f.png">

Other notes:

- Having used Xcode for years, I did try quitting Xcode and deleting DerivedData--no joy
- I installed using `brew install swiftgen`; all seemed to go well
- After seeing the error in the playground, I figured maybe I need to create a swiftgen.yml? So I went to my terminal and tried to cd into my cloned Swiftgen folder. I got
```
Required ruby-2.7.4 is not installed.
To install do: 'rvm install "ruby-2.7.4"'
```
(This scares me a bit; I've never gotten a message about ruby (or any app) when simply doing `cd <somefolder>`; I hope I haven't broken my machine.)
- I did `rvm install ruby-2.7.4`; rvm reported about a thousand times that:
```
Error: python@3.8: the bottle needs the Apple Command Line Tools to be installed.
You can install them, if desired, with:
 xcode-select --install
```
- But rvm didn't stop when that happened. It continued and then completed with `Requirements installation failed with status: 1`
- I went back and did `xcode-select --install`
- Then I did `rvm install ruby-2.7.4` again, and it seemed to run ok, but still no joy

Also, in case this helps:
<img width="1431" alt="Screen Shot 2021-12-19 at 13 55 48" src="https://user-images.githubusercontent.com/2438449/146692192-d946c77b-9106-4513-996d-f3651315ac07.png">
The error in the playground persists, and I'm just too discouraged at this point to try anything else. I hope this will be useful in some way for you guys. It seems like an excellent tool

**Comment by SaganRitual** [comment]
Ok, I guess the error message is unrelated, and the playground code seems to be working perfectly, which I can see by changing it slightly
```
let view = UILabel(frame: CGRect(origin: .zero, size: CGSize(width: 100, height: 100)))
view.text = "Hello, World!"
```
And clicking the boxes in the whatever-that-view-is-called:
<img width="953" alt="Screen Shot 2021-12-19 at 14 18 54" src="https://user-images.githubusercontent.com/2438449/146692783-8960e082-6b0c-4ff9-80a4-3ad5f8d620bb.png">
I'll leave this open in case the (apparently unrelated) error message is an issue you guys want to look at.

**Comment by djbe** [comment]
I think that's just Xcode being Xcode: broken in lots of places.

In this case, that `strings` file isn't a normal strings file, but a compiled one (done so by our `rake playground:resources` task). The reason we use a compiled resource is that it otherwise wouldn't work in playgrounds. Resources are in a similar state when you run your macOS/iOS app on a device (or simulator).
