### ISSUE TITLE
New XCAssets template for SwiftUI

### ISSUE THREAD

**Issue by jbossjaslow** [SwiftGen/SwiftGen#912]
Hello, this is my first time contributing to the SwiftGen repo. I've been directed to create an issue before creating a pull request as per the contributing guidelines. I'd appreciate some guidance on which branch to branch off of and anything else I need to know to contribute to this repo.

I've created a template for XCAssets to generate resources for SwiftUI. I noticed that there were a few issues created in the past asking about SwiftUI support, but there weren't any definitive solutions or updates for this on the repo. I had issues swapping between dark and light mode using the normal generated UIKit assets in my SwiftUI components with them. My issues have been fixed completely using my SwiftUI template.

Thanks!

**Comment by OskarGroth** [comment]
I'm not a maintainer but I believe you want to base your PR on the `develop` branch. Reading the comments on other PR's might give you a good idea about requirements. In any case, I'm curious to see your solution.

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
