### ISSUE TITLE
Add // swiftlint:enable all to each default template

### ISSUE THREAD

**Issue by RomanKovalchukDev** [SwiftGen/SwiftGen#914]
Hello. I've faced an issue that swiftlint in one of my projects doesn't work in some files. After further investigation, I've found that all generated files have a command to disable all swiftlint rules, and not enable them ever again. 
Could you please update all templates to include a command that reenables all linter rules?
Example.
```
// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen
...
Template text
...
// swiftlint:enable all
```
Thanks!

**Comment by djbe** [comment]
That line only disables SwiftLint for THAT file, not other files. I recommend opening checking the docs of [SwiftLint](https://github.com/realm/SwiftLint) and/or opening an issue there.

Quote from the SwiftLint docs:
> The rules will be disabled until the end of the file or until the linter sees a matching enable comment
