### ISSUE TITLE
LICENCE should be LICENSE

### ISSUE THREAD

**Issue by DaCuteRaccoon** [SwiftGen/SwiftGen#921]
Although licence is a British spelling of license, GitHub uses the LICENSE spelling. You should probably **rename `LICENCE` to `LICENSE`.**

**Comment by djbe** [comment]
Github detects it just fine though? When I click on that, it just opens our licence file.

<img width="319" alt="Screen Shot 2022-07-20 at 23 50 54" src="https://user-images.githubusercontent.com/641356/180088620-49acb675-c653-4319-b090-737cfe27f3a9.png">
