### ISSUE TITLE
Support derived attributes in the CoreData parser

### ISSUE THREAD

**Issue by ABridoux** [SwiftGen/SwiftGen#928]
The current [`CoreData.Attribute`](https://github.com/SwiftGen/SwiftGen/blob/d498d285867f42ef0c74c5ebd9ddced747831372/Sources/SwiftGenKit/Parsers/CoreData/Attribute.swift#L11) type does not support the [derived attributes](https://developer.apple.com/documentation/coredata/nsderivedattributedescription). I think it would be a benefit for SwiftGen to support this feature. 

For instance it does not make sense to set such a property from the code perspective since CoreData will set its value when the context of the entity is saved. Thus, the generated property could be marked as `private(set)`. In the template, this piece of information could be made available similarly as `isTransient` or `isOptional`. Users could then use that in the template to tune the generated attribute.

I can try to implement this feature. I followed the guidelines and opened an issue to ask for you advice before jumping right in the code part and open a pull request when it's ready.

**Comment by djbe** [comment]
From quickly creating a derived attribute in a model, this is what the XML looks like:
`<attribute name="friendsCount" attributeType="Integer 32" derived="YES" derivationExpression="friends.@count" usesScalarValueType="YES"/>`

So we'd need to add a `isDerived` flag to our attribute, correct? From what I can gather form the docs, there's no need to add the `derivationExpression`.

I don't think the property needs to be "settable" at all, it should only have a getter.

**Comment by djbe** [comment]
@ABridoux created a PR for this feature, mind going through it and/or testing it? To see if it works for your use cases. I honestly haven't used derived attributes yet.

**Comment by ABridoux** [comment]
Thanks for this!
I agree the property should only have a getter although I was not aware this was possible with `NSManaged` (hence the `private(set)`).
I'll try as soon as I can in a test project since it's not something I use currently.
