### ISSUE TITLE
CoreData FetchRequests with distinct class names

### ISSUE THREAD

**Issue by jp-hoehmann** [SwiftGen/SwiftGen#936]
When the CoreData templates generate code for FetchRequests, the name of the targeted entity is used instead of its class name. This results in the generation of code that will not compile for FetchRequests targeting Entities whose class name differs from the entity name.

Specifically the issue is with this line here:
https://github.com/SwiftGen/SwiftGen/blob/d498d285867f42ef0c74c5ebd9ddced747831372/Sources/SwiftGenCLI/templates/coredata/swift5.stencil#L115

I think instead of `fetchedProperty.fetchRequest.entity` it should be `model.entities[fetchedProperty.fetchRequest.entity].className` (and equivalently for the swift4 template). Let me know if you'd like me to make that into a PR.

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.
