### ISSUE TITLE
SceneType' requires that 'ViewController' inherit from 'UIViewController'

### ISSUE THREAD

**Issue by ARIEnergy** [SwiftGen/SwiftGen#938]
Actually my ViewController inherit from UIViewController, and then I run swiftgen ,but it always showed the error

**Comment by ARIEnergy** [comment]
@djbe  Please help me to fix the terrible bug....

@AliSoftware  Any tips to fix the bug??? Thank you so much!

**Comment by djbe** [comment]
You'll need to provide more information, like what your configuration looks like, and maybe your storyboard file. Do you have a small test case that reproduces the error?
