### ISSUE TITLE
Processing multiple files with the same name

### ISSUE THREAD

**Issue by red-beeard** [SwiftGen/SwiftGen#939]
If I specify in the configuration the folder where all the localizations are stored, it will cause an error because there are several files Localizable.strings

R.swift handles all the files and shows warnings if one of the files is missing a key. If SwiftGen could do this, that would be cool.

**Comment by djbe** [comment]
Note: translated OPs russian comment to english, not sure how good the translation is.

Not sure how you'd have multiple localizable.strings files in one folder?

You should point SwiftGen at your `Base.lproj/Localizable.strings` if you have that, or, if your development language is (for example) english, at `en.lproj/Localizable.strings`.

**Comment by red-beeard** [comment]
Here is an example of folders and the desired result. There is a situation when a value for a key is in a file for one language, but not for another.

![2022-07-24 17 15 13](https://user-images.githubusercontent.com/54406512/180651213-7e219336-8ae5-4e36-805b-0a13c3314651.jpg)
![2022-07-24 17 15 25](https://user-images.githubusercontent.com/54406512/180651215-f84477c7-3c29-4a7e-bc8d-161f6aac22a3.jpg)
![2022-07-24 17 15 34](https://user-images.githubusercontent.com/54406512/180651216-605849ad-b794-46ea-a278-03c8eafe819a.jpg)

**Comment by djbe** [comment]
That's wrong, never point SwiftGen at all your languages, always point it at your **development** language. For most people that's either `en.lproj` or `Base.lproj`.

SwiftGen will not check for missing/extra translations, for such things we recommend using dedicated translation tools. For example, if you use something like POEditor (or Weblate, or …), it will tell your translators which strings have issues. Or use a tool like [BartyCrouch](https://github.com/FlineDev/BartyCrouch), which can do that and much more in a build step
