### ISSUE TITLE
When running swiftgen from a command plugin the fonts are not detected because of missing Universal Type Identifier

### ISSUE THREAD

**Issue by doozMen** [SwiftGen/SwiftGen#952]
I looked into the code and the problem seams to be the checks in the `FontParser`

The warning I get is

```
swiftgen: warning: Unable to determine the Universal Type Identifier for file lib/ios/Fonts/Roboto-Medium.ttf
```

Which is declared in the config file as

```
## FONTS

fonts:
  inputs: 
    - lib/ios/Fonts
  outputs:
    templateName: swift5
    params: 
      publicAccess: true
    output: lib/ios/Fonts.swift
```

When running from command line this works. But I use a command plugin to loop over the targets. I'm waiting for #926 to actually use it in a buildtool plugin. But for now I just commented out the code in the fontparser checking for the mentioned identifier, and this works.

But this seams nog ok to just remove the checks. But do the checks have value if you parse the file after and check for the correct extension?

```swift

public enum Fonts {
  public final class Parser: SwiftGenKit.Parser {
    var entries: [String: Set<Font>] = [:]
    private let options: ParserOptionValues
    public var warningHandler: Parser.MessageHandler?

    public init(options: [String: Any] = [:], warningHandler: Parser.MessageHandler? = nil) throws {
      self.options = try ParserOptionValues(options: options, available: Parser.allOptions)
      self.warningHandler = warningHandler
    }

    public static let defaultFilter = filterRegex(forExtensions: ["otf", "ttc", "ttf"])

    public func parse(path: Path, relativeTo parent: Path) throws {
        // TODO: unclear why when runnin in a plugin this check fails, also not clear why check is needed
//      guard let values = try? path.url.resourceValues(forKeys: [.typeIdentifierKey]),
//        let uti = values.typeIdentifier else {
//        warningHandler?("Unable to determine the Universal Type Identifier for file \(path)", #file, #line)
//        return
//      }
//      guard UTTypeConformsTo(uti as CFString, kUTTypeFont) else {
//        warningHandler?("File is not a known font type: \(path)", #file, #line)
//        return
//      }

      let fonts = CTFont.parse(file: path, relativeTo: parent)
      fonts.forEach { addFont($0) }
    }

    private func addFont(_ font: Font) {
      let familyName = font.familyName
      entries[familyName, default: []].insert(font)
    }
  }
}
```

That is what I did in my fork for now. Is there a better solution?

**Comment by djbe** [comment]
The check is there because we want to make sure the files we're passed are actual font files, and not something like json files. 

Very curious that we can't check the UTI for a file. Is this a sandbox issue? I thought package plugins got access to the files in a project?

**Comment by doozMen** [comment]
I'm not sure why it happens and how to avoid it. But it currently makes the current implementation not useable to me. Which is unfortunate. Thanks for the response do.

**Comment by djbe** [comment]
Right, so I've finally been able to reproduce this (SPM plugin dev. is hell). What ends up being executed is something like this:

```bash
DERIVED_SOURCES_DIR=/Users/…/MyExample/.build/plugins/outputs/myexample/MyExample/SwiftGenPlugin /usr/bin/sandbox-exec -p '(version 1)
(deny default)
(import "system.sb")
(allow file-read*)
(allow process*)
(allow file-write*
    (subpath "/private/tmp")
    (subpath "/private/var/folders/vt/ycpry0f913x8x4w1gb0xms680000gn/T")
)
(allow file-write*
    (subpath "/Users/…/MyExample/.build/plugins/outputs/myexample/MyExample/SwiftGenPlugin")
)
' /Users/…/MyExample/.build/artifacts/myplugin/swiftgen.artifactbundle/swiftgen/bin/swiftgen config run --verbose --config /Users/…/MyExample/Sources/MyExample/swiftgen.yml
```

If you execute the same SwiftGen command without the sandbox parts, then the parser works normally. So like I suspected, it's a sandbox issue. The weird thing is that other file parsers can easily read & parse directories and files, so it's not filesystem access. It's somehow loading "resource keys", however they may be different from normal file access.

**Comment by djbe** [comment]
Implemented by SwiftGen 6.6.0, which has been released.

**Comment by kenji21** [comment]
As the warnings are still present, I dig to determine where they are coming from:

https://developer.apple.com/documentation/security/app_sandbox/discovering_and_diagnosing_app_sandbox_violations

To get the detail error:

```
swiftgen: warning: Unable to determine the Universal Type Identifier for file /Users/kenji/.....path-to-Regular.ttf : Error Domain=NSCocoaErrorDomain Code=256 "The file “Regular.ttf” couldn’t be opened." UserInfo={NSURL=file:///Users/kenji/.....path-to-Regular.ttf, NSFilePath=/Users/kenji/.....path-to-Regular.ttf, NSUnderlyingError=0x12d631cd0 {Error Domain=NSOSStatusErrorDomain Code=-10813 "kLSDataUnavailableErr: E.g. no kind string"}}
```

using /usr/bin/sandbox-exec with all the options, only replacing plugin command to: `/Users/kenji/github/SwiftGen/.build/debug/swiftgen` 

and after patching (and `swift build`):
![Screenshot 10](https://github.com/SwiftGen/SwiftGen/assets/1105089/8276f40e-e40b-4ed0-b3c3-ebf0a5f24543)

**Comment by kenji21** [comment]
> As the warnings are still present, I dig to determine where they are coming from:
> 
> https://developer.apple.com/documentation/security/app_sandbox/discovering_and_diagnosing_app_sandbox_violations
> 
> To get the detail error:
> 
> ```
> swiftgen: warning: Unable to determine the Universal Type Identifier for file /Users/kenji/.....path-to-Regular.ttf : Error Domain=NSCocoaErrorDomain Code=256 "The file “Regular.ttf” couldn’t be opened." UserInfo={NSURL=file:///Users/kenji/.....path-to-Regular.ttf, NSFilePath=/Users/kenji/.....path-to-Regular.ttf, NSUnderlyingError=0x12d631cd0 {Error Domain=NSOSStatusErrorDomain Code=-10813 "kLSDataUnavailableErr: E.g. no kind string"}}
> ```
> 
> using /usr/bin/sandbox-exec with all the options, only replacing plugin command to: `/Users/kenji/github/SwiftGen/.build/debug/swiftgen`
> 
> and after patching (and `swift build`): ![Screenshot 10](https://user-images.githubusercontent.com/1105089/270880659-8276f40e-e40b-4ed0-b3c3-ebf0a5f24543.png)

so the fix is really simple, as the `resourceValues(forKeys:)` fails due to sandboxing, simply checking "header bytes" of ttf files does validate files are ttf (or otf) ones : 

![Screenshot 1](https://github.com/SwiftGen/SwiftGen/assets/1105089/39f4b667-1743-48c9-bcf1-eb4bd16b3c60)

https://github.com/SwiftGen/SwiftGen/pull/1080/files#diff-7e96cd2a51a2fcdc429a7adcd14e85b4e948ad4fcc63c1423f0ae55214107100R38-R70

**Comment by twittemb** [comment]
Hi there. I'm having the exact same warning (using the last version 6.6.2). Is there a plan to fix that issue ?
Thanks a lot.

**Comment by kenji21** [comment]
The plan is to use the new release of SwiftGen after https://github.com/SwiftGen/SwiftGen/pull/1080 has been merged
