### ISSUE TITLE
objc-m.stencil: not able to build the project due to a compile error in a generated localization file.

### ISSUE THREAD

**Issue by zummenix** [SwiftGen/SwiftGen#990]
SwiftGen version: 6.6.1

Currently, in the `objc-m.stencil` in the `tr` function the initialization of the variable argument list is done like `va_start(args, key);`,  but it should be `va_start(args, value)` instead, because the `value` is the last named parameter. Otherwise there is a compilation error: `Second argument to 'va_start' is not the last named parameter`

**Comment by djbe** [comment]
Disadvantage of not compiling that output in our tests. At least the compiler tells you it's wrong instead of runtime crashes 😄

**Comment by djbe** [comment]
Fixed in 6.6.2
