### ISSUE TITLE
Internal: correctly set minimum `swift-argument-parser` version

### ISSUE THREAD

**Issue by diederich** [SwiftGen/SwiftGen#992]
I'm seeing a broken build with the 6.6.1 release. This is in an SPM project with constraints on `swift-argument-parser` <= 1.10 (latest swiftlint release).

It looks like swiftgen's [using](https://github.com/SwiftGen/SwiftGen/blob/1db1ca768cdda4a2a1aef785f55167a1812fa9a0/Sources/SwiftGen/Commands/Run.swift#L61) ArgumentParser's `visibility` features, which got introduced in ArgumentParser's 1.1.0 release: https://github.com/apple/swift-argument-parser/releases/tag/1.1.0

Bumping the dependency up would highlight the issue during package resolving vs. at build time.

**Comment by djbe** [comment]
How are you including SwiftGen into your project? Since 6.6 we support SPM plugins, check it out here:
https://github.com/SwiftGen/SwiftGenPlugin

**Comment by djbe** [comment]
But I get your point, I'll be upping the version number in the package.swift file

**Comment by djbe** [comment]
Fixed in 6.6.2
